### ISSUE TITLE
Mercurial 4.7/4.8 compatibility

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#1001]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/1001) by Frédéric Fondement (Bitbucket: [FFondement](https://bitbucket.org/FFondement), ).**

----------------------------------------

Hi there.

I have some issues running mercurial 4.7/4.8 as some of its API changed. Those changes impact fileview and javahg extensions.

I can get them back to work by:

from mercurial import cmdutil, registrar

cmdtable = {}
command = cmdutil.command(cmdtable) -> command = registrar.command(cmdtable) if hasattr(registrar, 'command') else cmdutil.command(cmdtable)

---

and (for fileview only)

from mercurial.utils import dateutil
...
   date = '%d %d' % util.parsedate(linkrev.date()) ->    date = '%d %d' % **dateutil**.parsedate(linkrev.date())

(see https://phab.mercurial-scm.org/D2055#change-7jHmgUrhh7BF)

For the latter, I'm not sure how to handle both old and newer mercurial versions though...

Cheers,

**Comment by sdorra** [comment]
SCM-Manager 2 support recent mercurial versions.
