### ISSUE TITLE
build scm-manager Failed to execute goal

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#1016]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/1016) by bill (Bitbucket: [1191149398](https://bitbucket.org/1191149398), GitHub: [1191149398](https://github.com/1191149398)).**

----------------------------------------

build scm-manager 2.0.0

修订集:
7545 (434a009a46ac) Merged in feature/css_round_panel (pull request #238) …

Failed to execute goal com.github.sdorra:buildfrontend-maven-plugin:2.2.0:run (bootstrap) on project scm-ui-components: Execution bootstrap of goal com.github.sdorra:buildfrontend-maven-plugin:2.2.0:run failed: java.io.IOException: process ends with exit value 1 -> [Help 1]

**Comment by sdorra** [comment]
@1191149398 could please try to build the last version of the develop branch?
