### ISSUE TITLE
Implement Anonymous access to public repos through web interface

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#1028]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/1028) by Former user (Bitbucket: [Former user](https://bitbucket.org/Former user), ).**

----------------------------------------

Apparently, the only way currently to access a repo which has been set to readable anonymously is through a SCM client. It would be useful to allow access through the web interface too, such that SCM Manager could be used to host and share personal codebases.

Ideally, the interface will show the repository directly when visiting the link to the repo, with a “Log In” button at the top.

PS. While this is in works, is it possible for us to edit the landing page? A temporary workaround can be to create a new unpriviledged user and put their credentials on the landing page itself to allow people to login and access the code from their browsers.

‌

**Comment by pfeuffer** [comment]
An editable landing page is of some risk, so we do not think this is a good way to start with.
Please note, that in SCM-Manager 2.x you can configure a *Login Info URL*, providing the tips on the righthand side. Maybe you can use this.
