### ISSUE TITLE
possibility to remove /scm from url path like in 1.60

### ISSUE THREAD

**Issue by Metzlmane** [scm-manager/scm-manager#1035]
I tried to set the base path in 2.0.0-rc4 to https://sth.domain/svn
but it reappears with https: and :443 at the end in the general options.
If i remove the /scm so that there is onle /svn/repository, thee webinterface fails

Is it possible to set the path like in version 1.6 to https://sth.domain/svn/reponame?
It would avoid to force all clients to relocate the repositories

**Comment by eheimbuch** [comment]
Hey Metzlmane,

it should be possible to remove the "/scm" context path like you did in version 1.60. 

After the migration to 2.0.0-rc4 there now exist redirects for all your repositories. This means unfornutalety your users have to relocate their repositories but the relocation command will be proposed on "svn checkout".

Best regards.

**Comment by Metzlmane** [comment]
I set the base path and created a new repository, but it still showed /scm in the path. I'll give it another try tomorrow

**Comment by HipDragon** [comment]
This web interface shows loading scm-svn-plugin when you change the context from /scm to just /. There is no information provided in the logs about why this is either.

**Comment by pfeuffer** [comment]
This issue will be fixed with the release of #1182 (probably in release 2.1.0)
