### ISSUE TITLE
Invalid character in file name causes invalid cloning in Windows 

### ISSUE THREAD

**Issue by 40rn05lyv** [scm-manager/scm-manager#1048]
Execute `git clone https://github.com/scm-manager/scm-manager.git`
Open /docs/v2/ directory
You can see that file "UI: Additions or Changes to ui-components or ui-types.md" was cloned with name "UI", because ":" is not allowed in Windows file names.

Please, fix it.

**Comment by pfeuffer** [comment]
Thanks for the hint!

I've fixed this on the `develop` branch. I'm afraid we cannot fix it for older versions, though (we had the release in the meantime).

Hope this works for you, and thanks again.

**Comment by 40rn05lyv** [comment]
Commit https://github.com/scm-manager/scm-manager/commit/58821f47edd61f041948f30637ac8a34f25558e2
