### ISSUE TITLE
Failed to build sources: "spawnSync yarn ENOENT"

### ISSUE THREAD

**Issue by 40rn05lyv** [scm-manager/scm-manager#1049]
It's not possible to build sources on clean environment.
The build fails with "spawnSync yarn ENOENT" error (in file scm-ui/ui-scripts/src/lerna.js)
To fix it I need to
1. Install yarn globally:
`npm install yarn --global`
2. Change the `lerna.js` file. 
From
`  const result = spawnSync("yarn", args, { stdio: "inherit" });`
to
`  const result = spawnSync("yarn.cmd", args, { stdio: "inherit" });`

Please, fix this issue.

**Comment by pfeuffer** [comment]
Am I guessing right that you are running this on Windows?

**Comment by 40rn05lyv** [comment]
Yes, it's Windows.
