### ISSUE TITLE
scm-archive-plugin SCM 1.6

### ISSUE THREAD

**Issue by JoeriBouchet** [scm-manager/scm-manager#1054]
We're running SCM Manager 1.6. in the UI under plugins I wanted to install the scm-archive-plugin, yet http://bitbucket.org/sdorra/scm-manager/scm-plugins/scm-archive-plugin does not seem to be a valid link anymore. 
I read that SCM had moved to github, yet, I could not find this plugin in the repository. 

Somehow I did find the source on https://bitbucket.org/sdorra/scm-archive-plugin/src/default/ , but could not find an installable package. Is there ANY way to avoid building it from the source code ?

Thank in advance

**Comment by sdorra** [comment]
Have you tried to install it over the "install" link on the plugins ui=

**Comment by JoeriBouchet** [comment]
Hello Sebastian, 

Thx for the reply. 
Yes I have. In the UI I get a pop up window: Plugin installation failed

In the logs:
2020-03-19 08:24:02.892 [qtp608188624-35] INFO  sonia.scm.plugin.AetherPluginHandler - try to install plugin with gav: sonia.scm.plugins:scm-archive-plugin:1.1
2020-03-19 08:24:02.892 [qtp608188624-35] INFO  sonia.scm.plugin.AetherDependencyResolver - create repository system session

In the scm-server.err:
Caused by: 
sonia.scm.plugin.PluginException: could not collect dependencies or store classpath file
	at …..
Caused by: 
org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for sonia.scm.plugins:scm-archive-plugin:jar:1.1
	at …..
Caused by: 
org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for sonia.scm.plugins:scm-archive-plugin:jar:1.1
	at …..
Caused by: 
org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact sonia.scm.plugins:scm-archive-plugin:pom:1.1 from/to central (https://repo1.maven.org/maven2/): Proxy Authentication Required (407)
	at …..
Caused by: 
org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact sonia.scm.plugins:scm-archive-plugin:pom:1.1 from/to central (https://repo1.maven.org/maven2/): Proxy Authentication Required (407)
	at …..
Caused by: 
org.apache.http.client.HttpResponseException: Proxy Authentication Required (407)
	at …..

I can give you the full java dump if you want.
Any ideas? 

Thanks in advance.

**Comment by sdorra** [comment]
It looks like you are using an proxy which requires authentication:

```
org.apache.http.client.HttpResponseException: Proxy Authentication Required (407)
```

Have you configured your proxy with authentication in the settings of scm-manager?

**Comment by JoeriBouchet** [comment]
Yes we did.
I tested on the SCM server the connection through proxy and it works fine.
However, in the log file I noticed it is trying to connect to (https://repo1.maven.org/maven2/). 
Testing the connection with wget from the SCM server to this url fails with Proxy request sent, awaiting response... 403 Forbidden
2020-03-19 12:33:39 ERROR 403: Forbidden.

When I check this URL , I cannot find anything that refers to scm plugins?
Is this correct? 

In the UI , we have as plugin repository "http://plugins.scm-manager.org/scm-plugin-backend/api/{version}/plugins?os={os}&arch={arch}&snapshot=false". Again, I'm doubting this is correct.

As workaround, we currently found the needed jar files on https://maven.scm-manager.org/nexus/content/repositories/releases/sonia/scm/plugins/scm-archive-plugin/1.1/ 
moved this to the server and manually edited the classpath.xml file 
Then restarted the service. 

I would love to get the UI running though. I haven't tried with installing other plugins, but I doubt they will work. 

Can you please check the plugin repository is correct and which was we should use?

Thanks in advance

**Comment by sdorra** [comment]
SCM-Manager 1.x uses Maven for the installation of its plugins. Maven uses several sources for their dependencies. In SCM-Manager those sources are currently:

* https://repo1.maven.org/maven2
* http://maven.scm-manager.org/nexus/content/groups/public/

You can see this in the repositories section of the e.g.: [plugin center api](http://plugins.scm-manager.org/scm-plugin-backend/api/1.60/plugins?os=linux).

The repo1.maven.org is required, because each plugin can have dependencies in form of a java library which must be downloaded from the maven central repo (repo1.maven.org).

This behaviour changes completely with scm-manager 2. In scm-manager 2.x a plugin is a single file which contains all of its dependencies.

**Comment by JoeriBouchet** [comment]
Is still don't understand why wget over proxy for  https://repo1.maven.org/maven2 returns 
Testing the connection with wget from the SCM server to this url fails with Proxy request sent, awaiting response... 403 Forbidden
2020-03-19 12:33:39 ERROR 403: Forbidden.

and a same request to http://maven.scm-manager.org/nexus/content/groups/public/ succeeds without problems. 

That should tell me the proxy authentication is correct. 
Is there something different that https://repo1.maven.org/maven2 requires which may interfere with the way it handles the request by the proxy?

I understand it will be time to upgrade to 2.x , and this is being scheduled.
In the meantime I do wish to ensure there is a stable way to get plugins though. This used to work ...

**Comment by JoeriBouchet** [comment]
Update:
When I specify a user agent (-U) in my wget from the scm server, I do get a successful connect:
command used:
https_proxy=http://<our proxy server>:8080/ wget -U 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0' -O - --proxy-user=scmadmin --proxy-password='<our proxy pwd>' https://repo1.maven.org/maven2/

So this says to me the connection over the proxy to maven is fine. 
But still for some reason the code in SCM does not translate to that ?

Cheers

**Comment by sdorra** [comment]
Could you enable debug logging and check for the lines like:

* enable proxy selector to collect dependencies
* enable proxy ... for ...

Do you have access to the access.log of the proxy server?

**Comment by JoeriBouchet** [comment]
Hello again, 
Yes I have access to the acces logs of the proxy server.
IMPORTANT note: I am having the issue with other plugins as well. I am testing now with the scm-sample-hello plugin giving the same issue. So we may want to change the issue title?

Here are the outputs requested: 
note1: the log from the proxy server is from before I enabled debugging on SCM) 
note2: ip addresses suppressed

proxy server access log:

When I go to the plugin page in the SCM manager UI

`<IPv4addr> - scmadmin [20/Mar/2020:08:38:01 +0100] "GET http://plugins.scm-manager.org/scm-plugin-backend/api/1.60/plugins?os=Linux&arch=64&snapshot=false HTTP/1.1" 200 21651 "-" "Java/1.8.0_242"`

When clicking on install for scm-sample-hello

`<IPv4addr> - - [20/Mar/2020:08:39:12 +0100] "CONNECT repo1.maven.org:443 HTTP/1.1" 407 415 "-" "Aether"
<IPv4addr> - - [20/Mar/2020:08:39:12 +0100] "GET http://maven.scm-manager.org/nexus/content/groups/public/sonia/scm/sample/scm-sample-hello/1.60/scm-sample-hello-1.60.pom HTTP/1.1" 407 415 "-" "Aether"`

UI just gives pop up window “Installation Failed”

Repeated with debug logging on (<logger name="sonia.scm" level="TRACE" />)

scm access log:

`<IPv6addr> - - [20/Mar/2020:09:19:04 +0100] "GET /scm/api/rest/plugins/overview.json HTTP/1.1" 200 3156 "https://scm.cs.kuleuven.be/scm/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
<IPv6addr> - - [20/Mar/2020:09:19:21 +0100] "POST /scm/api/rest/plugins/install/sonia.scm.sample:scm-sample-hello:1.60.json HTTP/1.1" 500 83878 "https://scm.cs.kuleuven.be/scm/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
<IPv6addr> - - [20/Mar/2020:09:19:22 +0100] "GET /scm/resources/extjs/resources/images/default/window/icon-error.gif HTTP/1.1" 304 - "https://scm.cs.kuleuven.be/scm/resources/bbf05a9447a19d65bc259727b99af096996ecdf6.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"`

scm server log:

When I go to the plugin page in the UI

`2020-03-20 09:19:04.388 [qtp608188624-35] INFO  sonia.scm.plugin.DefaultPluginManager - fetch plugin informations from http://plugins.scm-manager.org/scm-plugin-backend/api/1.60/plugins?os=Linux&arch=64&snapshot=false
2020-03-20 09:19:04.391 [qtp608188624-35] DEBUG sonia.scm.net.ahc.DefaultAdvancedHttpClient - fetch 'http://plugins.scm-manager.org/scm-plugin-backend/api/1.60/plugins?os=Linux&arch=64&snapshot=false' using proxy oauthproxy.cs.kuleuven.be:8080
2020-03-20 09:19:04.399 [qtp608188624-35] DEBUG sonia.scm.net.ahc.DefaultAdvancedHttpClient - append proxy authentication header for user scmadmin
2020-03-20 09:19:04.569 [qtp608188624-35] DEBUG sonia.scm.plugin.Aether - enable proxy oauthproxy.cs.kuleuven.be for https://repo1.maven.org/maven2/
2020-03-20 09:19:04.574 [qtp608188624-35] DEBUG sonia.scm.plugin.Aether - enable proxy oauthproxy.cs.kuleuven.be for http://maven.scm-manager.org/nexus/content/groups/public/`

When clicking on install for scm-sample-hello

`2020-03-20 09:19:21.931 [qtp608188624-32] TRACE sonia.scm.security.XsrfProtectionFilter - xsrf protection is disabled, skipping check
2020-03-20 09:19:21.931 [qtp608188624-32] TRACE sonia.scm.web.filter.AutoLoginFilter - user is allready authenticated
2020-03-20 09:19:21.931 [qtp608188624-32] TRACE sonia.scm.web.filter.AutoLoginFilter - user is allready authenticated
2020-03-20 09:19:21.932 [qtp608188624-32] INFO  sonia.scm.plugin.AetherPluginHandler - try to install plugin with gav: sonia.scm.sample:scm-sample-hello:1.60
2020-03-20 09:19:21.936 [qtp608188624-32] INFO  sonia.scm.plugin.AetherDependencyResolver - create repository system session
2020-03-20 09:19:21.944 [qtp608188624-32] DEBUG sonia.scm.plugin.Aether - enable proxy selector to collect dependencies
2020-03-20 09:19:22.415 [qtp608188624-37] TRACE sonia.scm.web.filter.AutoLoginFilter - user is allready authenticated`

output server.err (omitted “at ”):

`Mar 20, 2020 9:19:22 AM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
sonia.scm.plugin.PluginException: could not collect dependencies or store classpath file
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for sonia.scm.sample:scm-sample-hello:jar:1.60
	... 122 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for sonia.scm.sample:scm-sample-hello:jar:1.60
	... 127 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact sonia.scm.sample:scm-sample-hello:pom:1.60 from/to central (https://repo1.maven.org/maven2/): Proxy Authentication Required (407)
	... 129 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact sonia.scm.sample:scm-sample-hello:pom:1.60 from/to central (https://repo1.maven.org/maven2/): Proxy Authentication Required (407)
	... 132 more
Caused by: org.apache.http.client.HttpResponseException: Proxy Authentication Required (407)
	... 137 more

2020-03-20 09:19:22.167:WARN:oejs.ServletHandler:
javax.servlet.ServletException: Filtered request failed.
Caused by: 
sonia.scm.plugin.PluginException: could not collect dependencies or store classpath file
Caused by: 
org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for sonia.scm.sample:scm-sample-hello:jar:1.60
Caused by: 
org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for sonia.scm.sample:scm-sample-hello:jar:1.60
Caused by: 
org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact sonia.scm.sample:scm-sample-hello:pom:1.60 from/to central (https://repo1.maven.org/maven2/): Proxy Authentication Required (407)
Caused by: 
org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact sonia.scm.sample:scm-sample-hello:pom:1.60 from/to central (https://repo1.maven.org/maven2/): Proxy Authentication Required (407)
Caused by: 
org.apache.http.client.HttpResponseException: Proxy Authentication Required (407)
2020-03-20 09:19:22.172:WARN:oejs.ServletHandler:/scm/api/rest/plugins/install/sonia.scm.sample:scm-sample-hello:1.60.json
sonia.scm.plugin.PluginException: could not collect dependencies or store classpath file
Caused by: 
org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for sonia.scm.sample:scm-sample-hello:jar:1.60
Caused by: 
org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for sonia.scm.sample:scm-sample-hello:jar:1.60
Caused by: 
org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact sonia.scm.sample:scm-sample-hello:pom:1.60 from/to central (https://repo1.maven.org/maven2/): Proxy Authentication Required (407)
Caused by: 
org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact sonia.scm.sample:scm-sample-hello:pom:1.60 from/to central (https://repo1.maven.org/maven2/): Proxy Authentication Required (407)
Caused by: 
org.apache.http.client.HttpResponseException: Proxy Authentication Required (407)`

**Comment by sdorra** [comment]
Ok, the proxy access log are showing that the credentials are send during descriptor fetch but not from the maven sub system:

```
<IPv4addr> - scmadmin [20/Mar/2020:08:38:01 +0100] "GET http://plugins.scm-manager.org/scm-plugin-backend/api/1.60/plugins?os=Linux&arch=64&snapshot=false HTTP/1.1" 200 21651 "-" "Java/1.8.0_242"
<IPv4addr> - - [20/Mar/2020:08:39:12 +0100] "CONNECT repo1.maven.org:443 HTTP/1.1" 407 415 "-" "Aether" <IPv4addr> - - [20/Mar/2020:08:39:12 +0100] "GET http://maven.scm-manager.org/nexus/content/groups/public/sonia/scm/sample/scm-sample-hello/1.60/scm-sample-hello-1.60.pom HTTP/1.1" 407 415 "-" "Aether"
```

 Which is really strange, because the scm-manager log shows that scm-manager configures aether (the maven sub system) to send the credentials:

```
2020-03-20 09:19:04.569 [qtp608188624-35] DEBUG sonia.scm.plugin.Aether - enable proxy oauthproxy.cs.kuleuven.be for https://repo1.maven.org/maven2/ 
2020-03-20 09:19:04.574 [qtp608188624-35] DEBUG sonia.scm.plugin.Aether - enable proxy oauthproxy.cs.kuleuven.be for http://maven.scm-manager.org/nexus/content/groups/public/
```

Do you use any special kind of proxy authentication or do you use basic authentication?

**Comment by JoeriBouchet** [comment]
Hello,

Thanks for your reply. 
We use basic authentication. From conf file:

AuthType Basic

Cheers

**Comment by sdorra** [comment]
Ok, it looks like a bug. Are you planning to migrate to scm-manager v2 in the near time? Because v2 should not be affected by this.
