### ISSUE TITLE
Chown in Dockerfile

### ISSUE THREAD

**Issue by ThirtySomething** [scm-manager/scm-manager#1067]
Hello, everybody,

the SCM Manager is a great software. You do that very well.

I try to use the SCM Manager with Docker and use the official container from [hub.docker.com](https://hub.docker.com/r/sdorra/scm-manager) - but I have a somewhat unusual environment: I want to save the Docker volume on another computer. Therefore I create the volume as follows:

```
sudo docker volume create \
    --driver local \
    --opt type=nfs4 \
    --opt o=addr=<IP of other system>,rw \
    --opt device=:/volume1/dockerfs/v_scm_manager \
    --name v_scm_manager
```

Then I try to install/run the SCM Manager with:

```
sudo docker run -dit \
    --restart unless-stopped \
    --name scm_manager \
    -p 8080:8080 \
    -v v_scm_manager:/var/lib/scm \
    -d sdorra/scm-manager:latest
```

Unfortunately, that doesn't work. An error message appears, namely:

```
docker: Error response from daemon: failed to copy file info for /var/lib/docker/volumes/v_scm_manager/_data: failed to chown /var/lib/docker/volumes/v_scm_manager/_data: lchown /var/lib/docker/volumes/v_scm_manager/_data: invalid argument.
```

On the [internet I found hints](https://www.google.com/search?q=chown+in+dockerfile) that the chown command in Dockerfiles might not be that good. Is the chown command really necessary in the docker file? Unfortunately, I don't know how to fix the problem now.

Could you please rate it and correct it if necessary?

Greetings

ThirtySomething

**Comment by sdorra** [comment]
Hello,
We could not remove the chown, because we are running as a separate user for security reasons. 

I could not reproduce the issue. Even with a named nfs volume, the container starts and creates its home. Perhaps you have not enough rights to change the ownership. I think the machine which starts the scm-manager container needs the **no_root_squash** option.

**Comment by ThirtySomething** [comment]
Hello,

I understand the concept of using a separate user for security reasons. I even like that.

I had thought about the possibility of using the `HOME `directory of the SCM user instead of the `/opt` or `/var` directories.

As far as I know, all files/folders automatically get the correct settings for user and group when run with the appropriate user.

Unfortunately I was not able to execute a su command in the Dockerfile. Here my knowledge is not sufficient. Would that work somehow? Then the chown command would not be necessary.

The fact that the error is not reproducible confuses me. Maybe I should take a closer look at the configuration of NFS. On the computer which provides the NFS share, the following configuration is available:

`/volume1/dockerfs <My Network BASE>/24(rw,async,no_wdelay,crossmnt,no_root_squash,insecure_locks,sec=sys,anonuid=1025,anongid=100)`

The anonuid/anongid maps to an internal user. Maybe this is the problem?

The computer that starts the container is the client - here I wouldn't know how to set the 'no_root_squash' option. Isn't that defined when creating the Docker Volume?

**Comment by sdorra** [comment]
I don't like the idea of starting process as root, creating the necessary structure and switching than to an unprivileged user. Because we must move the logic for the creation of the home folder into a start script and this start script have to wrap the scm-server script.

I don't know it anon props causes the problem. Here is what i have tried to reproduce the problem. First i've created the nfs share on a separate machine with the following options:

```
"/storage/scm-home" 10.0.42.0/24(rw,nohide,async,no_subtree_check,insecure,no_root_squash)
```

After that i created the docker volume on the client machine:

```bash
docker volume create \
    --driver local \
    --opt type=nfs4 \
    --opt o=addr=10.0.42.4,rw \
    --opt device=:/storage/scm-home \
    --name scm-home
```

Than i started scm-manager with the mounted volume:

```bash
docker run -d --name scm -v scm-home:/var/lib/scm -p 8080:8080 sdorra/scm-manager:1.60
```

The *no_root_squash* option is configured on the server side and is not required on the client.

**Comment by ThirtySomething** [comment]
Please excuse my late reply.

Please do not be annoyed, I do not want to change the concept of how the container is used. If I understood that correctly, the setup is done in the `RUN` areas. The container itself is started with the user specified under `USER`. In theory I would have adjusted the setup a bit - I would create the user with a `HOME` directory for example. Then I would download the SCM Manager with the user `SCM` and unpack it in his `HOME`. In this case all files would automatically have the correct assignments and the `chown` command would be obsolete. But this would imply other problems, because the directory structure would not be in the usual place in `/opt` or `/var`.

Regardless of this, I have also tried to use the suggested NFS settings. Unfortunately this did not work. Not working means that the computer on which NFS is set up is actually a NAS. And the NAS overwrites the settings immediately when I restart the NFS service.

I think that my NAS is the problem and I cannot use the default container because of that. I have to see if I can build my own container that can work with the limitations of the NAS or if I have to find a completely different solution.

Thank you very much for your help and engagement.
