### ISSUE TITLE
@XmlRootElement usage in some classes

### ISSUE THREAD

**Issue by 40rn05lyv** [scm-manager/scm-manager#1130]
Hi, 

I tried to extend scm-core with some custom Git operation and noticed that classes in `scm-core/src/main/java/sonia/scm/repository` package (like BlameResult, ChangesetPagingResult, Branches etc.) have `@XmlRootElement` annotation on them even though they are not stored anywhere on file system (AFAIK). Is it some kind of legacy stuff?

**Comment by sdorra** [comment]
This is a leftover from SCM-Manager v1. The dto layer was introduced with v2. These objects are marshalled in the rest layer as xml and json in v1.

**Comment by sdorra** [comment]
It should be safe to remove those annotations.
