### ISSUE TITLE
/diff/parsed - add support for "rename" and "copy"

### ISSUE THREAD

**Issue by 40rn05lyv** [scm-manager/scm-manager#1132]
Hi,
As I know JGit supports Add, Modify, Delete, Rename and Copy change types. (org.eclipse.jgit.diff.DiffEntry.ChangeType), but DiffResultToDiffResultDtoMapper only returns the first three.
Are there plans to add Rename and Copy too?

**Comment by sdorra** [comment]
Yes, this is definitely on our list.
