### ISSUE TITLE
DiffCommandRequest - incorrect equals & hashcode 

### ISSUE THREAD

**Issue by 40rn05lyv** [scm-manager/scm-manager#1139]
DiffCommandRequest has additional fields comparing to its superclass ("format" and "ancestorChangeset"), but doesn't overwrite equals and hashcode methods.
(upd. actually not an issue for now, since it's not used as key for caching)

**Comment by pfeuffer** [comment]
Hi, you are right. Looks like this is the case for other sub classes of FileBaseCommandRequest, too. Thank you for the hint!
