### ISSUE TITLE
Add option to save folder structure as /<namespace>/<reponame> scm-manager2

### ISSUE THREAD

**Issue by pwatt01** [scm-manager/scm-manager#1150]
when trying to change things in a root repository, it is very hard to find as all the folder names are random IDs. Is it possible to have an option or change the way scmmanger2 saves the repositories to make them easier to navigate?

**Comment by pfeuffer** [comment]
Hi!

One of the top requests in SCM-Manager was the possibility to rename repositories. So we made the decision not to use any name related elements for the path. If you want to find a specific repository, you can use grep to find your repository. In your repository folder simply call:

`grep my-repo-name */metadata.xml`

Further you can manually move your repositories to an arbitrary location (you just have to keep `data`, `store` and `metadata.xml` together in one folder). All you have to do is to set the path in `repository-paths.xml` afterwards (and don't do it while SCM-Manager is running).

In the long run the plan is to add features for this to SCM-Manager, but we have not gotten this far, yet.

Hope this helps for now.

René
