### ISSUE TITLE
SCM-Manager 2.0.0 Error in javahg.py

### ISSUE THREAD

**Issue by nanek-hg** [scm-manager/scm-manager#1179]
## Issue description
Error in javahg.py

### Bug Report
I installed SCM-Manager 2.0.0 for Windows and noticed errors when working with Mercurial.

#### Describe how to reproduce the bug

I have created an empty repository and click on </> Code on the right. I have no error on the page, but there is an error in the logs.

#### Describe your SCM-Manager setup
SCM-Manager 2.0.0 for Windows
mercurial-4.9.1.win-amd64-py2.7
Python 2.7.18
java 14.0.1

#### Log of the bug
cze 10, 2020 12:02:03 PM com.aragost.javahg.log.JULLogger info
INFO: Copy resource /javahg.py to C:\WINDOWS\system32\config\systemprofile\.javahg\tmp\1591783323298-0\javahg.py
cze 10, 2020 12:02:07 PM com.aragost.javahg.log.JULLogger error
SEVERE: stderr from Mercurial: *** failed to import extension javahg from C:\WINDOWS\system32\config\systemprofile\.javahg\tmp\1591783323298-0\javahg.py: 'module' object has no attribute 'command'

#### Further information
It seems to me that in javahg.py:
line 32 should be changed from
from mercurial import util, commands, cmdutil, lock, extensions
to
from mercurial import util, commands, cmdutil, lock, extensions, registrar
and
line 42 should be changed from
command = cmdutil.command (cmdtable)
to
command = registrar.command (cmdtable)

cmdutil.comand is invalid since Mercurial 4.7

**Comment by pfeuffer** [comment]
Thank you for this information, @nanek-hg !
