### ISSUE TITLE
Changing the context from /scm to / results in loading forever

### ISSUE THREAD

**Issue by HipDragon** [scm-manager/scm-manager#1181]
The issue is when you change the context from /scm to /, and remove the required docroot. The page will stall out on loading scm-svn-plugin, it just spins an image forever.

Looking at the network traffic it stops at assets/assets/scm-svn-plugin.bundle.js

Below is the changes to server-config.xml

  

```XML 
  <New id="scm-webapp" class="org.eclipse.jetty.webapp.WebAppContext">
     <Set name="contextPath">/</Set>
     <Set name="war">
       <SystemProperty name="basedir" default="."/>/var/webapp/scm-webapp.war</Set>
     <!-- disable directory listings -->
     <Call name="setInitParameter">
       <Arg>org.eclipse.jetty.servlet.Default.dirAllowed</Arg>
       <Arg>false</Arg>
     </Call>
     <Set name="tempDirectory">/var/cache/scm/work/webapp</Set>
   </New>

   <Set name="handler">
     <New class="org.eclipse.jetty.server.handler.HandlerCollection">
       <Set name="handlers">
         <Array type="org.eclipse.jetty.server.Handler">
           <Item>
             <Ref id="scm-webapp" />
           </Item>
         </Array>
       </Set>
     </New>
   </Set>
```
I tried this on Firefox and am running the server on RedHat 8 EL.

**Comment by sdorra** [comment]
Related to #1035

**Comment by pfeuffer** [comment]
Thank you for the hint! Fix should be released next week or the week after.

**Comment by HipDragon** [comment]
You're welcome, I compiled that one change and stuck it into the current release war file. It seems to solve the issue and I'm not see any other issues so far from that change. I'm looking forward to the official release to replace my hotfix. 😃
