### ISSUE TITLE
Push a mercurial repository error 

### ISSUE THREAD

**Issue by SaboShao** [scm-manager/scm-manager#1190]
realm: SONIA :: SCM Manager
abort: remote error:
Mercurial/Python process ends with return code 2

**Comment by pfeuffer** [comment]
Can you please use `hg push -v` for verbose output? And an excerpt of the corresponding server log may be helpful, too.

**Comment by SaboShao** [comment]
The log just follow:
abort: remote error:
Mercurial/Python process ends with return code 2

I have grant all permission to scmadmin

**Comment by SaboShao** [comment]
python version is 2.7
Mercurial version is 5.9.2

**Comment by SaboShao** [comment]
sonia.scm.web.cgi.DefaultCGIExecutor - C:\Python27\python.exe: can't open file 'C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\SCM-Manager\lib\python\hgweb.py': [Errno 2] No such file or directory;
But this file is really exist.

**Comment by pfeuffer** [comment]
Can you tell us more about your hg installation? Can you push to other hg servers? The error message can also occure, when other files are missing.

**Comment by SaboShao** [comment]
actually， I could not initialize a mercurial repository while I create it.
Internal repository error

There was an error or an unexpected condition while handling the native repository. Please consult the logs for further information.

Context

Repository: scmadmin/Salbo
Transaction ID 3zS28O9IfGL
![Uploading image.png…]()

**Comment by SaboShao** [comment]
HG Binary 
C:\Python27\Scripts\hg.bat
Python Binary 
C:\Python27\python.exe
Python Module Search Path 
C:\Python27\Lib\site-packages\mercurial
Encoding 
UTF-8

**Comment by pfeuffer** [comment]
Sorry, but somehow your logs are not attached. Can you try once again?

However, there may be issues with Mercurial 5.x. We will ship a fix for versions > 4.7 this week. Can you try with a mercurial 4.7?

**Comment by SaboShao** [comment]
OK , I will try later
