### ISSUE TITLE
v1.6 to v2.0 conf conflict during installation

### ISSUE THREAD

**Issue by mshortall** [scm-manager/scm-manager#1194]
**## Issue description**

With scm-server-1.6.0 installed, performing yum install scm-server failed due to the following during yum transaction check:
Transaction check error:
 file /opt/scm-server/conf from install of scm-server-2.0.0-1.noarch conflicts with file from package scm-server-0:1.60-20180504T09:15:11Z.noarch

To work around this issue, the scm-server-1.6.0 package was removed prior to installing scm-server-2.0.0. However, the scm-server-2.0.0 install hit an error while writing to /opt/scm-server/conf as well.

Running transaction
 Installing : scm-server-2.0.0-1.noarch                                                           1/1 
Error unpacking rpm package scm-server-2.0.0-1.noarch
error: unpacking of archive failed on file /opt/scm-server/conf: cpio: rename
 Verifying : scm-server-2.0.0-1.noarch                                                           1/1 
Failed:
 scm-server.noarch 0:2.0.0-1                                                                   
Complete!

**### Bug Report**

#### Describe how to reproduce the bug
With scm-server 1.6.0 installed and after configuring the yum.repos.d/SCM-Manager.repo config:
sudo yum install scm-server

To replicate the unpacking archive error:
sudo yum remove scm-server-1.6.0
sudo yum install scm-server-2.0.0

**#### Describe your SCM-Manager setup**

**What plugins and what versions do you use?** 
scm-git-plugin
scm-hg-plugin
scm-legacy-plugin
scm-svn-plugin

**Are you using a server like tomcat?** 
nginx

**Do you have special settings like proxies? Are you running your instance behind a reverse proxy?**
behind reverse proxy

**#### Which operating system, browser and versions do you use?**
CentOS Release 6.9
Google Chrome V 83.0.4103.97

Windows, Mac or Linux? Chrome, Firefox or IE? What versions?
MAC & Linux
Google Chrome V 83.0.4103.97

**#### Log of the bug**
Transaction check error:
 file /opt/scm-server/conf from install of scm-server-2.0.0-1.noarch conflicts with file from package scm-server-0:1.60-20180504T09:15:11Z.noarch

**After removing the 1.6.0 manager and attempting install of scm-manager-2.0.0:**
Running transaction
 Installing : scm-server-2.0.0-1.noarch                                                           1/1 
Error unpacking rpm package scm-server-2.0.0-1.noarch
error: unpacking of archive failed on file /opt/scm-server/conf: cpio: rename
 Verifying : scm-server-2.0.0-1.noarch                                                           1/1 
Failed:
 scm-server.noarch 0:2.0.0-1                                                                   
Complete!

**#### Further information like screenshots**

Uninstalling scm-server-1.6.0 prior to installing scm-server-2.0.0 worked around the initial conf issue.

To work around the unpacking archive issue, /opt/scm-server was moved to a stored location.

**Comment by pfeuffer** [comment]
Due to the fact that this is a new installation of SCM-Manager, we cannot really handle this in our yum package. Your fix to delete the old `/opt/scm-server` seems to be the right solution.

We added a hint in the troubleshooting section for yum installation.

Thank you for your detailed contribution!
