### ISSUE TITLE
SCM Manager web server not handling spaces in name of files in SVN repo

### ISSUE THREAD

**Issue by BrendanKOz** [scm-manager/scm-manager#1197]
## Issue description

Running a Subversion repository on SCM-Manager 2.0.0.
Repository is monitored by Atlassian Fisheye.
Indexing of repo fails with the following error:

PROPFIND of '<removed>': 400 Illegal character SPACE= (<removed>) 

Possibly related to: [https://issues.tmatesoft.com/issue/SVNKIT-491](https://issues.tmatesoft.com/issue/SVNKIT-491)

#### Describe how to reproduce the bug

Install subversion repository, with at least one file in the subversion history containing a space.
Attempt to index repository from software using SVNKit (Java based svn software)

#### Describe your SCM-Manager setup

SCM Manager 2.0.0
No proxy
Plugins for Hg, SVN, Git.

#### Which operating system, browser and versions do you use?

Windows Server

**Comment by eheimbuch** [comment]
Hey BrendanKOz,

sorry that it took some time, but now we can confirm that spaces in filenames shouldn't be a matter with SCM-Manager. We also use SVNKit in the SCM-SVN-Plugin and i couldn't find any issues with files containing spaces at all. 

Does your described issue only occur using fisheye?

**Comment by BrendanKOz** [comment]
Hi eheimbuch,

Fisheye is the only system that has demonstrated this error at this time.

**Comment by eheimbuch** [comment]
Hi BrendanKOz,

if we cannot reproduce this error without fisheye, we are afraid we cannot really help that much. When you are able to reproduce an error without fisheye, feel free to contact us again.

But maybe this could help you?: https://jira.atlassian.com/browse/FE-5683?error=login_required&error_description=Login+required&state=acea83bc-659a-4220-ab95-deb176059faf

**Comment by dark3rMatt3r** [comment]
Hi Everyone!

I have been debugging this issue with Fisheye Dev and I think this bug needs to be reopened as the issue can be replicated without using Fisheye at all.

The folks over at TMate also looked into this and their conclusion so far is that this needs to be addressed on the scm-manager side. Here is the relevant thread: https://support.tmatesoft.com/t/svnkit-does-not-properly-urlencode-urls-in-outbound-http-requests-svnkit-jetty/2426/19

**Comment by pfeuffer** [comment]
Thanks for the updates. We will take a look at this.

**Comment by pfeuffer** [comment]
Should be closed with #2013
