### ISSUE TITLE
LDAP setting

### ISSUE THREAD

**Issue by SaboShao** [scm-manager/scm-manager#1198]
How can I set a windows LDAP? is there one doc or blog?

**Comment by sdorra** [comment]
Hi, could you describe in more detail what are you trying to achieve? Are you trying to setup an ldap server on windows or do you try to connect with scm-manager to a ldap server (perhaps windows ad)?

**Comment by SaboShao** [comment]
Thanks sdorra, I have  connected successfully, but the Group did not synchronize (windows ad)

**Comment by sdorra** [comment]
The ldap-plugin does not synchronise groups at all.

> Users who log on to SCM-Manager via an external authentication mechanism (such as Ldap), can receive additional groups from the external system. External groups can be used without manual creation in SCM-Manager. However, adding the groups marked as "external" has the advantages that the groups created are taken into account in the auto-completion and authorizations can be assigned directly to an external group. Which external groups are assigned to a user can be read out on the profile page of a registered user.

You can see which groups are attached to your user by click on the profile link at the bottom of SCM-Manager. On this page you can see every group which is assigned to your user, regardless of internal or external.
