### ISSUE TITLE
Mirroring a Git LFS Repo - lfs files not found

### ISSUE THREAD

**Issue by amaidment** [scm-manager/scm-manager#1214]
I'm trying to use SCM-Manager to host git repos within an organisation, but which are a mirror clone of repos in the cloud.
I confess, I had trouble with the import repository functionality in SCM-Manager, so what I did was to create a repository, then via the command line delete all the directories / files in `~/.scm/repositories/git/[repo]`, and then do a `git clone --mirror [URL] [repo]`. This works fine for git repositories _without_ using `git-lfs` - internally, we work from SCM-Manager, and I can push changes from the mirror clone to the cloud remote, and update for any changes in the cloud.

However, when I have tried to do this on git repos that use `git-lfs`, it doesn't work. 

Initially, I was just doing `git clone --mirror [URL] [repo]` followed by `git lfs fetch --all`, which fetched the LFS objects to `~/.scm/repositories/git/[repo]/lfs/...` - which I checked by doing `du -skh lfs/` and finding that it's about the right size for the LFS objects in our repo. However, when I then do a clone from the repo in SCM-Manager, and then do `git lfs pull`, I get an error for each file tracked by LFS, that:

> [OID] Object 'OID' not found: [404] Object 'OID' not found
> ...
> error failed to fetch some objects from '[SCM-URL]/scm/git/[repo].git/info/lfs

So, I understand the 404 error is that the files are not available on the server. Well, they are on the server, but obviously not in the right place for SCM-Manager to serve them up. I was a bit perplexed by the last message, given that the lfs files are not in the info/ dir, but it did lead me to work out where SCM-Manager seems to want to store its LFS objects, which is under seems to be in `~/.scm/var/blob/[scm-repo-id]-git-lfs/`. Indeed, when I created a new repo (in SCM-Manager), did a clone, then added/tracked some LFS files, that was where they all appeared.

As such, I tried again, except that after doing the initial `git clone --mirror [URL] [repo]`, I set `git config --local lfs.storage ~/.scm/var/blob/[scm-repo-id]-git-lfs/`, so that the LFS files will be stored where (I thought) SCM-Manager would be expecting them. After calling `git lfs fetch --all` in that repo dir, all the LFS files appear to be in the `.../[scm-repo-id]-git-lfs/` dir, as confirmed by `du -skh [scm-repo-id]-git-lfs/`. However, when I then try to clone from the SCM-Manager repo, when I call `git lfs pull`, I get the same errors as before:

> [OID] Object 'OID' not found: [404] Object 'OID' not found
> ...
> error failed to fetch some objects from '[SCM-URL]/scm/git/[repo].git/info/lfs

Predominantly, I have been trying to do this with SCM-Manager 1.60, although I have also tried this with SCM-Manager 2.1.0 (repo directories are a little different, but manageable), and cannot get it to work in either case. 

I'm not sure if there's some configuration that I'm missing, or even if there's a better way of doing what I'm trying to do here.

**Comment by amaidment** [comment]
After a bit of further investigation, it looks like the issue could be due to how SCM-Manager is organising the LFS objects / files.

SCM-Manager is saving its LFS files to / reading LFS files from `~/.scm/var/blob/[repo-id]-git-lfs/objects/[OID]`

However, I don't think this is in keeping with the git-lfs [specification](https://github.com/git-lfs/git-lfs/blob/master/docs/spec.md), which states that:

```
These filters ensure that large files aren't written into the repository proper, instead being stored locally 
at .git/lfs/objects/{OID-PATH} (where {OID-PATH} is a sharded filepath of the form OID[0:2]/OID[2:4]/OID), 
synchronized with the Git LFS server as necessary. Here is a sample path to a file:

> .git/lfs/objects/4d/7a/4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393
```

As such, even sticking with the sperate storage in `~/.scm/var/blob`, SCM-Manager _should_ be saving/reading LFS from paths such as `~/.scm/var/blob/[repo-id]-git-lfs/objects/OID[0:2]/OID[2:4]/[OID]`

**Comment by pfeuffer** [comment]
Hi,

Fiddling with the repository directory inside the SCM-Manager is not a good idea in general. SCM-Manager tries to cache data that cannot be invalidated, when the repository is changed manually and we cannot guarantee for anything.

Taking LFS into this does not make things easyer. Maybe it would be wiser, using a third repository in the middle to handle the transfers? This also could be a place to resolve possible conflicts.

You have a point regarding our lfs storage, though. Although I do not think that this should be changed to follow the specification (this seems to be for local storage, only), it may be more suitable when storing a big amount of files.

Regards

René

**Comment by amaidment** [comment]
Thanks for coming back on this - yes, using a third mirror repository between the cloud and internal repos does make sense, especially, as you say, to resolve possible merge conflicts.
