### ISSUE TITLE
Check for ports

### ISSUE THREAD

**Issue by olaf7** [scm-manager/scm-manager#1224]
The Debian package installer does not check for the availability of the desired port. So for instance if a separate Jetty is already running, running the service after installation fails.

Same is true for the SSH plugin. Worse here is that it cannot be easily reconfigured to use a different port.

**Comment by sdorra** [comment]
The Port of the SSH plugin is configurable via the UI. Please have a look at the [docs](https://scm-manager.org/plugins/scm-ssh-plugin/docs/2.0.x/en/configuration/).

**Comment by olaf7** [comment]
My bad. Please add to the docs that the default port it uses is port 2222. (I had this already in use)

**Comment by eheimbuch** [comment]
The default SSH server port was added to the SSH Plugin documentation.
