### ISSUE TITLE
Broken links in Markdown

### ISSUE THREAD

**Issue by mcclure** [scm-manager/scm-manager#1225]
On the github page https://github.com/scm-manager/scm-manager

The links
"You can find the complete documentation in the docs/ directory."
"Full documentation lives in the SCM-Manager repository"
are broken links. It appears you added en/ and de/ subfolders to your docs but didn't update your links to reflect this.

Maybe other links, elsewhere, are also broken as a result.

**Comment by pfeuffer** [comment]
Thank you very much for this finding. We will fix this immediately.
