### ISSUE TITLE
apt update error - repository/apt-v2-releases stable InRelease' doesn't support architecture 'amd64'

### ISSUE THREAD

**Issue by ionelanton** [scm-manager/scm-manager#1228]
## Issue description

Can't install scm-manager on Ubuntu 20.04 (Proxmox container)

### Bug Report

Running "apt update" gives:

`Skipping acquire of configured file 'main/binary-amd64/Packages' as repository 'https://packages.scm-manager.org/repository/apt-v2-releases stable InRelease' doesn't support architecture 'amd64'`

#### Describe how to reproduce the bug

Running installation:

```
echo 'deb https://packages.scm-manager.org/repository/apt-v2-releases/ stable main' | sudo tee /etc/apt/sources.list.d/scm-manager.list
sudo apt-key adv --recv-keys --keyserver hkps://keys.openpgp.org 0x975922F193B07D6E

sudo apt-get update (gives the error)
``` 

#### Describe your SCM-Manager setup

Clean installation

#### Which operating system, browser and versions do you use?

Ubuntu 20.04

**Comment by ionelanton** [comment]
Fixed with [arch=all] in 

echo 'deb **[arch=all]** https://packages.scm-manager.org/repository/apt-v2-releases/ stable main' | sudo tee /etc/apt/sources.list.d/scm-manager.list

**Comment by sdorra** [comment]
@ionelanton Thank you for the report.
