### ISSUE TITLE
c:\var\cache folder and An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by nanek-hg** [scm-manager/scm-manager#1236]
## Issue description

On Windows, scm manager creates a var directory in C: \

I use the default configuration with a specified home directory
  <env name="SCM_HOME" value="c:\scm-server-home" />

#### Log of the bug

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/var/cache/scm/work/webapp/webapp/WEB-INF/lib/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by sdorra** [comment]
The `illegal reflective access operation` is a warning from google guice [google/guice#1133](https://github.com/google/guice/issues/1133) and is currently not fixable, but the warning is not a problem. The cache directory at `c:\var` is a problem and we will fix it.
