### ISSUE TITLE
SCM behind apache reverse  with SSL 

### ISSUE THREAD

**Issue by mamut999** [scm-manager/scm-manager#1253]
If scm is behind apache reseverse and apache is running SSL server
correct apache config

                RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
                RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}

                ProxyPass               /scm    http://localhost:8080/scm
                ProxyPassReverse        /scm http://localhost:8080/scm

Just documentation update is needed

**Comment by pfeuffer** [comment]
You also have to set

```
AllowEncodedSlashes NoDecode
```

Additionally the `nocanon` directive has to be set, in your example:

```
ProxyPass               /scm    http://localhost:8080/scm       nocanon
ProxyPassReverse        /scm http://localhost:8080/scm
```
