### ISSUE TITLE
Can not access a repository with a extension name

### ISSUE THREAD

**Issue by spritetong** [scm-manager/scm-manager#1266]
I create a Git repository named "test.git" successfully, but I can clone it.

Command line:
   git clone "https://localhost/scm/repo/my-repo/test.git"

Error message:
    fatal: repository 'https://localhost/scm/repo/my-repo/test.git/' not found

Environment:
     SCM manager V2.3.0,  Windows 10 / CentOS 8.

**Comment by eheimbuch** [comment]
Hey spritetong,

you are right, there seems to be an error if an git repository is named with `.git` extension. We will have a look.
