### ISSUE TITLE
  The file name added to the repository cannot contain Chinese.

### ISSUE THREAD

**Issue by 1191149398** [scm-manager/scm-manager#1268]
The file name added to the repository cannot contain Chinese. Error when file name contains Chinese.

**Comment by sdorra** [comment]
Could you please provide more information? Which SCM-Manager version do you use? Which type of repository (Git, Mercurial or Subversion)?

**Comment by 1191149398** [comment]
SCM-Manager 2.3.0
Mercurial 
For example, There is a file named “你好.txt” in the repository

**Comment by sdorra** [comment]
Which encoding do you use on your client?

**Comment by 1191149398** [comment]
I use the client TortoiseHg version 5.0.2，Unable to modify encoding。
The encoding should be GB2312.  
The gb312 code corresponding to "新建文本文档" is d0 C2 BD A8 CE C4 B1 be CE C4 B5 B5
![图片](https://user-images.githubusercontent.com/7444753/88884066-5c963100-d268-11ea-9e66-14554a050d70.png)
![图片](https://user-images.githubusercontent.com/7444753/88884095-6ae44d00-d268-11ea-9d53-f55d2ea90152.png)

**Comment by 1191149398** [comment]
The default encoding for the Chinese version of windows is GB2312

**Comment by 1191149398** [comment]
The default encoding for the Chinese version of windows is gbk

**Comment by sdorra** [comment]
Could you try to set the mercurial encoding at (`/scm/admin/settings/hg`) to match your local encoding?

**Comment by 1191149398** [comment]
I not found (/scm/admin/settings/hg).
 Where should it be ？

**Comment by 1191149398** [comment]
After setting the mercurial encoding to GBK, it works

**Comment by sdorra** [comment]
You have to login with an administrator account. Click on Administration in the top navigation, click on settings in the right navigation, click on mercurial also in the right menu. Then you should see the mercurial settings, with the encoding field, which should contain UTF-8 as default value.

**Comment by 1191149398** [comment]
thank you
