### ISSUE TITLE
SSL cookie without secure flag

### ISSUE THREAD

**Issue by yashcho** [scm-manager/scm-manager#1281]
Hello Team,

Summary:
When we done some security pen-testing of open-source scm version 1.60 installed on our project application, we got the SSL cookie without secure flag included in scm URL endpoint(/scm/), If the secure flag is not set, then the cookie will be transmitted in clear-text if the user visits
any HTTP URLs within the cookie's scope. An attacker may be able to induce this event by feeding a user suitable links, either directly or via another web site. Even if the domain that issued the cookie does not host any content that is accessed over HTTP, an attacker may be able to use links of the form http://example.com:443/ to perform the same attack.

As you can see in this screenshot:
![image](https://user-images.githubusercontent.com/69308923/89649378-47f80f80-d8de-11ea-91df-0211653809de.png)

I believe this is a medium level severity bug but if you can provide us some fix on it would appreciate it?

**Comment by pfeuffer** [comment]
This looks like we would need a configuration option for this, because we cannot assume that all SCM-Manager instances are accessed via https... Thanks for the hint, we definitely will have a look at it.

**Comment by sdorra** [comment]
I think we could set the flag, if the request scheme (or forwarded scheme) of the authentication request was https.

**Comment by yashcho** [comment]
Your welcome, so can we except this enhancement in next release, if yes then we can agree to close this issue. :)

**Comment by sdorra** [comment]
We already set the secure flag if the request is an https request:

* [Set secure flag](https://github.com/scm-manager/scm-manager/blob/develop/scm-webapp/src/main/java/sonia/scm/security/DefaultAccessTokenCookieIssuer.java#L80)
* [Check if request is secure](https://github.com/scm-manager/scm-manager/blob/develop/scm-webapp/src/main/java/sonia/scm/security/DefaultAccessTokenCookieIssuer.java#L119)

Do you use an reverse proxy which does the ssl termination for scm-manager?

**Comment by yashcho** [comment]
Yes, we are using reverse proxy but that lead to ssl termination can't say without confirming, so let me confirm on this and if so this causes the issue then we are willing to close the ticket.

**Comment by yashcho** [comment]
Hello @sdorra ,
We got this issue again and found two header's which we apply to the URL at SSL Interception are mentioned below.

X-Forwarded-Proto=https
X_FORWARDED_PROTO=https 

So can you let us know by which header's you are considering the request is secured or not?

**Comment by pfeuffer** [comment]
Hi @yashcho ,
when I'm not mistaken we use the first form X-Forwarded-Proto (see here)
Regards
René
