### ISSUE TITLE
GIT branches with '+' not supported by UI

### ISSUE THREAD

**Issue by terexas** [scm-manager/scm-manager#1302]
## Issue description

SCM-Manager Web fails to browse git repository branches with '/' character in the branch name.
For GIT these are valid names (release/1.1, hotfix/etc) very well used by GitFlow workflow.

#### Describe how to reproduce the bug

Test case 1:
1. Go to any GIT repository
2. Create branch with '/'. For example 'test/branch'
3. UI fails with error: An internal URL could not be found (Error Code 92RCCCMHO1). Yet branch is created.

Test case 2:
1. Create and push the branch with '/' in existing git repository or get from test case 1.
2. Go to pushed GIT repository in SCM-Manager Web.
3. List the branches (click on Branches)
3. Select one with '/' in name. For example 'test/branch'
5. UI fails with same error: An internal URL could not be found (Error Code 92RCCCMHO1)

Test case 3:
1 & 2. Same as test case 2.
3. Goto </> Code
4. Select the branch with '/' in the name.
5a. Sources fails with error: Not found (Error Code AGR7UzkhA1)
5b. Commits fails with same error as test case 1 & 2: An internal URL could not be found (Error Code 92RCCCMHO1)

#### Describe your SCM-Manager setup

[version]
Version: 2.4.0
Stage: PRODUCTION
ConfigurationStoreFactory: class sonia.scm.store.JAXBConfigurationStoreFactory
ConfigurationEntryStoreFactory: class sonia.scm.store.JAXBConfigurationEntryStoreFactory
DataStoreFactory: class sonia.scm.store.JAXBDataStoreFactory

[system]
Operating System: Linux
Architecture: 64
Java: Oracle Corporation/1.8.0_262
Container: SCM_SERVER
Locale: en_US
TimeZone: Europe/Vilnius

[runtime]
Available processors (cores): 1
Free memory: 57 MB
Maximum memory: 239.8 MB
Total memory available to JVM: 239.8 MB

[handlers]
git: scm-git-plugin/2.4.0 org.eclipse.jgit/5.6.1.202002131546-r-scm1
svn: scm-svn-plugin/2.4.0 svnkit/1.10.1-scm2
hg: scm-hg-version/2.4.0 python/2.7.5 mercurial/5.5

Plugins:
scm-ldap-plugin:2.0.0
scm-authormapping-plugin:2.0.0
scm-legacy-plugin:2.4.0
scm-landingpage-plugin:1.2.0
scm-script-plugin:2.1.2
scm-svn-plugin:2.4.0
scm-issuetracker-plugin:2.0.1
scm-webhook-plugin:2.1.1
scm-git-plugin:2.4.0
scm-hg-plugin:2.4.0
scm-statistic-plugin:2.0.0
scm-redmine-plugin:2.0.0
scm-activity-plugin:2.0.0
scm-support-plugin:2.0.0
scm-pushlog-plugin:2.1.1
scm-ci-plugin:2.1.0
scm-el-plugin:1.0.0
scm-jenkins-plugin:2.1.0

#### Which operating system, browser and versions do you use?

Fedora 32
Mozilla Firefox 79.0 (64bit)
Chromium Version 84.0.4147.89 (Developer Build) Fedora Project (64-bit)

#### Log of the bug

Related log entries when trying to browse code:
2020-08-25 22:31:25.918 [qtp1604839423-416] [2IS8hrtPT6N] ERROR sonia.scm.repository.spi.GitBrowseCommand - could not find revision test

#### Further information like screenshots

![image](https://user-images.githubusercontent.com/1862391/91219356-2cd13080-e723-11ea-89f7-185537f0c4ab.png)

![image](https://user-images.githubusercontent.com/1862391/91219514-699d2780-e723-11ea-9d7b-d0f63e6fd6f2.png)

**Comment by pfeuffer** [comment]
Thanks for the detailed description, @terexas. Important question: Do you use a reverse proxy? The slashes of branches have to be escaped in the URL and you have to configure proxies correctly that these are not converted to real slashes again. If so, please have a look at our page regarding reverse proxies here: https://scm-manager.org/docs/2.4.x/en/administration/reverse-proxies/

**Comment by terexas** [comment]
Thanks for it! Indeed nginx reverse proxy was guilty for this. To mention details - the trailing slash in the proxy_pass was responsible for URI normalization. The simple change from `proxy_pass http://scm:8080/;` to `proxy_pass http://scm:8080;` has made my day.

**Comment by terexas** [comment]
Actually I'll be picky again..
After reverse proxy changes '/' works well, yet '+' in the branch name prevents to browse sources within the repository's branch. Not a usual case, but sadly we have such..

Direct access (no reverse proxies this time)
Branch name: test/b+ranch
Internal Server Error (Error Code CmR8GCJb31)

Exception:
WARN  sonia.scm.api.FallbackExceptionMapper - mapping unexpected org.eclipse.jgit.errors.RevisionSyntaxException to status code 500
org.eclipse.jgit.errors.RevisionSyntaxException: Invalid ref name: test/b ranch
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:831)
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:502)
	at sonia.scm.repository.GitUtil.getRevisionId(GitUtil.java:572)
	at sonia.scm.repository.spi.GitBrowseCommand.computeRevIdToBrowse(GitBrowseCommand.java:148)
	at sonia.scm.repository.spi.GitBrowseCommand.getBrowserResult(GitBrowseCommand.java:133)
	at sonia.scm.repository.api.BrowseCommandBuilder.getBrowserResult(BrowseCommandBuilder.java:154)
	at sonia.scm.api.v2.resources.SourceRootResource.getSource(SourceRootResource.java:93)
	at sonia.scm.api.v2.resources.SourceRootResource.getAll(SourceRootResource.java:73)
        ...

**Comment by pfeuffer** [comment]
Tries a `+` in three environments (local dev, k8s installation and behind an apache reverse proxy. All three were working. Can you please check for your nginx config once again? The '+' has to be escaped as `%2B` in the URL.
![Peek 2020-08-26 08-53](https://user-images.githubusercontent.com/281097/91271195-1609f880-e77a-11ea-8e1a-556b5c764c39.gif)

**Comment by terexas** [comment]
No reverse proxy this time. 
Creating/Listing commits - works. 
Browse sources - does not.

**Comment by pfeuffer** [comment]
Ah, got it. I can reproduce this. We will have a look at it. Thanks for the report!
