### ISSUE TITLE
Fehler: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by BasDL91** [scm-manager/scm-manager#1365]
OS: Unraid 6.8.3
Installed SCM-Manager 2.6.2 as Docker

Used Webbrowser: Microsoft Edge Version 86.0.622.38
When opening the changeset of a svn Repository the following error appears:

![image](https://user-images.githubusercontent.com/51874985/95728773-31728980-0c7c-11eb-9dab-3276de2b6424.png)

When opening with Firefox Version 81.0.1 appears this error:

![image](https://user-images.githubusercontent.com/51874985/95731790-39342d00-0c80-11eb-875f-e29d38258ceb.png)

SCM log contains no errors.

**Comment by pfeuffer** [comment]
Can you tell us some more details? Is this the first time you get this error, was it working before? If so, did you do something that may be of relevance? Or have you migrated from 1.60?

**Comment by BasDL91** [comment]
Its the fist time i have seen the error appear since i have updated from 2.6.0 to 2.6.1.
Some changesets of the same day of this Repo display normal and some show this error.

I initially made a clean install with 2.3.0.

**Comment by eheimbuch** [comment]
Hey @BasDL91,

could you provide further information like a patch of your changeset or the Json content which get fetched by your browser. We couldn't reproduce this error yet.

We suspect there might be an error processing your Json response content of the changeset.

Thanks in advance.

**Comment by BasDL91** [comment]
Hey @eheimbuch,

i also checked new changesets since 2.6.2 and there doesn't happen the error anymore.

the JSON:
> {
  "id": "9",
  "author": {
    "mail": null,
    "name": "mustmax"
  },
  "date": "2020-10-13T05:41:27.809Z",
  "description": "Türantrieb 5A Module CAN Timeout auch für die Nachricht vom Gateway",
  "contributors": [
    {
      "type": "Pushed-by",
      "person": {
        "mail": "max.mustermann@mail.de",
        "name": "Max Mustermann"
      }
    }
  ],
  "signatures": [],
  "_links": {
    "self": {
      "href": "http://192.168.0.10:8080/scm/api/v2/repositories/svn/MRS_Motorsteuerung_5A_1_037_300/changesets/9"
    },
    "diff": {
      "href": "http://192.168.0.10:8080/scm/api/v2/repositories/svn/MRS_Motorsteuerung_5A_1_037_300/diff/9"
    },
    "sources": {
      "href": "http://192.168.0.10:8080/scm/api/v2/repositories/svn/MRS_Motorsteuerung_5A_1_037_300/sources/9"
    },
    "modifications": {
      "href": "http://192.168.0.10:8080/scm/api/v2/repositories/svn/MRS_Motorsteuerung_5A_1_037_300/modifications/9"
    }
  },
  "_embedded": {
    "parents": [
      {
        "id": "8",
        "_links": {
          "self": {
            "href": "http://192.168.0.10:8080/scm/api/v2/repositories/svn/MRS_Motorsteuerung_5A_1_037_300/changesets/8"
          },
          "diff": {
            "href": "http://192.168.0.10:8080/scm/api/v2/repositories/svn/MRS_Motorsteuerung_5A_1_037_300/diff/8"
          }
        }
      }
    ]
  }
}

**Comment by BasDL91** [comment]
I examined the error further with the browser-dev tools and saved the log with the error.
This might be helpful for you.

edge:
[edge-console-log-1602749234978.log](https://github.com/scm-manager/scm-manager/files/5383448/edge-console-log-1602749234978.log)

firefox:
[firefox-console-export-2020-10-15_10-34-39.txt](https://github.com/scm-manager/scm-manager/files/5383466/firefox-console-export-2020-10-15_10-34-39.txt)

**Comment by BasDL91** [comment]
I forgot to tell that we use TortoiseSVN as PC Client.

Did you mean this svn props:
![Unbenannt](https://user-images.githubusercontent.com/51874985/96143696-a0addf00-0f03-11eb-8a70-07a6c869fbeb.PNG)
These are from the changeset with the error.

**Comment by BasDL91** [comment]
Hey @eheimbuch,

i checked with 2.9.0 but the error still appears on new an old changesets.

**Comment by eheimbuch** [comment]
Hey @BasDL91,

i could not reproduce your error on my machine yet.

Could you create a new dummy repository which you can share with us and reproduce this error there? It's way more likely we will find the error and could fix it till to the next minor release.

Thanks!

**Comment by arnoud-koolecontrols** [comment]
Hey @eheimbuch 
I am also having an issue related to this. 
I think it is a problem with modified binairy files. 

reproducing:
- create a svn repo in the scm manager
- do a checkout and add a .dll file
- do a commit
- change the dll file for another dll file with the same name
- do a commit
- view last commit in the changset and the error happends.

I have attached my test repo

[8HSGD5kwK4.zip](https://github.com/scm-manager/scm-manager/files/5535839/8HSGD5kwK4.zip)

**Comment by eheimbuch** [comment]
Hey @arnoud-koolecontrols 

Thanks a lot. I could reproduce it like you said. I will try to fix this issue till our next release.
