### ISSUE TITLE
LDAP groups missing in the UI

### ISSUE THREAD

**Issue by schneidr** [scm-manager/scm-manager#1391]
## Issue description

LDAP groups are not showing in the UI.

#### Describe how to reproduce the bug

Configure LDAP. LDAP groups don't show up in the UI, neither under "Groups" nor when I want to set a permission for a repository, only groups created in SCM-Manager itself are available.

Running `Test Connection` in the settings of the LDAP plugin shows all groups of the tested user just fine.

#### Describe your SCM-Manager setup

- docker image scm-manager/scm-manager:2.7.1
- Apache 2.4.41 as a reverse proxy
- LDAP plugin 2.0.1

#### Which operating system, browser and versions do you use?

Windows 10 with Chrome 86, Firefox 82

#### Log of the bug

No LDAP related messages show up in the logs.

#### Further information like screenshots

ldap.xml:

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <ldap-config>
        <attribute-name-fullname>cn</attribute-name-fullname>
        <attribute-name-group>memberOf</attribute-name-group>
        <attribute-name-id>sAMAccountName</attribute-name-id>
        <attribute-name-mail>mail</attribute-name-mail>
        <base-dn>dc=ad,dc=example,dc=com</base-dn>
        <connection-dn>scmmanager@example.com</connection-dn>
        <connection-password>{enc}v2:_REDACTED_=</connection-password>
        <host-url>ldap://dcproxy.example.com:389</host-url>
        <profile>AD</profile>
        <referral-strategy>FOLLOW</referral-strategy>
        <search-filter>(&amp;(objectClass=Person)(sAMAccountName={0}))</search-filter>
        <search-filter-group>(&amp;(objectClass=group)(member={0}))</search-filter-group>
        <search-scope>sub</search-scope>
        <unit-groups></unit-groups>
        <unit-people></unit-people>
        <enabled>true</enabled>
        <enable-starttls>false</enable-starttls>
        <enable-nested-ad-groups>true</enable-nested-ad-groups>
    </ldap-config>

**Comment by eheimbuch** [comment]
Hey Schneidr,

this is right. External groups will not be created automatically in SCM-Manager. Nonetheless your external users keep their external groups. You can find them if you have a look at the user profile.

If you want to manage user permissions by an external group, you have to create a new group in SCM-Manager marked as external manually.

**Comment by schneidr** [comment]
Seriusly? I'm expecting the same behavior as in SCM-Manager 1.x. If the users can't just use the AD groups as before I the 2.x version is useless to me.

**Comment by pfeuffer** [comment]
As in SCM-Manager 1.x you can add permissions for arbitrary group names for repositories or namespaces. Just select "Group Permission", enter the name of the group and select '_Create "your_group_name"_' in the drop down.

![Arbitrary Group Name](https://user-images.githubusercontent.com/281097/97305452-6591a100-185d-11eb-93d0-f12bfe3e60cd.gif)
