### ISSUE TITLE
Find handling of Java versions prior Java 8u162

### ISSUE THREAD

**Issue by sdorra** [scm-manager/scm-manager#1394]
## Issue description

We should find a handling of Java versions prior to Java 8u162, because these version require the Cryptography Extension (JCE) in order to create our GPG private keys. At least we should update our install instructions and perhaps we could create a check on application start.

https://groups.google.com/g/scmmanager/c/pne6pApwids

**Comment by eheimbuch** [comment]
Close this since we already atleast Java 11 for SCM-Manager.
