### ISSUE TITLE
Error Code CmR8GCJb31

### ISSUE THREAD

**Issue by bbarzeM** [scm-manager/scm-manager#1401]
## Issue description

_Hi, I think that I found a bug._ 

Some times ago I write a C# solution (CamerApp) made of three project (CamerApp, CamerAppServer, Utility).
Yestarday I created a repository (CameraApp) througt web interfce; after that i push my solution into this repository.
Everithing goes fine.
If I make a pull from another PC I have my solution without error.
The problem is visible in the Web Interface, I can't see nothing inside CamerApp folder.
![image](https://user-images.githubusercontent.com/73690306/97678445-171a1780-1a94-11eb-93e3-8cc9105ed95e.png)
There is not this problem with the other projects.

#### Describe your SCM-Manager setup

I use SCM-Manager 2.8.0
The plugin that I use is Mercurial 2.8.0
In this moment the server is hosted on my PC

#### Which operating system, browser and versions do you use?

I use Windows 10 and Chrome v. 86

#### Log of the bug

I attach logs scm-manager logs
[scm-manager.log](https://github.com/scm-manager/scm-manager/files/5463992/scm-manager.log)
[scm-server.err.log](https://github.com/scm-manager/scm-manager/files/5463993/scm-server.err.log)
[scm-server.wrapper.log](https://github.com/scm-manager/scm-manager/files/5463996/scm-server.wrapper.log)

_Thank you_

**Comment by sdorra** [comment]
Hi, are you using sub repositories? Did your repository contain the file or a folder `CamerApp/.sln`?

**Comment by bbarzeM** [comment]
Hi,

i think i'm not using sub repositories (I don't kown them)

In tortoise hg i have this situation:
![image](https://user-images.githubusercontent.com/73690306/97705021-a7b42000-1ab3-11eb-98de-ffbc0be422c8.png)

The situation in Visual Studio is like this:
![image](https://user-images.githubusercontent.com/73690306/97705303-2610c200-1ab4-11eb-8c65-9826e4ff2ef4.png)

I have only one .sln file and it is inside the solution folder
![image](https://user-images.githubusercontent.com/73690306/97705365-3fb20980-1ab4-11eb-907e-36ba5b6a01ac.png)

Thank you

**Comment by sdorra** [comment]
The CamerApp folder does not contain a `.sln` file? It looks like the repository has an invalid entry in its manifest. Is this by chance an OpenSource application, so we can get a copy of the repository?

**Comment by bbarzeM** [comment]
This is the solution folder

![image](https://user-images.githubusercontent.com/73690306/97717017-99223480-1ac4-11eb-8df2-e766cb1db5fa.png)

Nope, inside the inner folder there is not another .sln file

![image](https://user-images.githubusercontent.com/73690306/97716919-7db72980-1ac4-11eb-8153-afb05a1b1bb1.png)

Sorry but I can't share this project

Is possible that the problem is becouse of the inner folder has the same name of the outsider folder?

**Comment by bbarzeM** [comment]
I found the cause :D 

On ScmManager I had a repository that have inside a subfolder with the same name of the repository 🌵 


I changed the c# project name and it's folder name... Now it's working! 👍

![image](https://user-images.githubusercontent.com/73690306/97719472-66c60680-1ac7-11eb-8f0a-e1d19b50151e.png)

**Comment by avsdev-cw** [comment]
I'm not sure why this is closed... It legitimately is a bug if SCM-Manager can't handle a repository that has a sub-folder with the same name as the repository.

It would also appear that this is STILL an issue as this is exactly what I am experiencing.

In my case I cannot simply "change the repository name and subfolder name" as these are legacy repositories that are mostly archived at this point. (We are still having to regularly access them for one reason or another)

**Comment by pfeuffer** [comment]
I took a look at this, and I cannot find a simple way to reproduce this bug you've experienced. Adding a folder in a subdirectory called the same as the project did not lead to any issues.

Can you create a simple repository, where you can reproduce this bug and give us this repository? (And of course: Does this still happen with the lates version of SCM-Manager?)

Thank you!

**Comment by avsdev-cw** [comment]
> And of course: Does this still happen with the lates version of SCM-Manager?

Yes it does. As for the rest of your query, I'll take a look and see if I can do so asap. I wonder if this is related specifically to c# projects (and their .sln files)?
