### ISSUE TITLE
Docker HEALTHCHECK instruction

### ISSUE THREAD

**Issue by rabesocke** [scm-manager/scm-manager#1428]
#### Problem to be solved

A nice feature of the Docker / Kubernetes version of SCM Manager would be a Docker HEALTHCHECK in order to use this e.g. with https://hub.docker.com/r/willfarrell/autoheal/

#### Proposed solution

Add a health endpoint to SCM Manager and add a HEALTHCHECK instruction to the Dockerfile (https://docs.docker.com/engine/reference/builder/#healthcheck)

**Comment by eheimbuch** [comment]
Hey @rabesocke,

currently our implicit healthcheck is to check if the SCM-Manager REST API is available. But you are right we could provide an explicit endpoint for the healthcheck. We will discuss this matter in our team.

**Comment by rabesocke** [comment]
My feature request is about the Docker image. At the moment there is no HEALTHCHECK implemented, so docker has no health state of the container. If you add a HEALTHCHECK instruction to the Dockerfile, Docker (and also Kubernetes I think) can check the state of the container and restart it automatically.

An example in the Dockerfile:
```
HEALTHCHECK --interval=1m CMD curl -f http://localhost/api/health || exit 1
```

If this instruction is available in the base image, everyone can override it for their container. But if there is no HEALTHCHECK instruction in the base image, you have to create an own image in order to use this feature.
