### ISSUE TITLE
Ubuntu 20.04 AttributeError: module 'mercurial.cext' has no attribute 'parsers'

### ISSUE THREAD

**Issue by MWalz149** [scm-manager/scm-manager#1448]
## Issue description

First of all: Great Software. Thank you very much for this platform.
Now the bug: I installed scmmanager on a clean, fresh and up-to-date ubuntu 20.04 x64 server using the instructions from here:
https://scm-manager.org/docs/2.10.x/en/installation/debian/
After a reboot, the UI was up and running. I was able to create users and repositories. I tested git and it works perfectly.
However there is a strange error when using mercurial:

### Bug Report

When I try  to clone or push from a remote machine I get this error: (also with -v or --debug)

```
hg push -v
pushing to http://x.y.z:8080/scm/repo/scmadmin/hg-test
keyring: username not specified in hgrc (or in url). Password will not be saved.
http authorization required
realm: SONIA :: SCM Manager
url: http://10.0.0.49:8080/scm/repo/scmadmin/hg-test
user: de-test
password: 
abort: remote error:
Mercurial/Python process ends with return code 1
```

In the /var/log/scm/scm-manager.log I get this error:

```
2020-11-25 20:58:37.252 [cgi-pool-4] [          ] WARN  sonia.scm.web.cgi.DefaultCGIExecutor - Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mercurial/policy.py", line 69, in _importfrom
    fakelocals[modname] = mod = getattr(pkg, modname)
  File "/usr/lib/python2.7/dist-packages/mercurial/pycompat.py", line 299, in w
    return f(object, sysstr(name), *args)
AttributeError: module 'mercurial.cext' has no attribute 'parsers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/scm/lib/python/hgweb.py", line 27, in <module>
    from mercurial import demandimport, ui as uimod, hg
  File "/usr/lib/python2.7/dist-packages/mercurial/ui.py", line 23, in <module>
    from .i18n import _
  File "/usr/lib/python2.7/dist-packages/mercurial/i18n.py", line 17, in <module>
    from . import (
  File "/usr/lib/python2.7/dist-packages/mercurial/encoding.py", line 40, in <module>
    charencode = policy.importmod('charencode')
  File "/usr/lib/python2.7/dist-packages/mercurial/policy.py", line 116, in importmod
    mod = _importfrom(pn, mn)
  File "/usr/lib/python2.7/dist-packages/mercurial/policy.py", line 71, in _importfrom
    raise ImportError('cannot import name %s' % modname)
ImportError: cannot import name parsers


```
This error is permanent and I can reproduce it also after reboot. 

#### Describe your SCM-Manager setup

A fresh install of 2.10.1 on ubuntu server x64 20.10, no additional plugins installed.

#### Which operating system, browser and versions do you use?

Ubuntu 20.04. mercurial on the remote machine ist 4.5.3

**Comment by pfeuffer** [comment]
Thanks for the feedback, @MWalz149 ! Indeed we have an issue with mercurial on Ubuntu 20.10 and we haven't figured out whether it is due to the mercurial version, python or whatever, but we will have a look at this in the next days.

I'm not sure whether you are running 20.04 or 20.10 on your server because you mention both. Would it be a possibility for you to use 20.04 (you said it was a fresh install) or the docker image till we fix the problem?

**Comment by MWalz149** [comment]
I am sorry, this was s typo. I am running 20.04 on the server. Might it help to downgrade some packages? But I can also use 18.04 or fedora, no Problem

**Comment by sdorra** [comment]
@MWalz149 could you post your mercurial settings (Administration -> Settings -> Mercurial)?

**Comment by MWalz149** [comment]
Sure:
HG Binary:
/usr/bin/hg

Python Binary:
/usr/bin/python3

Python Module Search Path 
/usr/lib/python2.7/dist-packages

Encoding
UTF-8

Optimized Bytecode (.pyo)
not checked

Show Revision
not checked

Disable SSL Validation on Hooks
not checked

 Enable HttpPostArgs Protocol
not checked

**Comment by sdorra** [comment]
Ok, there is an issue in the configuration. With this configuration scm-manager uses a python 3 with modules from python 2.7. Could you try to use `/usr/bin/python2` as python binary?

**Comment by MWalz149** [comment]
Hey, that did the trick!
Thanks a lot!
Is this a problem in the defaults or did I forget something during install?

**Comment by sdorra** [comment]
This looks like a problem with the defaults. We are currently working to reduce the complexity of the mercurial configuration, see #1458.
