### ISSUE TITLE
Templates .gitignore for new repositories

### ISSUE THREAD

**Issue by vanBassum** [scm-manager/scm-manager#1449]
Hello,

When you create a new repository on github, you get the possibility to select a default gitignore file. I would love to see a feature like this in SCM-Manager. For example: When you select the option "Initialize repository" a dropdown will show where you can select a certain ignore file. I can imagine a directory on the server containing these ignore files that will be copied to the repository upon initialisation.

Or if you want to go fancy, maybe instead of only ignore files, the option to create templates. Where you have a directory on the server with a number of template folders containing a folderstructure and files that will be used in the initialisation of repository. The advantage of this will be that this also works for the other version control systems. 

- /Server/Templates
   -  /Server/Templates/Template1/.gitignore
   -  /Server/Templates/Template1/Somefolder/Somefile.txt

I hope you get the idea, feel free to ask me any questions if something is unclear.

**Comment by eheimbuch** [comment]
Hey @vanBassum,

you are lucky today. Exactly the feature you describe we already support with this [plugin](https://www.scm-manager.org/plugins/scm-repository-template-plugin/). 

You can create your own custom template repositories and use them when creating a new repository. Like initializing a repository with license files, gitignore and so on. Check out the [documentation](https://www.scm-manager.org/plugins/scm-repository-template-plugin/docs/1.0.x/en/usage/) for further information.

**Comment by vanBassum** [comment]
Aah very nice. Ill try this out, consider this issue solved.
