### ISSUE TITLE
Can not commit subversion repos while have Chinese char in floder name or file name

### ISSUE THREAD

**Issue by lxh0508** [scm-manager/scm-manager#1468]
## Issue description

Can not commit subversion repos while have Chinese char in floder name or file name.

#### Describe how to reproduce the bug

have Chinese char in file / floder name

#### Describe your SCM-Manager setup

Docker

#### Which operating system, browser and versions do you use?

SCM-Manager:
OS: Synology DSM918+
Docker: 18.09.0-0513
Image:  scmmanager/scm-manager (https://registry.hub.docker.com/r/scmmanager/scm-manager/)
Version: 2.11

Client:
OS: Win10 LTSC
SVN: TortoiseSVN 1.14
Brower: Edge

#### Log of the bug

1. Will get error code 400 while use edge to download the file(Chinese char in file/floder name）
    Error: server returned status code 400
2. Will get error code 400 while commit by TortoiseSVN.
    Unexpected HTTP status 400 'Bad Request' on  '/scm/repo/Project/609-0109/trunk/%E8%AF%B4%E6%98%8E.md'

**Comment by sdorra** [comment]
This looks like the same problem as #1469. It should be fixed with the version 2.12.0 of SCM-Manager which should be available in the next days.
