### ISSUE TITLE
Realm Description change is not applied correctly 

### ISSUE THREAD

**Issue by niks-** [scm-manager/scm-manager#1487]
## Issue description
I've changed Realm Description in Global Configuration. However, changes are not shown in command line when accessing repos.

#### Describe how to reproduce the bug

1. Log in under scmadmin account
2. Go to Administration -> Settings -> General -> Global Configuration
3. Change value of "Realm Description" to new one. E.g. "My SCM Manager"
4. Save changes
5. Restart scm-server
6. Open Windows cmd and try to pull changes from repo

Original(old) Realm Description is shown in cmd.
![image](https://user-images.githubusercontent.com/8697655/103589214-9b08d980-4ef3-11eb-9453-5aa6b0e231ec.png)

On GUI of SCM-Manager new value is displayed
![image](https://user-images.githubusercontent.com/8697655/103589388-f0dd8180-4ef3-11eb-8a37-8e8a68a35115.png)

#### Describe your SCM-Manager setup

SCM-Manager version - 2.12.0
scm-hg-plugin@2.12.0
scm-mail-plugin@2.4.0
scm-notify-plugin@2.0.1
scm-ci-plugin@2.1.0
scm-jira-plugin@2.3.0
scm-notify-plugin@2.0.1
scm-pushlog-plugin@2.1.1
scm-cas-plugin@2.2.1
scm-legacy-plugin@2.12.0
scm-ci-plugin@2.1.0
scm-statistic-plugin@2.0.0
scm-git-plugin@2.11.1
scm-activity-plugin@2.0.0
scm-ldap-plugin@2.0.1
scm-svn-plugin@2.12.0
scm-jira-plugin@2.3.0
scm-issuetracker-plugin@2.0.1
scm-jira-plugin@2.3.0

No any proxies

#### Which operating system, browser and versions do you use?

OS - Windows Sever 2019 x64
scm-server service is running under Local System account
Scm-Manager Home directory - C:\SCM-Manager-Data
Windows Firewall is disabled
Chrome - v87.0.4280.88 (Official Build) (64-bit)
OpenJDK - v11

**Comment by eheimbuch** [comment]
Hey @niks-

I will have a look.

**Comment by eheimbuch** [comment]
You are right, this seems to be a bug. We will discuss this matter in our team and will try to fix this till the next release. Thanks for the report!
