### ISSUE TITLE
Update Helm chart to make deployment as statefulset

### ISSUE THREAD

**Issue by eirisdg** [scm-manager/scm-manager#1575]
## Issue description

Actually, the Helm chart uses a deployment object to deploy the SCM pod. In my consideration, SCM must be treated like a database, because the data must not be volatile. So the correct object should be statefulset.

### Feature Request

Change the kind of object from deployment to statefulset

**Comment by sdorra** [comment]
If I understand correctly, the difference between a deployment and a stateful set is that each pod from a stateful set gets its own volume and in a deployment all pods from that deployment share the same volume.

So stateful sets are especially interesting for services that replicate their data, like databases.

SCM Manager currently does not support scaling or replication, so you can run SCM-Manager only with a replica count of one. Therefore I think it makes no difference if we use a stateful set or a deployment.

Do you think we have missed something?
