### ISSUE TITLE
Can't open changeset details of mercurial repositories

### ISSUE THREAD

**Issue by LeandroAGR** [scm-manager/scm-manager#1587]
## Issue description

You can't open the page to see the details of the changeset for mercurial repositories, I tracked the error to the file scm-ui/ui-api/src/diff.ts at the line

initialLink = `${initialLink}?limit=${options.limit}`;

the code does not take into account the case where initialLink already have a parameter, in the case of a mercurial repo initialLink looks like '.../repositories/<namespace>/<reponame>/diff/<changeset>?format=GIT' and it just adds '?limit=25' to it, making it an invalid url

### How to Reproduce

Create a mercurial repository and push any files to it

Open scm-manager and navigate to the repository\code\commits and click on details on any changeset

It gives an error message for Illegal input

### Describe your SCM-Manager setup

SCM-Manager 2.15.0

**Comment by eheimbuch** [comment]
Hi @LeandroAGR,

thanks a lot for this report. We fixed this issue and just released a new version: https://scm-manager.org/download/2.15.1/#packages
