### ISSUE TITLE
Scm Single Sign On Plugin for version above 2.x

### ISSUE THREAD

**Issue by yashcho** [scm-manager/scm-manager#1624]
Hello Team,

Previously we were using SCM Auto Login Plugin for Single Sign On on version 1.60 but after migrating to 2.6 I am not able to use this plugin anymore plus I checked on CAS plugin which uses token Authentication but if we have a plugin which uses Header Authentication that would be good, Could you suggest something?

**Comment by sdorra** [comment]
That's not on our roadmap at the moment. If someone is willing to write it themselves, we would of course support as much as we can.

**Comment by yashcho** [comment]
Yes I am willing to write but for that I would need the endpoints which are used as a Authentication through headers as our project requirement is same. So if you can help with those classes mentioned below then it would mean a lot to me.. :)

AutoLoginAuthenticationFilter.java
AutoLoginAuthenticationHandler.java
AutoLoginConfig.java
AutoLoginConfigRessource.java
AutoLoginHelper.java

As those classes were part of 1.60 SCM and was used to enable SSO with headers but as for 2.0+ those classes are vanished and only some classes are there which only helps Token Authentication, No header authentication.

**Comment by sdorra** [comment]
Yes, of course. SCM-Manager 2 is slightly different then 1 in terms of authentication. 

The best way to start should be a fresh plugin. You can create a new one with [create-plugin.scm-manager.org](https://create-plugin.scm-manager.org/).

Then you have implement a [WebTokenGenerator](https://github.com/scm-manager/scm-manager/blob/2.0.0/scm-core/src/main/java/sonia/scm/web/WebTokenGenerator.java). Have a look on the [BasicWebTokenGenerator](https://github.com/scm-manager/scm-manager/blob/2.0.0/scm-webapp/src/main/java/sonia/scm/web/BasicWebTokenGenerator.java) for an example.

This WebTokenGenerator should return a new Shiro AuthenticationToken, have a look at the [BearerToken](https://github.com/scm-manager/scm-manager/blob/2.0.0/scm-core/src/main/java/sonia/scm/security/BearerToken.java) for an example. The token should contain all information you can extract from the http request which are relevant for the authentication.

The last step you have to do is to write a shiro realm for the final authentication, have a look at the [BearerRealm](https://github.com/scm-manager/scm-manager/blob/2.0.0/scm-webapp/src/main/java/sonia/scm/security/BearerRealm.java) for an example.

I hope that I could help you with this. If you have more questions feel free to ask.

**Comment by yashcho** [comment]
Thank you @sdorra for all this link, but to test do we have some scenario somewhere?, I would implement the given way and if I see any issue I would comment in this ticket.

As with our company policy we can't test directly create plugin on our application until it is secure enough.

**Comment by sdorra** [comment]
You can test the plugin with the following command `./gradlew run`.

**Comment by yashcho** [comment]
Hello @sdorra,

After checking those file the  BasicWebTokenGenerator  uses UserPasswordToken to generate, but our old plugin use to work on just username and not the password, so can you suggest something else that could generate token based on username from header instead of username and password, that would help us a lot.. :)

**Comment by sdorra** [comment]
You have to create you own token class e.g.: `SsoHeaderAuthenticationToken` which extends [AuthenticationToken](https://shiro.apache.org/static/1.4.0/apidocs/org/apache/shiro/authc/AuthenticationToken.html) (you can return `null` on `getCredentials`). After you have defined your token you can create a custom [AuthenticatingRealm](https://shiro.apache.org/static/1.4.0/apidocs/org/apache/shiro/realm/AuthenticatingRealm.html).

For an example you can have a look at the bearer token authentication:

* [BearerToken](https://github.com/scm-manager/scm-manager/blob/2.0.0/scm-core/src/main/java/sonia/scm/security/BearerToken.java)
* [BearerWebTokenGenerator](https://github.com/scm-manager/scm-manager/blob/2.0.0/scm-webapp/src/main/java/sonia/scm/web/BearerWebTokenGenerator.java)
* [BearerRealm](https://github.com/scm-manager/scm-manager/blob/2.0.0/scm-webapp/src/main/java/sonia/scm/security/BearerRealm.java)

**Comment by yashcho** [comment]
oka @sdorra, Thankyou for info let me check and revert you back for any issue in creation.. :)

**Comment by yashcho** [comment]
Hello @sdorra , Thanks for all your suggestion and I was able to create the custom token but now my second question is how to valid it with some ldap as we use a internal ldap after the SSO which verify the user is authorized to access the scm or not. Can you suggest something on this?

**Comment by yashcho** [comment]
No I was trying with placing sso-plugin folder directly under scm plugin but thankyou for your hint it works with above step now, but now second issue arises with authentication when opening scm it should use our plugin to authenticate but it using the Bearer Token & User Password Token to authenticate and the not the sso token, so do we need to change something in scm to only make it work with SSO plugin and not with some other authentication ?

**Comment by sdorra** [comment]
No this is not possible. The only thing which comes to my mind, is to block every request which does not contain the header from the reverse proxy. You can have a look at the [ForceCasLoginFilter](https://github.com/scm-manager/scm-cas-plugin/blob/develop/src/main/java/com/cloudogu/scm/cas/browser/ForceCasLoginFilter.java). It does not do exactly the same, but you can get an idea.

**Comment by yashcho** [comment]
Thank you @sdorra it works with that example, so now I have issue for the group sync from ldap as the groups from our ldap are created in scm but it's permission is not as per the name. e.g. Admins of Ldap group are getting user's permission in scm. Is there any way to sync the group according to the Ldap we use?

**Comment by sdorra** [comment]
Sorry, but i'm not sure if i understand your question. In SCM-Manager it is not necessary that a group exists, you can apply repository permissions to the name of the group without a prior creation of the group. If you want to apply global permissions (such as overall admin permissions), the easiest way is to create group with the exact same name as in your ldap, mark the group as external and assign the required permissions.

**Comment by yashcho** [comment]
Thank you @sdorra our team have successfully created the custom SSOHeader plugin with Ldap Integration. So should we share with you or is it fine to keep this at our end?

**Comment by eheimbuch** [comment]
Hey @yashcho 

Sorry we haven't answered your last question yet. We would like to integrate your SSO-Header-Plugin into the official SCM-Manager Plugin Center. For that we would need to fork the plugin repository into our organization. Is the plugin repository already on GitHub?

**Comment by yashcho** [comment]
Hello @eheimbuch , Thank you for your response as of now we are still polishing the code, so once we are done with that we would fork it.

As of now I have an issue with logout might @sdorra can help me, when we are logging out from scm it stuck in loop of logout, do you know the reason?

**Comment by yashcho** [comment]
Hello @eheimbuch, so we got the approval from our team lead but we don't have the code on public repo such as github it's stored under our internal private repository so we can provide you the code once you create a repo under your organization and then we will send the pull request. Is it fine for you?

**Comment by eheimbuch** [comment]
Hey @yashcho 

Sounds very good. We will create an new repository for you.

**Comment by yashcho** [comment]
Thank you @eheimbuch I have asked my colleague to do a pull request with all details, as worked more on the code base. :)
Can you even send @lego765 a collaboration invite?

**Comment by eheimbuch** [comment]
@yashcho @legos765 Your are now both permitted to write to the scm-sso-plugin.

If you are done pushing your code, we will have a look at it.

**Comment by yashcho** [comment]
Hello @eheimbuch my colleague is facing permission denied error while pushing the code to the repo. 

git push --set-upstream origin master
remote: Permission to scm-manager/scm-sso-plugin.git denied to legos765.
fatal: unable to access 'https://github.com/scm-manager/scm-sso-plugin.git/': The requested URL returned error: 403

Can you please the authority :) ?

**Comment by eheimbuch** [comment]
He has to accept the invitation to gain write permissions. The invitation is still pending.

**Comment by yashcho** [comment]
Thank you for quick response, we have now pushed the changes to the repo, can you please check it.. :)

**Comment by legos765** [comment]
Hi, @eheimbuch 
Sorry fo that, i didn't see the email.

Repo is already pushed and some additional info:
Some background why and what we do regarding sso-plugin:

Why do we needed to create our own Plugin?
SCM version 2.x has been rebuilt in terms of authentication, so we also had to change the SSO plugin that we used in the old SCM 1.60 version. Initially we tried to adapt the existing plugin to the new requirements, but it turned out to be incomplete due to significant differences in SCM structures.

What is it based on; Why did we took that plugin as a base?
While creating a new SSO plugin, we noticed the need to integrate login with our LDAP. Since without LDAP, it would only be possible to login for users, who exist only inside scm. That is why we decided to connect SSO plugin with the already existing (created by another person) LDAP plugin which allowed  to login people existing in LDAP using sso.

Which files are customized / added by us and why?
I added 3 new classes responsible for SSO part (SsoHeaderAuthenticationToken.java, SsoHeaderTokenGenerator.java, SsoHeaderRealm.java) . This is logic that generate token basing on X-Forwarded-User header and if user exist in LDAP allow him to login. And I modified one class that already existed (LdapAuthenticator.java), because it was checking for password, but we do not store it in instance-ldap so I had to skip this one step in “authenticate” function.

And we kept original Readme, beacuse it shows how to test plugin with ldap instance.

This is version that we are using in scm-manager, but if you have any concerns (or you want only sso part) let us know

**Comment by eheimbuch** [comment]
Thank you for your contribution. We will take a look and give you some feedback. I may take some days since we are currently very busy preparing the next big features.

**Comment by eheimbuch** [comment]
Hey @yashcho and @legos765,

the whole team thanks you for your contribution and today we reviewed your plugin together. While doing so we recognized that we should have made it easier for you to implement your feature. We are planning to create some public APIs you can use to collect your user informations (like from ldap) which are needed for your single-sign-on feature. 

This changes would make your plugin way easier to understand and reduce a lot of code. Also it would be possible to accept any header and make it less ldap-specific which should also be helpful for many other SCM-Manager users. 

What do you think? We will try to implement the new API in the next weeks. Afterwards we would like to tell you about our preferred implementation.

**Comment by yashcho** [comment]
Hello @eheimbuch ,
Sorry for replying late we had a long discussion and came to conclusion internally that we would proceed with the current setup which we prepared, but surely we would wait for your new feature of API once we would upgrade the scm in next year again.

Till then you could close the ticket and keep the code if it's reliable for the scm.. :)
