### ISSUE TITLE
unnecessary reloads in repository creation form

### ISSUE THREAD

**Issue by Shaoranlaos** [scm-manager/scm-manager#1644]
### Bug Report

If the check box "Initialize Repository" is checked every change in a field in the creation form reloads the template list and with this the whole form flickers on the screen.
This should only be the case when the check box "Initialize Repository" is changed.

#### Describe how to reproduce the bug

1. Create a template repository according to docu
2. Open the Repository creation form
3. Check the "Initialize Repository" check box
4. Change any field in the form (e.g. the contact)
5. The loading spiral will flicker and the template select list shortly disappears before it reappears.

#### Describe your SCM-Manager setup

SCM-Manager 2.17.1 with Plugin Repository-Template 1.0.2
Installation via Yum (RPM)

#### Which operating system, browser and versions do you use?

CentOS 7

**Comment by sdorra** [comment]
The issue is related to the core extension point and must be fixed there.
