### ISSUE TITLE
Incomplete and very aggresive cache clearing when gpg key is added/removed

### ISSUE THREAD

**Issue by 40rn05lyv** [scm-manager/scm-manager#1668]
sonia.scm.repository.api.RepositoryServiceFactory has cache clearing logic which is incomplete. Handlers for PublicKeyDeletedEvent and PublicKeyCreatedEvent events clear only LogCommandBuilder.CACHE_NAME.

Need to also clear ChangesetsCommandBuilder.CACHE_NAME and TagsCommandBuilder.CACHE_NAME, because they store Changesets with Signature objects. 

Would be nice to add more complex cache clearing logic and don't purge everything when a key is added or removed.

**Comment by pfeuffer** [comment]
Thanks for the hint, sounds right. We will take a look at this.
