### ISSUE TITLE
SSL cookie without secure flag

### ISSUE THREAD

**Issue by yashcho** [scm-manager/scm-manager#1684]
Hello @sdorra & Team ,
We got this issue again same as [https://github.com/scm-manager/scm-manager/issues/1281](url) and found two header's which we apply to the URL at SSL Interception are mentioned below.

X-Forwarded-Proto=https
X_FORWARDED_PROTO=https

So can you let us know by which header's you are considering the request is secured or not?

**Comment by pfeuffer** [comment]
Hi @yashcho ,
when I'm not mistaken we use the first form `X-Forwarded-Proto` (see [here](https://github.com/scm-manager/scm-manager/blob/5f887d4fa8d11f471de981ec78f5e112d1863fcf/scm-core/src/main/java/sonia/scm/util/HttpUtil.java#L132))
Regards
René

**Comment by yashcho** [comment]
So @pfeuffer , is there something which needs to be added in Header to make the request secure under proxy, because we call the scm using https://abc.com/scm where abc.com is our application address that perform SSL Interception. :)

**Comment by pfeuffer** [comment]
As long as the proxy does a redirect to https for "normal" http calls and as long as you trust your internal network, this looks fine for me (though our [Apache Configuration](https://www.scm-manager.org/docs/2.19.x/en/administration/reverse-proxies/#apache) mentions `X-Forwarded-SSL`, I think is no longer used).

**Comment by yashcho** [comment]
Thank you @pfeuffer for you quick response, after upgrading scm to 2.0 we didn't see the issue so will be closing the ticket with last comment

**Comment by pfeuffer** [comment]
Thanks for the feedback, @yashcho !
