### ISSUE TITLE
Autocomplete in groups doesn't always show exact match

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#1695]
A small but annoying issue, regarding the autocomplete when setting permissions in a repository. SCM-Manager 2.19.1

Situation:
- we have more than 5 groups that begin with the same prefix.
- we have a group whose name is exactly the given prefix.

In the Add New Permission textbox, we write the prefix.
We receive 5 suggestions - but none of them is the group that is named exactly as the prefix.
So it is not possible to find and select the group that we are looking for.

(It is actually possible if we choose the 6th option "Create prefix", but that is completely counter-intuitive, as that group already exists and won't be created)

I attach screenshots to illustrate the problem (the prefix has been changed).

![image](https://user-images.githubusercontent.com/7532590/121420738-b75ee580-c96d-11eb-9f4c-e5fd248dfa02.png)

![image](https://user-images.githubusercontent.com/7532590/121420651-a2825200-c96d-11eb-8aea-285388c4369e.png)

I would suggest that the suggestion logic checks if there is an exact match, and if so, puts it in the first position. Alternatively, sort the matches first by length and then alphabetically could also work.

I assume that the autocomplete of users might have the same issue - haven't tested it though.

**Comment by pfeuffer** [comment]
This sounds like a good sugestion. It should be possible to implement in the [GenericDisplayManager](https://github.com/scm-manager/scm-manager/blob/develop/scm-webapp/src/main/java/sonia/scm/GenericDisplayManager.java#L48), eg. by first looking for an entry with the exact id.
