### ISSUE TITLE
Make custom namespace field autocomplete in create repository form

### ISSUE THREAD

**Issue by Shaoranlaos** [scm-manager/scm-manager#1723]
#### Problem to be solved

It can easily happen that you get a typo in your custom namespace field when you are creating a new repository.
That you would only realize after creating it when you are actively searching in the whole namespace or when the users with rights on the namespace does not have the right privileges for the repositiory.
This can also interrupt the automatic build pipeline creation via the scm-plugin in Jenkins.

#### Proposed solution

A solution would be to convert the namespace field into an autocomplete field which proposes a number of existing namespaces depending on your entered text. It would then work like the field to add members to a group.

![image](https://user-images.githubusercontent.com/25054970/124477926-e584e900-dda4-11eb-8981-ea4885838e85.png)

**Comment by eheimbuch** [comment]
Hey @Shaoranlaos 

This is a very nice suggestion. I will take this to our team and we will try to implement it soon.

**Comment by pfeuffer** [comment]
Fixed with #1916. This will be released with version 2.30.0.
