### ISSUE TITLE
Usability: Omnisearch: repositories with "-" cannot be filtered on

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#1743]
A relatively minor problem.

Let's say you have a repository called Name-Subname

In the new omnisearch textbox,

* Type "name" --> the repository "Name-Subname" is listed as a possible result --> OK 
* Type "subn" --> the repository "Name-Subname" is listed as a possible result --> OK
* Type "name-" --> there is a message "Could not find matching repository" instead --> NOK
* Type "-subn" -->  there is a message "Could not find matching repository" instead --> NOK

My guess is that this has to do with the Lucene syntax that you hinted at in your blog post. Be that as may be, I'd argue that the hyphen is not such an uncommon symbol for repository names, and it is highly inconvenient to be unable to filter repositories which use hyphens.

SCM-Manager 2.21.0

**Comment by sdorra** [comment]
This is interesting it seems like to work if i specify the searched field (expert mode, we will explain this in more detail with v2.22.0), but in the simple query mode it fails.

I've tested with a repository called `something-may-catch-fire` the expert search returns the repository:

A search for `name:something-may` is translated in `+(name:something name:may) +_type:repository`, which is interesting lucene splits the searched string and makes an `or` of it.

This simple search does not return the repository:

A search for `something-may` is translated into `+((namespace:something-may*)^1.25 (name:something-may*)^1.5 description:something-may*) +_type:repository`, which is not slit.

My guess is that the used analyzer tokenizes the repository name into the following tokens:

* something
* may
* catch
* fire

And this is why a search for "something-may*" does not match. 
I'm not sure if it is a good idea to do the split into an `or` query for the simple search as well or if we must change the analyzer. We have to discuss this.

Thanks for the report.
