### ISSUE TITLE
Possible XSRF issue: "Error: The session has expired You can login here again" in first operation after login

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#1751]
I think we are encountering a side effect of the experimental setting "Enabled XSRF Protection"

Our browser is configured to delete all the cookies when closing. So each time I want to get into our SCM Manager, I have to log in from zero.

After I log in, I can browse around (that is, issue GET requests) without problem. But as soon as I try to do a change (POST), it *always* fails with the message "Error: The session has expired You can login here again.". Then I click on the link, try to do the change again, and from that moment on it works without any problem.

My suspicion is that the first POST does *not* include (for some reason) the X-XSRF-Token header, whereas the second and next do:

<pre>
POST /scm/api/v2/repository-avatar/hg/REPONAME/auto-generated HTTP/1.1
Host: THEHOST
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://THEHOST/scm/repo/hg/REPONAME/settings/general
Cache: no-cache
X-Requested-With: XMLHttpRequest
X-SCM-Client: WUI
X-SCM-Session-ID: KRQ***8VH
Content-Type: application/json
Origin: https://THEHOST
DNT: 1
Connection: keep-alive
Cookie: X-Bearer-Token=eyJhbGc*********jYKlfE
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
Content-Length: 0
</pre>

vs

<pre>
POST /scm/api/v2/repository-avatar/hg/REPONAME/auto-generated HTTP/1.1
Host: THEHOST
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://THEHOST/scm/repo/hg/REPONAME/settings/general
Cache: no-cache
X-Requested-With: XMLHttpRequest
X-SCM-Client: WUI
X-SCM-Session-ID: KRQ***LQP
X-XSRF-Token: ead65***-****-****-****-*****3c0890c
Content-Type: application/json
Origin: https://THEHOST
DNT: 1
Connection: keep-alive
Cookie: X-Bearer-Token=eyJhbGc*********jYKlfE
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
Content-Length: 0
</pre>

Which diffs as:

```diff
 Cache: no-cache
 X-Requested-With: XMLHttpRequest
 X-SCM-Client: WUI
-X-SCM-Session-ID: KRQ***8VH
+X-SCM-Session-ID: KRQ***LQP
+X-XSRF-Token: ead65***-****-****-****-*****3c0890c
 Content-Type: application/json
 Origin: https://THEHOST
 DNT: 1
```

I assume that the session ID changes because I have relogged using the link, and that it is the XSRF token what makes the second request work and the first one fails.

Ideally, I think this header should have been sent in the first request too.

If there's something else I can do to help you diagnose this issue please let me know.

Edit: SCM Manager 2.21.0

**Comment by eheimbuch** [comment]
Hey @fnajera-rac-de,

it seems like you really are our best tester. :) We will look into this issue and try to fix this asap.

BTW: It seems like you work a lot with mercurial. We are planning to add some new mercurial features but since there are a lot options we are not sure where to start. We would love to hear your opinion what features you desire the most for SCM-Manager.

You can give us your feedback at this [survey](https://docs.google.com/forms/d/e/1FAIpQLScvdjEux2bngeM6nX_gzosJa9t4NAEq_2IBojsyUHqMI8yQAg/viewform?vc=0&c=0&w=1&flr=0) or contact us directly. Also feel free to share this survey with your colleagues if they are interested in mercurial. Thanks!

**Comment by eheimbuch** [comment]
Hey @fnajera-rac-de,

I cannot reproduce your error. I have tried the setup you describe, but every POST request seems to work. Do you have more clues you can share?

**Comment by fnajera-rac-de** [comment]
Thanks for looking into it @eheimbuch 

I can still reproduce it. I had a look at the settings and played a bit, and the one thing that seems to have an impact is the "Force Base URL".

We have both a Base URL and the [x] Force Base URL set. Like this, after clearing cookies (in our case, just closing/opening the browser), it always happens.

If I keep Base URL but disable [ ] Force Base URL, then the problem seems to go away.

Just in case it helps: I always log in with the Base URL...

**Comment by eheimbuch** [comment]
Maybe we have a theory. Do you use a reverse proxy?

**Comment by fnajera-rac-de** [comment]
Indeed

**Comment by eheimbuch** [comment]
@sdorra thinks it's likely your reverse proxy removes the token on the first request. But we are not sure why this happens. Could you look into your reverse proxy configuration?

**Comment by fnajera-rac-de** [comment]
I have another theory different, though. I have been nosing around and I found that the XSRF header is set via javascript and it's based on the X-Bearer-Token, which is correctly set at the beginning of the session and carried from there on.

So... can it be that the javascript code that sets the XSRF header is not being called when I first log in?

In the network call of Firefox, I can see that when I first log in, the following request is made:

POST /scm/api/v2/auth/access_token

whereas, when the error comes and I click on the link, the request being made is quite different:

GET /scm/login?from=%2Frepo%2Fhg%2FREPONAME%2Fsettings%2Fgeneral

which probably reloads the page and triggers the javascript code in question (since the Bearer Token is there now).

Can you try to reproduce this in a Private-Mode window in your browsers? 

Maybe your browser has cached your X-Bearer-Token somehow and when you open SCM Manager, the javascript is being triggered already - whereas for me, it is not.

**Comment by fnajera-rac-de** [comment]
@sdorra @eheimbuch Yes! Confirmed, that's the issue.

Scenario 1:
- I open a private window
- Browse to the root of SCM Manager
- Enter user and password, log in
- Navigate to a button (such as repo - settings - save)
- Error comes

Scenario 2:
- I open a private window
- Browse to the root of SCM Manager
- Enter user and password, log in
- **Press F5 to reload the site**
- Navigate to a button (such as repo - settings - save)
- No error

**Comment by sdorra** [comment]
I'm sorry but i can't reproduce this behaviour. Could you post your reverse proxy configuration?

**Comment by fnajera-rac-de** [comment]
I'm sorry, it turned out to be indeed a nginx reverse proxy misconfiguration. Apologies for the wasted time.

In case someone else finds this in the future: make sure your site has one and only one proxy_pass, and if you ever have several, make sure the URLs are exactly the same.
