### ISSUE TITLE
Too many warnings sonia.scm.web.SchemeBasedWebTokenGenerator - could not create token from authentication header

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#1772]
In connection with #1771, we have seen that every time we issue an API request using a Bearer token, there is a new entry in the log file with category WARN:

<pre>
2021-08-13 11:22:54.351 [qtp1347137144-10351] [          ] WARN  sonia.scm.web.SchemeBasedWebTokenGenerator - could not create token from authentication header
</pre>

The API requests do work, so it seems that the header is actually read and understood.

This is a minor problem (it's "just" warnings in the log file), but it triggers our monitoring tools.
We will add an exception for this message, but you may want to have a look to see if it can be prevented at all.

An example of a call that triggers this warning (in case I'm doing something wrong):

<pre>
curl --location --request GET "https://server.tld/scm/api/v2/repositories?q=test&pageSize=100" --header "Accept: application/vnd.scmm-repositoryCollection+json;v=2" --header "Authorization: Bearer eyJ......5Y0"
</pre>

**Comment by sdorra** [comment]
The problem is that there are multiple `SchemeBasedWebTokenGenerator` and only one is responsible for the `Bearer` scheme the other produce the log you've seen. But you are right the log level should be debug,
