### ISSUE TITLE
UI: Cannot access mercurial repository at all if default branch is closed

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#1782]
To reproduce:

* Create a mercurial repo in SCM - say, "scmmercurialtest"
* Then, clone and create a some file, branch and close the default branch.

<pre>
mkdir c:\temp\scmmercurialtest
cd /d c:\temp\scmmercurialtest
hg clone %server%/scm/repo/%ns%/scmmercurialtest .
echo. > file
hg addremove
hg commit --message "test"
hg push
hg branch another
echo. >> file
hg commit --message "test"
hg push --new-branch
hg up default
hg commit --message "closing default" --close-branch
hg push
</pre>

Now, just use the SCM Manager web and navigate to the repository:

![image](https://user-images.githubusercontent.com/7532590/130779133-c475c375-44dc-481e-aee5-41a7338e7cbc.png)

Note that the error message blocks the whole right-side menu, so there's no access to Settings for example.

Changing the URL manually does work, though. But as soon as you click Code (which is the default now), you get back to the picture above.

SCM Manager 2.22.0

**Comment by eheimbuch** [comment]
Hey @fnajera-rac-de,

sound interesting. Why would you want to close your default branch? 

But we will have a look. Thanks for your finding.

**Comment by elawson668** [comment]
Is there any update on this? We are migrating from a Mercurial service that labels default branches as "trunk" instead of "default".

**Comment by pfeuffer** [comment]
Sorry, but we cannot reproduce the error (our test repositories do not have files called `branch2-served`). Can you attach a zipped repository with this error, or even better a way how to create this error starting with an empty repository?

**Comment by Eddie-cz** [comment]
Hello, happens to us also, just have mercurial repo without default branch, push it to scm and you cannot manage that repo at all.

**Comment by Svedrin** [comment]
happens to me as well, with a few very old repos that I converted from SVN. They don't have a `default` branch, it's called `trunk` here.

**Comment by fnajera-rac-de** [comment]
> Sorry, but we cannot reproduce the error (our test repositories do not have files called branch2-served). Can you attach a zipped repository with this error, or even better a way how to create this error starting with an empty repository?

I'm confused. There has been one set of instructions to reproduce this on the top message of this issue from the start, and nowhere in this issue anyone talked about 'branch2-served'.

Here goes a second one - no deleted branch anymore, just a repo without default:

<pre>
hg init .
hg branch trunk
echo. > file
hg addremove
hg commit --message "test"
</pre>

**Comment by Eddie-cz** [comment]
There is a obvious blocker in SCM manager, causing unability to maintain some hg repos, but nobody is responding...or saying they don't understand. Can somebody responsible fix this???

**Comment by Phil-Ah** [comment]
Hey @Eddie-cz , we are aware of this issue. Unfortunately our team is involved different other topics right now. 
As SCM-Manager is open source software anybody may try and fix this. We are open to pull requests if you or someone else is able to contribute.

**Comment by pfeuffer** [comment]
Sorry for the confusion on my side. Most probably you can find a fix for the error in the frontend in the next release, we are working on it right now.

Is there a hg way to determine a new default branch, if `default` has been closed? Right now I just pick one of the other branches to display the sources. Or would this have to be done by a configuration option (like in git repositories)?

**Comment by eheimbuch** [comment]
This issue was fixed: https://github.com/scm-manager/scm-manager/commit/e679dac94d320c93e9d7c6a6ad37b7cc2c2ca3da

The next release should be right after the easter weekend.
