### ISSUE TITLE
TypeError: Cannot read property '_links' of undefined

### ISSUE THREAD

**Issue by mrPsycho** [scm-manager/scm-manager#1791]
## Issue description

On main page i started to see that: 
TypeError: Cannot read property '_links' of undefined

![image](https://user-images.githubusercontent.com/883964/131669448-ae141ea0-4a6c-4523-ad2a-8e1f2009b312.png)

### Bug Report

What i've done: 
* installed fresh scm 2.22
* installed plugins:
root@redmine:/home/user# ls /var/lib/scm/plugins/
scm-activity-plugin                scm-el-plugin            scm-landingpage-plugin  scm-redmine-plugin
scm-authormapping-plugin           scm-git-plugin           scm-ldap-plugin         scm-repository-avatar-plugin
scm-code-editor-plugin             scm-gravatar-plugin      scm-legacy-plugin       scm-repository-mirror-plugin
scm-commit-message-checker-plugin  scm-hg-plugin            scm-mail-plugin         scm-svn-plugin
scm-directfilelink-plugin          scm-issuetracker-plugin  scm-pushlog-plugin      scm-webhook-plugin
scm-editor-plugin                  scm-jenkins-plugin       scm-readme-plugin
* migrated some svn and git repos by https://www.scm-manager.org/docs/2.22.x/en/import/
* I also tried to execute some basic API's:
curl  -X POST -u scmadmin:secret -H 'content-type: application/json'  https://scm.domain/scm/api/v2/repositories/
curl  -X GET -u scmadmin:secret -H 'content-type: application/json'  https://scm.domain/scm/api/v2/repositories/
and some other GET to get more details about repos
* And it started to show error.

#### Describe your SCM-Manager setup

* Version 2.22
* Ubuntu LTS 20.04
* Behind nginx proxy
* installed via apt 
* default config
#### Log of the bug

Nothing happens in scm-manager.log

**Comment by sdorra** [comment]
It looks like a login info url has been configured that returns entries without _links. You can fix this by restoring the original url in the config.xml. The config.xml is located in the SCM-Manager home directory. Search the line with `<login-info-url>...</login-info-url>` and replace it with `<login-info-url>https://login-info.scm-manager.org/api/v1/login-info</login-info-url>`. After you have changed the config file, you have to restart SCM-Manager.

I think we should make this more robust.

**Comment by mrPsycho** [comment]
@sdorra thank you, yes, looks like it was mistake.
