### ISSUE TITLE
Activity tab is blank

### ISSUE THREAD

**Issue by fnajera-rac-de** [scm-manager/scm-manager#1862]
From version 2.26.0, our Activity tab is completely blank. Uninstalling/reinstalling the plugin didn't help.

There's nothing in the log file that we can see, or in the HTTP traffic on the browser. There is just nothing shown.

We are now on 2.27.0 and we still don't have anything in that tab.

Is there any debug trick I can use to try to diagnose this further?  I see a line "sonia.scm.activity.CacheWarmUpListener - start cache warm up" -> can it be that some cache is corrupted and that breaks the plugin? If yes: what should I do?

<pre>
2021-11-16 23:50:11.898 [main] [          ] INFO  sonia.scm.plugin.PluginProcessor - install plugin tree:
+- scm-repository-avatar-plugin@1.1.0
+- scm-activity-plugin@2.0.0
+- scm-git-plugin@2.27.0
+- scm-legacy-plugin@2.27.0
+- scm-hg-plugin@2.27.0
+- scm-groupmanager-plugin@2.0.0
+- scm-ldap-plugin@2.4.0
+- scm-issuetracker-plugin@3.1.0
+- scm-mail-plugin@2.7.1
   +- scm-issuetracker-plugin@3.1.0
   +- scm-notify-plugin@2.0.3
+- scm-svn-plugin@2.27.0
+- scm-el-plugin@1.0.0
   +- scm-webhook-plugin@2.2.0
+- scm-webhook-plugin@2.2.0
+- scm-notify-plugin@2.0.3
</pre>

**Comment by eheimbuch** [comment]
Hey @fnajera-rac-de,

the activity plugin is kinda deprecated. We do not plan to support this plugin any longer. Instead we have created the [Landingpage Plugin](https://scm-manager.org/plugins/scm-landingpage-plugin/) which includes the activities but also some more useful features. Could you try this out?

**Comment by fnajera-rac-de** [comment]
Ok! I didn't know that it was deprecated. We will try the Landingpage plugin as soon as we can, and I'll reply here.

Side idea: maybe add a 'deprecated' text in the plugin overview? 

![image](https://user-images.githubusercontent.com/7532590/142174852-73bf2a65-c06f-4d41-895e-21eb6a79912b.png)

**Comment by eheimbuch** [comment]
You are right. We haven't decided yet how to mark plugins as deprecated.

**Comment by fnajera-rac-de** [comment]
The Landingpage plugin did indeed work. Thanks!
