### ISSUE TITLE
Remove "repo" from repository url

### ISSUE THREAD

**Issue by oollie2** [scm-manager/scm-manager#1909]
### Feature Request
To migrate from Subversion Edge to this, I need the url to match the original one.
I need to remove the "repo" section of the url, for example:

from -http://localhost:8080/repo/namespace/repositoryname
to -http://localhost:8080/namespace/repositoryname

Am I missing a way this can be done already...?

### Proposed solution
Have a global setting to rename the "repo" directory to something of the users choice. This could potentially fix my issue?
Or allow removing it entirely...

**Comment by eheimbuch** [comment]
Currently this is not possible, because we would have to exclude every existing route as "settings" or "pluginXyz" as valid namespace. Since most plugins are optional and we cannot ensure to avoid route collision, we have no idea how to fulfill your feature request.

**Comment by oollie2** [comment]
Understood! Thanks for taking the time to reply, I'll look into my other options for getting this running.
