### ISSUE TITLE
Paging on list of pull requests

### ISSUE THREAD

**Issue by Matko88** [scm-manager/scm-manager#1914]
## Issue description

When listing pull requests it takes longer and longer to show it.

### Feature Request

Paging on list of PRs.

#### Problem to be solved

Since we create PRs daily, it takes longer and longer to show merged or all PRs. Now it takes around 7 seconds and we have 375 of PRs to show.

#### Proposed solution

Add paging to list of PRs.

Best regards, Matjaz

**Comment by Matko88** [comment]
14 seconds for 457 PRs in history. Looks like it's not linear. I hope someone can find time for this :) Even if it just limits the amount of PRs to last 100 or so. Thanks :)

**Comment by pfeuffer** [comment]
Be assuered, this is on our list (we have the same issue here for some of our own projects).

**Comment by eheimbuch** [comment]
Hey @Matko88,

we just released the newest version of the [Review Plugin](https://scm-manager.org/plugins/scm-review-plugin/releases/) including pagination for pull requests. You have to update your SCM-Manager first to version 2.32.0 before you can install this plugin through the plugin center.

**Comment by Matko88** [comment]
Ok I have the latest version of both.

Now what happens is, that when I go to repository, click on PR and then select "All", it shows first page. So far so good.
Then I click on page 2 and it changes selection to "Open" which shows no results on the second page. I have to select "All" again to show results. After that, paging works ok.

But overall, after things are cached it works really fast :+1: Thank you guys, I'll chip in for a coffee

**Comment by pfeuffer** [comment]
Hi @Matko88 , you're right, we have left some bugs there. We will fix them soon, Thank you very much for the hint!

**Comment by pfeuffer** [comment]
Hi @Matko88 , we released a fixed version of the review plugin. Finally, this should work now.

**Comment by Matko88** [comment]
This thing works now, but the issue is somewhere else I guess. Whenever I switch page for the first time, it takes the same amount of time to show the page. For example, I select "All" at the top filter, and then it loads first page for 10s. I have 51 pages, this means 10min to go through all. Before it loaded all at once and it took 14s to show all.

When I move through pages after it was loaded it works fast. Probably some cache in the background. But if I refresh the page (even simple reload of site), it takes 10s for each page to load again. Is it my setup that is slow or is the query slow? How can I help you debug it?

**Comment by eheimbuch** [comment]
Could you describe your setup?

On our infrastructure it works pretty fast. Less than one second to load
the page initially.

Matko88 ***@***.***> schrieb am Mo., 21. März 2022, 09:23:
