### ISSUE TITLE
Users can't login (htpasswd) - After upgrade from 1.60 to 2.x

### ISSUE THREAD

**Issue by ggrandes** [scm-manager/scm-manager#1961]
After upgrade from 1.60 to 2.31.1 our users can't login, we use the [scm-htpasswd-plugin](https://bitbucket.org/triologygmbh/scm-htpasswd-plugin) in 1.60.

Note: I only see CAS and LDAP, which are much more complex than htpasswd. Is there an equivalent alternative with the same level of simplicity in 2.x to externalize passwords?

**Comment by pfeuffer** [comment]
We are sorry, but the htpasswd plugin has not been migrated (yet?). CAS and LDAP are the only external authentication systems right now.

Would you dare to try a migration? We would love to support you.

**Comment by ggrandes** [comment]
...migration to what?

**Comment by pfeuffer** [comment]
Sorry, I mean the migration of the plugin from 1.x to 2.x of SCM-Manager.

**Comment by eheimbuch** [comment]
Thanks again for your contribution and your patience @ggrandes . Your plugin is now available on our [website](https://scm-manager.org/plugins/scm-htpasswd-plugin/releases/) and through the official plugin center.
