### ISSUE TITLE
Relative Image links are not rendered in Markdown

### ISSUE THREAD

**Issue by Clindbergh** [scm-manager/scm-manager#1979]
## Issue description

Create an a markdown file and add an image in the same (sub-) folder as the markdown file. Add an image link (using `\!\[relative_path.png\]\(relative_path.png\)`). A number of [markdown editors](http://zettlr.com/) will render the image correctly and so does github. SCM Manager doesn't render the image. Instead it renders a small image with the filename.

![image](https://user-images.githubusercontent.com/2742027/158854105-2736e071-ab9b-4572-8a93-5844ed55ee16.png)

The path to the rendered image is https://our-installation.com/039e3aeb765c03008a7c5ea91f389279.png which is obviously wrong. The path should be generated respecting the relative path.

#### Describe your SCM-Manager setup

SCM-Manager 2.25.0
Not aware of any plugins

**Comment by pfeuffer** [comment]
You are definitely right, @Clindbergh . We have this on our to-do list.

**Comment by eheimbuch** [comment]
Fixed with release 2.41.0.

Read the related blog post: https://scm-manager.org/blog/posts/2023-01-23-scm-manager-2-41-0/#image-resolution-in-markdown
