### ISSUE TITLE
Documentation about virtual group "_authenticated"

### ISSUE THREAD

**Issue by ggrandes** [scm-manager/scm-manager#1981]
The virtual group "[_authenticated](https://scm-manager.org/blog/posts/2013-06-02-new-features-of-scm-manager-1-31/)", exist on the 2.x branch? ❓ ❓ 
I haven't found any documentation about it nor [migrate](https://scm-manager.org/docs/2.32.x/en/migrate-scm-manager-from-v1/), [faq](https://scm-manager.org/docs/2.32.x/en/faq/), ...

**Comment by pfeuffer** [comment]
Hi, the group `_authenticated` was introduced in [version 1.31](https://scm-manager.org/blog/posts/2013-06-02-new-features-of-scm-manager-1-31/)

**Comment by ggrandes** [comment]
Yes, but... is currently working on 2.x?

**Comment by pfeuffer** [comment]
Ah, sorry, yes: This group still works in 2.x.

**Comment by ggrandes** [comment]
Thanks; how about a mention about this implicit group in current doc, may could be.... [here](https://scm-manager.org/docs/2.32.x/en/user/group/)?

**Comment by eheimbuch** [comment]
We added docs about the virtual group. It will be available after the release which should be tomorrow.
