### ISSUE TITLE
Side by Side Diff

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#200]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/200) by hyltonpeimer (Bitbucket: [hyltonpeimer](https://bitbucket.org/hyltonpeimer), ).**

----------------------------------------

Hi,

Is there already a feature where by providing a (Mercurial) changeset, it would be possible to diff the files in the changeset (side-by-side) with previous versions of the files?

Thanks,

Hylton.

**Comment by sdorra** [comment]
Version 2 comes with a side-by-side diff.
