### ISSUE TITLE
"Use Author as from Address" option not working in email notifications

### ISSUE THREAD

**Issue by ckeydel** [scm-manager/scm-manager#2012]
As reported here previously:

https://groups.google.com/g/scmmanager/c/H5AqJi6Rlow.

Still present in latest SCM-Manager 2.32.2 running under Ubuntu 18.04.6 LTS.

**Comment by ckeydel** [comment]
I would like to add and clarify the current situation:

About 1/8th of the times, the notification emails are sent as

`SCM-Manager System Account <system...@ourdomain.com>`

This is literally the string "SCM-Manager System Account" used as the From: name. The rest of the times, the notification emails are sent as

`username <system...@ourdomain.com>`

where 'username' is replaced by the name of the actual user. One or the other happens randomly, I couldn't find any special situation or circumstance to force this choice.

The version 1.6 behaviour that we would like to have back is that if this option is enabled, the emails are sent as

`username <user-email@ourdomain.com>`

Thanks for looking into it.

**Comment by eheimbuch** [comment]
Hey @ckeydel,

this bug was fixed and released with the [Mail Plugin](https://scm-manager.org/plugins/scm-mail-plugin/releases/) version 2.7.2.

Best Regards,
Eduard
