### ISSUE TITLE
Use valid CSS to define padding

### ISSUE THREAD

**Issue by Phil-Ah** [scm-manager/scm-manager#2022]
## Issue description

If you found a bug or want to have a new feature implemented, please take your time and look whether this issue has been discussed in another issue or on our mailing list already.

SCM-Manager is open source. If you have any knowledge of programming, maybe you can help. We would love to support you.

### Bug Report
Each view of SCM-Manager contains a wrong CSS definition for a padding. `padding: inherit 0`; is not viable CSS and should be split into two separate lines.

#### Describe how to reproduce the bug
Open SCM-Manager (any view) and validate the HTML.

Please provide a detailed description of what has to be done to reproduce your bug (settings, click paths, ...)

#### Describe your SCM-Manager setup

What plugins and what versions do you use? Are you using a server like tomcat? Do you have special settings like proxies? Are you running your instance behind a reverse proxy?

#### Which operating system, browser and versions do you use?

Windows. Chrome and Firefox, latest versions?

#### Log of the bug

Please remember to check for any sensible information in any logs you provide like repository names!
Consider to use the [support plugin](https://scm-manager.org/plugins/scm-support-plugin/) to easily create trace logs.

**Comment by eheimbuch** [comment]
Fixed by #2023
