### ISSUE TITLE
SCM does not attach to cmd on Windows

### ISSUE THREAD

**Issue by GeggsLegs** [scm-manager/scm-manager#2029]
## Issue description

Whenever i start SCM using cmd it starts the service but does not attach to the console.

#### Describe how to reproduce the bug

After starting it using cmd or powershell it will return to command input. as far as I know my issue seems unique to my server

#### Describe your SCM-Manager setup

I'm using Java jdk-17.0.1 with SCM-Manager 2.32.2 on Windows

#### Log of the bug

By running "scm-server test" It shows a message of it unable to attach
![image](https://user-images.githubusercontent.com/89689465/167196643-1e054f6c-72bc-4dfa-9533-bd9c9a2d826c.png)

**Comment by pfeuffer** [comment]
Hi,

so you have called ´scm-server install´ and ´scm-server start´ beforehand? I can reproduce your log output when the server is not running. Can you take a look at ´scm-manager.log´ in the ´logs´ folder? Can you find any errors there?

Regards
René
