### ISSUE TITLE
Error 500 on Windows

### ISSUE THREAD

**Issue by GeggsLegs** [scm-manager/scm-manager#2030]
## Issue description

After about a day or more of running, the server will suddenly start sending error 500 to anyone who tries to access it.
When i try to stop it using cmd it says It's no longer running, even though the website still gives an error 500. And then starting it doesn't fix it either. the only way to temporarily fix the issue is to completely restart the server.

#### Describe how to reproduce the bug

I do not know what causes the issue so I cannot explain how to reproduce it. it appears to happen randomly after some time.

#### Describe your SCM-Manager setup

I'm using Java jdk-17.0.1 with SCM-Manager 2.32.2 on Windows

#### Log of the bug

[scm-server.err.log](https://github.com/scm-manager/scm-manager/files/8643278/scm-server.err.log)

**Comment by eheimbuch** [comment]
Hey @GeggsLegs 

my first guess is that you have started the server several times (more than 1?) or have other applications running on the same port which caused this conflict 

From your log:
`Caused by: java.net.BindException: Address already in use: bind`
