### ISSUE TITLE
LFS is giving incorrect hash

### ISSUE THREAD

**Issue by Saragani** [scm-manager/scm-manager#2043]
I'm getting an error when cloning a repository:
Downloading Deployment Materials/Data/some path/some file.xml (11 MB)
Error downloading object: Deployment Materials/Data/some path/some file.xml (e7bdc0d): Smudge error: Error downloading Deployment Materials/Data/some path/some file.xml (e7bdc0d7851c3fe6bb43d8836a27f1d110504b5cc9ef756e348ed156f1cd4841): expected OID e7bdc0d7851c3fe6bb43d8836a27f1d110504b5cc9ef756e348ed156f1cd4841, got 98a84bfe44be9dae80c906c82ba555f93e8e140b8d31769e02bcd6175238e718 after 2732544 bytes written
Errors logged to C:\Users\Itais\Documents\unilogic3\.git\lfs\logs\20220522T134651.7824827.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
Filtering content:  99% (3307/3337), 990.31 MiB | 8.89 MiB/s 

Later on, when sourcetree is requesting to download the lfs, I get the following error (30 files total fail on lfs)

![image](https://user-images.githubusercontent.com/4511559/169691713-cce5d43a-55c2-4137-8223-00dafc09bb07.png)

This is a repository I've created only few days ago.
The Non-LFS files are stored in BitBucket, and the LFS files are on a local repository, running SCM Manager 2.34.0

I did nothing special. If I cannot trust the LFS, then it is useless.

**Comment by Saragani** [comment]
Looking at the error, I see a lot of after 131072 bytes written. I can hardly assume that there are so many files with that exact same size (which is 0x2000 bytes).

Btw, the first error is:
Downloading Deployment Materials/Data/some path/some file.xml (11 MB)

And then
(e7bdc0d7851c3fe6bb43d8836a27f1d110504b5cc9ef756e348ed156f1cd4841): expected OID e7bdc0d7851c3fe6bb43d8836a27f1d110504b5cc9ef756e348ed156f1cd4841, got 98a84bfe44be9dae80c906c82ba555f93e8e140b8d31769e02bcd6175238e718 after 2732544 bytes written

2732544 written. It is only 2.6MB

**Comment by Saragani** [comment]
OK, I think that maybe a communication error caused the file to be incomplete (I was working with the "local" server with VPN, and the connection timed-out few times).

The SCM manager was returning the file from the lfs bob, even when it was incomplete (Which is not a correct behavior).


As I understand, a LFS file is being saved in the blob storage even though the transfer was not completed successfully.


The transfer should work as follows:
When transferring a file to the LFS, store it first in a temp location.
If transfer fails in the middle, then delete the file
If transfer is completed successfully, calculate the SHA over the received file, and only if SHA is matching the required value, then move the file to the git-lfs folder.

**Comment by eheimbuch** [comment]
Hey @Saragani 

I am not sure if this is an issue how we handle LFS or with the default LFS workflow. We will discuss this and come back to you.

**Comment by Saragani** [comment]
Great :-)
