### ISSUE TITLE
Error "Illegal input" if  branch name contains non-English characters

### ISSUE THREAD

**Issue by dpashev** [scm-manager/scm-manager#2061]
## Issue description

If the branch name contains non-English characters (Cyrillic), an error occurs.

#### Describe how to reproduce the bug

If the branch name contains non-English characters (Cyrillic), the following error occurs:
Error: Illegal input

The values could not be validated. Please correct your input and try again.

Violations:

getBranchDetailsCollection.arg2[1].<list element>: must match "[\w-,;\]{}@&+=$#`|<>]([\w-,;\]{}@&+=$#`|<>/.]*[\w-,;\]{}@&+=$#`|<>])?"

Transaction ID BZT89N44NOT

#### Describe your SCM-Manager setup
OS: Fedora Linux 35 (Thirty Five)
SCM-Server:  scm-server-2.35.0-.noarch.rpm
Plugins: 
*  Authentication: LDAP,SSH
*  Authorization: Branch Write Protection,Group Manager,Path Write Protection
*  Information: Activity,Author Mapping,Landingpage
* Library: CodeEditor,Expression Language,Issue Tracker,Mail
* Source Code Management: Git,Subversion
* Workflow: Archive,Direct Filelink,Editor,Notify,Push Event,Repository Mirror Plugin,Review,Webhook

#### Which operating system, browser and versions do you use?
OS: Fedora Linux 35 (Thirty Five)

Windows, Linux? Chrome, Firefox 

#### Further information like screenshots
![изображение](https://user-images.githubusercontent.com/6588936/172585701-af86bbc1-1c0f-44cf-96ef-b29957aec04c.png)

**Comment by fscholdei** [comment]
Thanks for sharing this issue. Valid branches should not be displayed as faulty in the interface. I will remove the validation on the branch overview.
