### ISSUE TITLE
Merging PR after resolving conflicts

### ISSUE THREAD

**Issue by gatanasov88** [scm-manager/scm-manager#2069]
## Issue description

Pull Request remains in status OPEN, after resolving conflicts and merge.

#### Describe how to reproduce the bug

I create a Pull Request that has conflicts to resolve. After following the instructions from the attached file, the changes are applied to the server, the merge is reflected in the log, but on the  web page PR remains in the status "OPEN", but not "MERGE".
![Capture](https://user-images.githubusercontent.com/66259532/174549855-d7dcefa9-16c1-48d9-a6f9-b0532dd94ce6.PNG)

#### Describe your SCM-Manager setup

OS: Fedora Linux 35 (Thirty Five)
SCM-Server: scm-server-2.36.0-.noarch.rpm
Plugins:

Authentication: LDAP,SSH
Authorization: Branch Write Protection,Group Manager,Path Write Protection
Information: Activity,Author Mapping,Landingpage
Library: CodeEditor,Expression Language,Issue Tracker,Mail
Source Code Management: Git,Subversion
Workflow: Archive,Direct Filelink,Editor,Notify,Push Event,Repository Mirror Plugin,Review,Webhook

#### Which operating system, browser and versions do you use?

Windows Chrome, TortoiseGit 2.13.0.1
#### Further information like screenshots

**Comment by fscholdei** [comment]
Thanks for sharing this issue. Unfortunately, I can't recreate the behavior on my end. Could you provide a test repo to investigate it further?
