### ISSUE TITLE
Ability to make changes to the code directly into the SCM-manager

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#208]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/208) by DekstrinG (Bitbucket: [DekstrinG](https://bitbucket.org/DekstrinG), ).**

----------------------------------------

I think it would be very useful.

**Comment by sdorra** [comment]
Version 2 has an editor plugin, which allows modifying files within the web ui.
