### ISSUE TITLE
Docker container still 2.33.1-SNAPSHOT

### ISSUE THREAD

**Issue by ThirtySomething** [scm-manager/scm-manager#2082]
## Issue description

Old version of SCM-Manager in Docker container.

#### Describe how to reproduce the bug

Allthough I can see on docker hub that the container got updates, the SCM-Manager reports still version SCM-Manager 2.33.1-SNAPSHOT. And inside on the administration page it points out that a new version 2.37 is available and offers a download link.

#### Describe your SCM-Manager setup

Running official docker container of SCM-Manager.

#### Which operating system, browser and versions do you use?

The docker host is a DIY NAS based on [OMV](https://www.openmediavault.org/).

#### Log of the bug

In the log file I don't find any hint about the running version.

#### Further information like screenshots

None.

**Comment by pfeuffer** [comment]
Hi, can you please use the image `scmmanager/scm-manager`? That's the official one, that gets updated regulary.

**Comment by ThirtySomething** [comment]
@pfeuffer thank you for the hint. Yes, I did the change and I've got the latest version 2.37.2.

**Comment by pfeuffer** [comment]
Thanks for the feedback 👍🏽
