### ISSUE TITLE
Allow disabling automatic session expiry

### ISSUE THREAD

**Issue by namandixit** [scm-manager/scm-manager#2083]
#### Problem to be solved

After some time, when logged in to SCM Manager, the session expires, forcing the user to log in again. There doesn't seem to be any option in Settings to disable this behaviour.

#### Proposed solution

An option can be provided in the Settings menu to set the timeout for session expiry, with a value of -1 meaning "Never Expire".

**Comment by christophloose** [comment]
Thank you @namandixit for your input! We will discuss your feature request and will come back to you soon

**Comment by christophloose** [comment]
Hi @namandixit we are planning to make your suggested function available in a config file of SCM-Manager. This feature will be probably part of our next release 2.39.

Stay tuned and thank you for patience!

**Comment by Bernhardvleen** [comment]
I am all for this feature, the current timeout is not very long and seems to be hard coded somewhere. 
+1

**Comment by codefox42** [comment]
To pick up on the "closing words" from the release notes:

> We would love to hear from you about what you need most!

_This_ (#2083) is something we are really missing.

**Comment by eheimbuch** [comment]
Hey, actually this feature was just released with version 2.46.0.

Find the documentation here: https://scm-manager.org/docs/2.46.x/en/administration/jwt-configuration/

**Comment by codefox42** [comment]
@eheimbuch, thank you very much! Is there also a way to configure the JWT's default expiration time?

**Comment by christophloose** [comment]
Hey @codefox42 
could you please point out your use case? Is this for a technical user? Or a standard user? Something different?

**Comment by codefox42** [comment]
Hello @christophloose, sure: this would be for a standard user who only access the web ui once or twice a day and currently feels that he/she needs to login _every time_ (of course, this feeling only comes from the fact that the last visit was more than an hour ago).

What we are interested in is a way to configure this period of time. If for each request a fresh token (with a new expiration time) is issued, a custom value of several hours would already have the effect that users only have to login once a day. A value of e.g. 24 hours would probably reduce the need to login for several days of consecutive usage, which would have a great boost regarding the user experience (at least for our users).

Although this was not the op's request, for us this would be a more favorable compromise between security and user experience than disabling the token expiration completely.

**Comment by codefox42** [comment]
Is that probably worth a _separate_ ticket?

**Comment by christophloose** [comment]
Hey @codefox42 absolutely, feel free to open a seperate ticket for a feature request :)
