### ISSUE TITLE
Domain scm-manger.org vanished

### ISSUE THREAD

**Issue by rac-HH** [scm-manager/scm-manager#2100]
## Issue description

The domain is no more resolveable.

#### Describe how to reproduce the bug

$ host -t ns org 9.9.9.9
Using domain server:
Name: 9.9.9.9
Address: 9.9.9.9#53
Aliases:

org name server d0.org.afilias-nst.org.
org name server a0.org.afilias-nst.info.
org name server a2.org.afilias-nst.info.
org name server c0.org.afilias-nst.info.
org name server b2.org.afilias-nst.org.
org name server b0.org.afilias-nst.org.
$ host -t ns scm-manager.org d0.org.afilias-nst.org
Using domain server:
Name: d0.org.afilias-nst.org
Address: 2001:500:f::1#53
Aliases:

**scm-manager.org has no NS record**

**Comment by pfeuffer** [comment]
Thanks for the hint! We are working on this.

**Comment by pfeuffer** [comment]
The domain should be back up again. We are sorry for the inconvenience!
