### ISSUE TITLE
Open TortoiseSVN links in SCM Manager

### ISSUE THREAD

**Issue by dervomsee** [scm-manager/scm-manager#2108]
## Issue description

TortoiseSVN has the feature to copy the SVN URL to a file to the clipboard (Rightclick --> TortoiseSVN --> Copy URL to clipboard).
When the URL is opened in a webbrowser the file will not be opened, because of a different URL structure.
* TortoiseSVN: http://server:port/scm/repo/NAMESPACE/REPONAME/PATH/FILENAME.txt
* SCM Webinterface: http://server:port/scm/repo/NAMESPACE/REPONAME/code/sources/REVISION/PATH/FILENAME.txt

The difference is the "code/sources" in the URL and the SVN revision.

## Proposed solution

Can the webinterface be modified to open/view TortoiseSVN links too or to forward them to the HEAD revision of a file/directory.

**Comment by eheimbuch** [comment]
Hey, sorry for the late response. This is not possible because we have predefined routes for our frontend urls. Even if you try to redirect via reverse proxy this will most likely fail.
