### ISSUE TITLE
Hide/show archived repositories

### ISSUE THREAD

**Issue by yoheie** [scm-manager/scm-manager#2148]
#### Problem to be solved

There are many repositories on my SCM-Manager instance, both active and archived.

I think it would be useful to have a way to exclude archived repositories from the list.

#### Proposed solution

Add a pattern to exclude archived repositories in the filter, or add a checkbox to hide/show archived repositories.

**Comment by yoheie** [comment]
With the release of SCM-Manager 2.41, "Show archived repositories" setting is added to the Landingpage Plugin, which is exactly what I wanted.
Thank you for your support.

**Comment by pfeuffer** [comment]
Thank you for the feedback 🙂
