### ISSUE TITLE
SVN externals

### ISSUE THREAD

**Issue by ThirtySomething** [scm-manager/scm-manager#2151]
## Issue description

It seems that there is no longer support of [SVN externals](https://svnbook.red-bean.com/en/1.7/svn.advanced.externals.html). 
During the checkout of a repository with an external on the server, the following message occurs:

The server at 'http://<Server IP>/svn/<Repository name>/trunk/<subfoler> does not support the HTTP/DAV protocol

#### Describe how to reproduce the bug

Create a SVN repository, add an external to a subfolder, do a checkout.

#### Describe your SCM-Manager setup

SCM Manager 2.39.1

#### Which operating system, browser and versions do you use?

Windows server

**Comment by ThirtySomething** [comment]
Hm, it looks like the reason for this is a misconfigured VPN connection. I'm sorry for the inconvenience.

**Comment by pfeuffer** [comment]
Nothing to be sorry for. Thanks for the quick resolution.
