### ISSUE TITLE
Externals (Svn) NOT loaded from the UI for scm-manager versions > 2.30.1

### ISSUE THREAD

**Issue by nikossakellariou** [scm-manager/scm-manager#2171]
## Issue description

externals doesn’t show as links on the scm-manager’s UI, under repository–>code
So that causes “Error: Not found The requested entity could not be found. It may have been deleted in another session.”

#### Describe how to reproduce the bug

1. create an svn repository named "test01"
2. create an svn repository named "test02"
3. checkout test01 
4. add svn:externals on "test01":
    right click on local folder-->TortoiseSVN-->Properties-->new-->externals-->new
    and add "test02" as external repo
![image](https://user-images.githubusercontent.com/110619326/224020821-3403a96e-fbee-413f-97cd-d262265f385c.png)

5. commit changes for "test01"
6. Navigate to  "test01" repository at scm-manager UI
7. Find the "error" under repository-->code section
![image](https://user-images.githubusercontent.com/110619326/224020264-6947c287-4609-4db5-bd7f-e60a7ad6d0ae.png)

### log message
DEBUG svnkit.fsfs - svn: E160013: Attempted to open non-existent child node ‘test02’
org.tmatesoft.svn.core.SVNException: svn: E160013: Attempted to open non-existent child node ‘test02’
```

**Comment by eheimbuch** [comment]
Thanks for the report. We will reproduce it by your instructions and try to fix it.

**Comment by nikossakellariou** [comment]
Thanks @eheimbuch for he quick reply!
Also, links for externals doesn't works "correctly", **if externals is a subdirectory of a repository.**
That's why, the way urls are produced for subfolders contain  for example "../code/sources/6/...".

So can we have "clean" URLS for subdirectories?
Is there a way το fix that? 

Testing on SCM-Manager 2.30.1

**Comment by eheimbuch** [comment]
![Screenshot from 2023-03-13 14-49-38](https://user-images.githubusercontent.com/50202942/224721391-b0ace5bf-55ca-4cd3-9d68-8ae4b1d21af2.png)

Hey, i reproduced your steps. Since i have no tortoise installed I edited the svn properties directly with `svn pe svn:externals . `

In the screenshot you can see how my `svn:externals` property look for the folder "external-folder". On the SCM-Manager UI there is a folder named "b" (my external). Clicking on the folder "b" gets me redirected to the actual repository "b".

Tested on a SCM-Manager instance with version 2.30.1.

Could you also try to set your externals manually? Also how does your externals look like in the properties? => `svn propget svn:externals`

**Comment by eheimbuch** [comment]
I am not sure what exactly you mean about "clean" url. The scm-manager ui is based on different frontend routes. Accessing your repository url redirects you to the code view, e.g. `/code/sources/`.

From my example external "b" leads me to `http://localhost:8080/scm/repo/scmadmin/b/code/sources/`. What would you expect instead?

**Comment by nikossakellariou** [comment]
Sorry, maybe wasn't clear the title: "Externals (Svn) NOT loaded from the UI for scm-manager versions > 2.30.1". 
I meant, i get the "error Not found" with the versions **grater** than 2.30.1
Its working for me too for version 2.30.1!!!

******about  the "clean" url**********
if a repository named "**admin/test01**" contains a folder named "**subfolder**"
and i want to checkout just the "subfolder" i must use this  url for ex.:
**http://localhost:8080/scm/repo/admin/test01/subfolder**
On the UI this url  will not redirect  με το the subfolder's location.
So if i add http://localhost:8080/scm/repo/admin/test01/subfolder as external. the link on the UI is useless.

**Comment by eheimbuch** [comment]
My bad. I got confused by your `Testing on SCM-Manager 2.30.1` in the last comment. I will have another look.

**Comment by eheimbuch** [comment]
Hey, we were able to reproduce this issue and can confirm that we have corrupted this part while implementing other features. We have already started to fix this and hopefully the patch should be included in our next release. Sorry for the inconvenience.

**Comment by nikossakellariou** [comment]
Thanks!
What about the condition that we want to add a subfolder, of a repository, as external. Is there i way that the external link can redirect directly to the subfolder on UI?

****How to reproduce  this issue

if a repository named "**admin/test01**" contains a folder named "**subfolder**" and i want to checkout just the "subfolder" i must use this url for ex.: **http://localhost:8080/scm/repo/admin/test01/subfolder**.
On the UI this url will not redirect me to the subfolder's location. 
So if i add http://localhost:8080/scm/repo/admin/test01/subfolder as external. the link on the UI is useless.

**Comment by eheimbuch** [comment]
FYI we fixed this bug: https://github.com/scm-manager/scm-manager/commit/796330f883bfdecfefd715e3ccd7fffb943efe34

It should be released right after the easter weekend.
