### ISSUE TITLE
If svn external link is a subfolder. the link redirects to empty page

### ISSUE THREAD

**Issue by nikossakellariou** [scm-manager/scm-manager#2172]
## Issue description

If svn external link is a subfolder. the link redirects to empty page

SCM-Manager is open source. If you have any knowledge of programming, maybe you can help. We would love to support you.

#### Describe how to reproduce the bug

1. Create two repositories "test01","test02"
2. Create a folder "subfolder" in test02
3. Add "subfolder" as svn external to test01
http://localhost:8080/scm/repo/admin/test02/subfolder test02/subfolder
4. Commit changes to test01
5. Navigate to test01 repository (http://localhost:8080/scm/repo/admin/test01/code/sources/)
![image](https://user-images.githubusercontent.com/110619326/233928826-35850ec2-5fab-4bb1-9afc-bb9d50af554b.png)
6. click "[test02/subfolder](http://localhost:8080/scm/repo/admin/test02/subfolder)"
7.  Redirects to empty page
![image](https://user-images.githubusercontent.com/110619326/233929099-81c60a09-47bc-4ec1-b950-14fb3687b9d4.png)

Is there a way that external links redirect to repositories subfolders?

#### Describe your SCM-Manager setup

SCM-Manager 2.43.0

**Comment by fscholdei** [comment]
Thank you for the report. Unfortunately, we had not combined the [link for sub directories](https://github.com/scm-manager/scm-manager/commit/217a2e155e9b02f60520fd1ef1e035cf0192290c) correctly in the frontend.
With the next release, the problem should be solved.
