### ISSUE TITLE
Debian/Ubuntu installation instructions outdated

### ISSUE THREAD

**Issue by dhs-rec** [scm-manager/scm-manager#2174]
Debian has deprecated `apt-key` and recommends storing keys in `/etc/apt/keyrings` or `/usr/share/keyrings` (if the keyring is managed by a package later-on), see [this Debian wiki article](https://wiki.debian.org/DebianRepository/UseThirdParty) for the details. `apt-get update` on Ubuntu 22.04 already emits warnings if keys are found in /etc/apt/trusted.gpg(.d), and so will Debian Bookworm.

Also, starting with the upcoming Debian Bookworm release, repository definitions will default to the s.c. `deb822` format (see `man sources.list`), which can also be used on older Debian releases as well.

This should all work going back to Debian Buster (maybe even Stretch), and its corresponding Ubuntu release.

**Comment by pfeuffer** [comment]
Thanks for this hint, @dhs-rec ! We will take a look at this.
