### ISSUE TITLE
external user permission error

### ISSUE THREAD

**Issue by JustAnotherRandomUsername** [scm-manager/scm-manager#2178]
Hello developers!

I have 2.44 scm-manager server with ldap plugin.
web interface shows error with permission overview of  ldap users.

I think this is a bug with groups membership.
when I manually remove all ldap groups for this user from ` /var/lib/scm/config/user-group-cache.xml`
then permission overview being works again.
![perm_overview_bug](https://github.com/scm-manager/scm-manager/assets/136494829/abed84f7-e7d9-4ca5-b720-42c3989058ff)

**Comment by pfeuffer** [comment]
Hey random user,

thanks a lot for this report! Could you do us a great favour and send us an excerpt of your log? Using the [support plugin](https://scm-manager.org/plugins/scm-support-plugin/) this is extremely easy. When this plugin is installed, you can find the menu item "Support" in the "Administration" section. Here you will find a "Start" button. Simply click this, then open the permission overview (potentially in another window) and then click "Stop and Collect". You will get a zip file containing some metadata about your server and the excerpt of the trace log. You could checkt, whether this contains any confidential data for you (for example usernames or repository names).

Thanks for your support!

René

**Comment by JustAnotherRandomUsername** [comment]
Hello
1) domain name was masked by #############
2) username was changed to my.privateusername (but holds format, it's mean the username contain one dot)

[8rThLjaWE3p.zip](https://github.com/scm-manager/scm-manager/files/11770737/8rThLjaWE3p.zip)

**Comment by pfeuffer** [comment]
Thank you very much, this is exactly what we need for a fix.

**Comment by pfeuffer** [comment]
Hey again, we found the bug and it will be fixed in the upcoming version. Thanks again for this report!
