### ISSUE TITLE
Subversion export is broken for certain repositories even health check complete successfully

### ISSUE THREAD

**Issue by ertankucukoglu** [scm-manager/scm-manager#2182]
## Issue description

I have more than 10 subversion repositories where SCM-Manager export generate a dump which is not importable by SCM-Manager itself or other alternative subversion tools. Health check runs OK on these repositories and there seems to be no other problem with them as far as I can tell. Even using Apache svnadmin command line tool successfully verified one of the repositories (I manually search and find the repository folder on disk).

#### Describe how to reproduce the bug
This does not happen on all repositories. Only a few.

- Go to relevant repository settings page and click create a new export button.
- Download dump ZIP file.
- Go to Repositories, click add repository, click import repository.
- Select subversion and choose newly downloaded ZIP file. Make sure compressed is checked
- Type a random valid repository name
- Click import button.

This gives me `Error Code 8LRncum0S1`

#### Describe your SCM-Manager setup
I am using SCM-Manager 2.42.2 running on a Windows 2022 server. There is no installed plugin. Server access is direct. Eclipse Adoptium jdk-17.0.7.7-hotspot 64bit.

#### Which operating system, browser and versions do you use?
My client is Windows 11, Browser is Opera 99.0.4788.65

#### Log of the bug
I can provide a sample repository dump data and direct ZIP of the raw repository itself upon request using alternative direct channels. There is one small repository around 400KB in ZIP size. Raw size is about 250KB.

**Comment by pfeuffer** [comment]
Hi,

thanks for your report, we would love to take a look at it.
You can send your data by mail to support@scm-manager.org

Regards
René

**Comment by eheimbuch** [comment]
We found the error. Now we are looking for the cause on your side. Could you please describe your server and which encoding is currently set?

```
Caused by: org.tmatesoft.svn.core.SVNException: svn: E140001: Dump stream contains a malformed header (with no ':') at 'PROPS-END'
        at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:70)
        at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:57)
        at org.tmatesoft.svn.core.internal.wc.SVNDumpStreamParser.readHeaderBlock(SVNDumpStreamParser.java:366)
        at org.tmatesoft.svn.core.internal.wc.SVNDumpStreamParser.parseDumpStream(SVNDumpStreamParser.java:91)
        at org.tmatesoft.svn.core.wc.admin.SVNAdminClient.doLoad(SVNAdminClient.java:1089)
        at org.tmatesoft.svn.core.wc.admin.SVNAdminClient.doLoad(SVNAdminClient.java:1050)
        at sonia.scm.repository.spi.SvnUnbundleCommand.restore(SvnUnbundleCommand.java:119)
        at sonia.scm.repository.spi.SvnUnbundleCommand.unbundle(SvnUnbundleCommand.java:91)
        ... 123 common frames omitted
```

**Comment by ertankucukoglu** [comment]
It is a Windows 2022 64bit server. Encoding details are as following

```
PS C:\Users\Administrator\Desktop> [System.Text.Encoding]::Default

IsSingleByte      : True
BodyName          : iso-8859-1
EncodingName      : Western European (Windows)
HeaderName        : Windows-1252
WebName           : Windows-1252
WindowsCodePage   : 1252
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 1252

PS C:\Users\Administrator\Desktop>
```

**Comment by eheimbuch** [comment]
You dump files contains bad characters (non ascii), which seems to be the cause.

![Screenshot from 2023-06-28 10-42-34](https://github.com/scm-manager/scm-manager/assets/50202942/6044d7e4-1930-472f-9cc9-720bd99a96ae)

**Comment by ertankucukoglu** [comment]
Other repositories on same SCM-Manager server can be dumped and imported by SCM-Manager itself just fine. Only about 10+ repositories have this problem.

These dump files I shared are created using SCM-Manager. Using `svnadmin` command line tool I can validate repository or I can have importable repository dump of very same repository.

However, `svnadmin` command line should use `--file` option in order for it to build correct dump file. Using `>`  for output redirection yields to broken dumps.

Since verify complete successfully and `svnadmin` dumps are importable by SCM-Manager on identical computer, I take it there is a problem with SCM-Manager export under certain circumstances.

**Comment by eheimbuch** [comment]
Thanks for the clarification. We will take your repository and try to find the issue. Since we are currently working on other tasks it could take some time.

**Comment by pfeuffer** [comment]
Hi @ertankucukoglu ,

the thing with this is, there is not much magic on our side: We use SVNKit for all root svn actions. More precisely, we use the SVNAdminClient, and there are not much options for dump and load operations.
I wrote a simple java test class that just creates a dump of the repository you provided and tries to load it again. We see the same error here (E140001: Dump stream contains a malformed header (with no ':') at 'PROPS-END').
If you could create a minimal repository without production data that produces this error, we could try to create an issue for SVNKit.

Regards
René

**Comment by ertankucukoglu** [comment]
Hi,

Thank you for checking this issue.

I do not know what actually triggers the problem. It is fine that you share the sample repository you have.

Regards,
Ertan Küçükoğlu
