### ISSUE TITLE
Enhance URL Redirection for User-friendly Access to SVN Files

### ISSUE THREAD

**Issue by dorbeus** [scm-manager/scm-manager#2193]
Issue Description:

When a user accesses a URL like https://svn.company.com/scm/repo/svn/REPO/trunk/important.docx, they're directed to an empty page within the repository, which isn't very intuitive or user-friendly, especially for those who aren't deeply familiar with SVN.

Expected Behavior:

I suggest implementing an automatic redirect from URLs formatted like:
```
https://svn.company.com/scm/repo/svn/REPO/trunk/[filename]
```
to either:

1. A direct file download, or
2. The respective web interface page, e.g.:
```
https://svn.company.com/scm/repo/svn/REPO/code/sources/[revision-number]/trunk/[filename]
```

This would provide a more seamless and intuitive user experience, making the repository more accessible for non-SVN experts.

Steps to Reproduce:

1. Navigate to https://svn.company.com/scm/repo/svn/REPO/trunk/important.docx.
2. Notice that it redirects to an empty page within the repository.

Additional Information:

Having a direct and user-friendly URL scheme can significantly enhance the usability of our SVN for a broader range of users, reducing confusion and streamlining access.

**Comment by christophloose** [comment]
Hi @dorbeus 
thank you for your suggestions! We will discuss it.

**Comment by dorbeus** [comment]
I have implemented the functionality using an nginx reverse proxy.
This solution rewrites the request URL based on the `http_user_agent`. if the 'http_user_agent' contains the substring 'svn' I assume the request is from an SVN client, otherwise i assume it is a browser.
Don't know if this is universally correct, but it works in my environment. 
Ideally, this function should be incorporated directly in the scm-manager application itself.

```
  default.conf: |
    rewrite_log on;
    server {
      listen 80;
      server_name _;

      error_log /dev/stdout info;

      location ~ ^/scm/repo/svn/([^/]+)(?!/code/sources/)(/.*)?$ {
        if ( $http_user_agent !~* 'svn' ) {
          rewrite ^/scm/repo/svn/([^/]+)(?!/code/sources/)(/.*)?$ https://$host/scm/repo/svn/$1/code/sources/-1$2;
        }
        
        proxy_pass http://scm-manager;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
      
      location /   {
        proxy_pass http://scm-manager;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
```

**Comment by pfeuffer** [comment]
This is an interesting idea! Thanks for your suggestion.

**Comment by Pilopa** [comment]
Hi @dorbeus, our team take due dilligence reviewing every issue presented to us. Unfortunately, after careful consideration and due to the complexity of the solution given the url architecture of SCMM 2+, we have decided as a team to assign this issue a low priority. That means we will not solve it in the near future. You can still approach @christophloose directly if you would like to request a quote to get this work done on commission.
