### ISSUE TITLE
Increasing number of projects shown on Repositories page

### ISSUE THREAD

**Issue by mfide** [scm-manager/scm-manager#2195]
Hello,

I have installed SCM Manager v2.46.1 using docker. It works fine.

I wonder if it is possible increase the number of projects shown on Repositories page at a time?

Thank you.

**Comment by pfeuffer** [comment]
Hi @mfide ,

the landing page plugin is what you are looking for. There you will find a settings icon on the right side of the "mySCM" heading where you can select the views you want to have on your landing page as well as the preferred number of repositories.

![image](https://github.com/scm-manager/scm-manager/assets/281097/76125f49-8289-4dcd-93d7-4b864ad545c3)

Hope this is what you are looking for.

René

**Comment by mfide** [comment]
> Hi @mfide ,
> 
> the landing page plugin is what you are looking for. There you will find a settings icon on the right side of the "mySCM" heading where you can select the views you want to have on your landing page as well as the preferred number of repositories.
> 
> ![image](https://user-images.githubusercontent.com/281097/266826179-76125f49-8289-4dcd-93d7-4b864ad545c3.png)
> 
> Hope this is what you are looking for.
> 
> René


This is exactly what I look for. It solved my problem. Thank you.
