### ISSUE TITLE
Port the scm-hgnested-plugin to 2.x

### ISSUE THREAD

**Issue by mharbison72** [scm-manager/scm-manager#2197]
## Issue description

The hgnested plugin was used to support Mercurial subrepositories in 1.x, but isn't available in 2.x.  I [mentioned it](https://groups.google.com/g/scmmanager/c/HbfT6tgiPWQ/m/3SbshvXfBAAJ) awhile ago in the old google groups forum, but that's been decommissioned, so I didn't want this to get lost.  I can dig up a link to the old BitBucket repo that's archived on the Software Heritage Archive website, if needed.

#### Problem to be solved

We need a way to push to various parent repositories, and have any changes to the subrepositories immediately visible to any other parent repos that reference the subrepo.

#### Proposed solution

The plugin had a tab UI element in the parent repository that allowed mapping a URI to a known repository that is the subrepo, and then sent a 3xx redirect to the actual subrepo URL when it got a request for ${parent_url} + URI.  That's sufficient, but if you want to improve the implementation, I'd suggest having the subrepo stored wherever you want to, and then use the Mercurial `share` extension to share the subrepo into the proper place under the parent repo.  That has the advantage of:

1) No 3xx redirect needed
1) The parent repo in the filesystem is well-formed (i.e. the subrepo is nested under the parent as Mercurial expects), so filesystem commands like `hg verify` work in maintenance scripts, or could be added to the UI as a feature
1) Repo shares are a ~0 byte way to redirect Mercurial elsewhere like a symlink would, but it works on Windows too
 
I'm happy to help discuss/test/review or offer Mercurial expertise, but I can't do it myself because I don't understand the UI side of things here.

**Comment by christophloose** [comment]
@mharbison72 thank you for your patience and your suggestion.

From our perspective it would be easy to port the old nested plugin to SCM-Manager 3.x. Your suggestion is interesting and could you please tell us more about your use case? Thanks in advance.

**Comment by mharbison72** [comment]
@christophloose sorry for the delay- the use case is simply that if multiple top level repositories reference a subrepo (say of header files), the 1.x plugin allowed configuring the server such that pushing from either top level repo made changes to the subrepo immediately visible to the other top level repo if someone pulled and updated from that.  If the subrepo stays nested in the top level repo (as is customary) on the server, then pushing changes to top-level-repo1 would not be visible when pulling from top-level-repo2 without some other server side synchronization, which is a lot more work.  (I'm also not sure that the nested subrepo would be created with a push if it didn't exist, and the subrepo plugin is missing.  So best case scenario, that works and you get the undesired subrepo copies, worst case scenario it doesn't work and the push simply fails.)

While the 1.x plugin was sufficient to accomplish this, having the subrepo outside the top level repo makes it not well formed from a Mercurial point of view.  So if I have a nightly cron job on the server that runs `hg verify`, it would spew errors because the subrepo that it expects to be present in the filesystem, isn't.  The sharing trick would keep both command line Mercurial and SCM manager happy.

**Comment by lgorzitze** [comment]
Hello @mharbison72 ,
we checked your proposal and unfortunately, implementing your suggestion is currently not affordable. 
Although the subrepo is not visible in the source view of SCMM, the possibility to connect a subrepo to a top-level-repo via the .hgsub file (e.g. `nested = https://your-scm.repo/..`) should work with SCMM v2.x and 3.x. Would this option be sufficient for you?

**Comment by lgorzitze** [comment]
Hi @mharbison72,

Thank you for the insight. I may have expressed myself somewhat misleadingly. The proposal you mentioned regarding the Mercurial `share` extension is currently not feasible for us to implement, but we are working on the port of the 1.x hgnested-plugin.

**Comment by lgorzitze** [comment]
Hi @mharbison72 ,

the port of the hgnested-plugin is now completed. The plugin is available for SCMM as of v3.2.2. You can check out our [website ](https://scm-manager.org/plugins/scm-hgnested-plugin/) for more information about the plugin. Thank you for your patience.

**Comment by lgorzitze** [comment]
Hi @mharbison72,

Unfortunately, we do not currently have the resources to check whether and how an integration of the hg share extension into the SCMM is possible. If you would like to try this yourself, you are more than welcome to do so. We would appreciate the effort!
