### ISSUE TITLE
When a user is deleted, it is not deleted from the groups it was a member of

### ISSUE THREAD

**Issue by dervomsee** [scm-manager/scm-manager#2198]
## Issue description

When a user is deleted, it is not deleted from the groups it was a member of.

#### Describe how to reproduce the bug

I created a user 'test', added the user to a group. When the user user gets deleted, The user stiff exists in the group.
When clicking on the non-existent user, the following error message appears:
![grafik](https://github.com/scm-manager/scm-manager/assets/1233864/ee6f358b-1f03-4803-bc5c-6a18269a96f0)

#### Describe your SCM-Manager setup

* SCM version 2.47.0
* Caddy server reverse proxy
* SCM in the scmmanager/scm-manager docker container on a Ubuntu host

#### Which operating system, browser and versions do you use?

Windows, Firefox 119

#### Log of the bug

No log entry appears

**Comment by pfeuffer** [comment]
Hi @dervomsee , thanks for this report. In SCM-Manager, groups are designed to also accept user names, that have not (maybe yet) been created in SCM-Manager. The reason for this is, that a user may also log in using external systems (LDAP, CAS). In this case, an administrator can create and manage the groups although the user has not been logged in before and therefore is not known to SCM-Manager.

You are definitely right though, that in such a case a click on such a user must not lead you to an error page. Therefore thanks again, we will fix that.
