### ISSUE TITLE
Change number display changeset

### ISSUE THREAD

**Issue by nikobcs** [scm-manager/scm-manager#2202]
Good afternoon.

Please advise.
We updated from SCM-manager 1.60 to 2.48.3 and noticed that now the changeset number is displayed differently: it was changeset 5231:0ef3703b423c, but became 0ef3703.
Is it possible to change this setting?

![mc](https://github.com/scm-manager/scm-manager/assets/157552146/4e131e40-7a15-4467-8333-b59a5a67000a)
![image-2024-01-24-04-20-13-948](https://github.com/scm-manager/scm-manager/assets/157552146/91fac7c8-d689-4da8-8a6b-9c4cb5731655)
![sn](https://github.com/scm-manager/scm-manager/assets/157552146/e1d48ed9-3c0c-4fb5-b601-c69c376a671a)

**Comment by pfeuffer** [comment]
Hi @nikobcs ,

the counter you are missing is a number, that differs from instance to instance of a single repository. So number 42 on your PC could be number 23 on the server. Therefore we did not think that this would be of great value (and currently this cannot be configured). I'd be interested in the use case you would like to have this number for.

Thanks
René

**Comment by nikobcs** [comment]
Hi @pfeuffer,
It’s not entirely clear why the version number can be different on the server and on the client?

Very complex (however reproduceable) calculations.
At some moment we see difference in results.
Problem: find the commit leaded to such change in result to juge for correctness
Our solution (aka bisection):
•	sync to some old revisision, reproduce "old" result.
•	sync to head. reproduce "new" result.
•	sync to "midpoint". get result. If result is same as "old" – continue to search in upper (newer) halve, otherwise continue to search in lower (older) halve.
Running sequence of Revision is very convinient for such bisect algorithm. 
Of course the procedure could be automated, however it is not an easy task because of infrastructure.

**Comment by pfeuffer** [comment]
Hi @nikobcs ,

I know this feature from Git and I love it. And as far as I get it, there is no need to change the way you are working in a relevant way. The only important point you need to consider is, that revision numbers are not necessarily the same for revisions on all clones. See this excerpt from the [hg documentation](https://www.mercurial-scm.org/doc/hg.1.html):
![image](https://github.com/scm-manager/scm-manager/assets/281097/36ed0707-b47f-4ed2-9511-c648c572a28c)

So, your workflow must not rely on the revision number, though you can use it to iterate the commits in your clone. To later identify a revision, you always have to use the hash code.

Hope this helps :-)
René

**Comment by nikobcs** [comment]
I understand. Thank you for your help!
Have a good day!
