### ISSUE TITLE
SCM-Manager hosting using https proxy broken after 3.0.0 upgrade

### ISSUE THREAD

**Issue by ckeydel** [scm-manager/scm-manager#2203]
## Issue description

When SCM-Manager runs serving http without SSL behind a https proxy such as Apache or nginx, the loading of the web page doesn't complete. Instead, it shows three spinning circles with the text "loading plugin information".

#### Describe how to reproduce the bug

Running SCM-Manager in default configuration. A https proxy is set up to serve it to the Internet.

#### Describe your SCM-Manager setup

SCM-Manager running fine serving port 32180. Ubuntu 22.4 LTS server with Plesk, using nginx to host SCM-Manager as a proxy. Nginx proxy set up as follows:

```
location /scm {
	proxy_set_header X-Real-IP         $remote_addr;
	proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header Host $http_host;
	proxy_pass       http://localhost:32180;
}
```

Version 3.0.0 of SCM-Manager, upgraded from the last 2.x version through apt.

#### Which operating system, browser and versions do you use?

Any.

#### Further information like screenshots

See also the community bug report at
https://community.cloudogu.com/t/scm-manager-hosting-via-nginx-proxy-broken-after-3-0-0-upgrade

**Comment by dervomsee** [comment]
Have you tried to the the config variable `forwardHeadersEnabled` to true? I had the same issue and `forwardHeadersEnabled: true` solved it.
https://github.com/scm-manager/scm-manager/blob/d8081ed07427903d27649f03ea8e3c09d704cd92/scm-packaging/docker/src/main/fs/etc/scm/config.yml#L7C1-L8C29
```
 ## Evaluates headers set by a reverse proxy like X-Forwarded-For, X-Forwarded-Proto and X-Forwarded-Host
forwardHeadersEnabled: false
```

**Comment by ckeydel** [comment]
That fixed it - thanks!

**Comment by mfide** [comment]
Hello,

I upgraded my docker instant today and end-up with the same issue.
I have to attach to docker container , and modify the /**etc/scm/config.yml** (change as forwardHeadersEnabled: true) to fix the issue.

Is there a way to fix it permanently so that I don't need manual modification each time I update the docker container?

Thank you.

**Comment by dervomsee** [comment]
In my installation, I'm binding a local directory to the container's /etc/scm. This gives me persistence in the /etc/scm/ directory.
The volumes part of my docker-compose.yml is like this:
```
...
    volumes:
      - ./data/scmhome:/var/lib/scm
      - ./data/scmetc:/etc/scm
...
```

**Comment by mfide** [comment]
> In my installation, I'm binding a local directory to the container's /etc/scm. This gives me persistence in the /etc/scm/ directory. The volumes part of my docker-compose.yml is like this:
> 
> ```
> ...
>     volumes:
>       - ./data/scmhome:/var/lib/scm
>       - ./data/scmetc:/etc/scm
> ...
> ```

This indeed works. Thank you for the suggestion. But what if they introduce some new entries in config.yml with the new version of the SCM? In that case new entries will be missing in my previously generated config.yml.

I would prefer to change forwardHeadersEnabled to true only in the docker-compose.yml somehow and keep the rest default. For example like an environment variable definition. I have tried to following but it seems it is ignored:

```
..
    environment:
      SCM_FORWARDHEADERSENABLED: true
..

```
