### ISSUE TITLE
Latest Tag goes from 3.0.3 to 2.46.2 and docker hub scmmanager/scm-manager:latest has followed

### ISSUE THREAD

**Issue by SirRufo** [scm-manager/scm-manager#2206]
Did I miss something?

The latest version on [docker](https://hub.docker.com/r/scmmanager/scm-manager/tags) is now **2.46.2** and was before **3.0.3**.

That equals the [tag history here](https://github.com/scm-manager/scm-manager/tags).

Maybe there is a reason, but then you have to explain it to me

**Comment by pfeuffer** [comment]
Oh, you're right, that's not correct.

We had to release a fix for 2.46.x, but that should not have pushed the 'latest' tag on docker. That's a bug in our release pipeline.

Thanks for the report, we will fix this.

**Comment by pfeuffer** [comment]
To fix the current `latest` tag, I've just released version 3.0.4 of SCM-Manager with some minor bug fixes.
