### ISSUE TITLE
Docker compose environment definition for forwardHeadersEnabled

### ISSUE THREAD

**Issue by mfide** [scm-manager/scm-manager#2207]
Regarding to the discussion here: [here](https://github.com/scm-manager/scm-manager/issues/2203)
And information provided here: [here](https://scm-manager.org/docs/latest/en/administration/scm-server/)

Is it possible to tailor default value of `forwardHeadersEnabled` in the docker compose file directly something like below:

```
..
    environment:
      SCM_FORWARD_HEADERS_ENABLED: true
..
```

**Comment by pfeuffer** [comment]
This sounds like a reasonable request. We will check this. Thanks for the suggestion!

**Comment by mfide** [comment]
> Hello @mfide,
> 
> this is already possible by using this snippet inside your docker-compose.yaml File
> 
> ```yaml
> environment:
>   - SCM_FORWARD_HEADERS_ENABLED=true
> ```

Did you test that?
For me it is always ignored and config.yml produced in /etc/scm looks like following:

```
..
## Evaluates headers set by a reverse proxy like X-Forwarded-For, X-Forwarded-Proto and X-Forwarded-Host
forwardHeadersEnabled: false
..

```

**Comment by mfide** [comment]
Hi @zT-1337,

I have created a new instance using following docker-compose.yml in my test folder:

```
version: '3'

services:
  scm:
    image: scmmanager/scm-manager:3.1.0
    environment:
      - SCM_FORWARD_HEADERS_ENABLED=true
```

Running the container:
```
mf@myserver:~/test$ docker compose up -d
WARN[0000] /home/mf/test/docker-compose.yml: `version` is obsolete
[+] Running 1/1
 ✔ scm Pulled                                                                                                                                                                                                                       0.6s
[+] Running 2/2
 ✔ Network test_default  Created                                                                                                                                                                                                    0.1s
 ✔ Container test-scm-1  Started  
```

Check status:
```
mf@myserver:~/test$ docker compose ps
WARN[0000] /home/mf/test/docker-compose.yml: `version` is obsolete
NAME         IMAGE                          COMMAND                  SERVICE   CREATED          STATUS                    PORTS
test-scm-1   scmmanager/scm-manager:3.1.0   "/opt/scm-server/bin…"   scm       38 seconds ago   Up 37 seconds (healthy)   8080/tcp
```

Attach to container's bash:
```
mf@myserver:~/test$ docker exec -it test-scm-1 /bin/sh
/opt/scm-server $
/opt/scm-server $ cd /etc/scm/
/etc/scm $
/etc/scm $
```

Print config.yml produced:
```
etc/scm $ cat config.yml
# base server config
##  Address to listen 0.0.0.0 means on every interface
addressBinding: 0.0.0.0
port: 8080
contextPath: /scm

## Evaluates headers set by a reverse proxy like X-Forwarded-For, X-Forwarded-Proto and X-Forwarded-Host
forwardHeadersEnabled: false         <----------------------------- here it is still false

## increase http header size for mercurial
httpHeaderSize: 16384

## set http idle timeout (set to 0 for default)
idleTimeout: 0

# ssl config - ssl is only evaluated if key store path is set
## path to your cert file
https:
  keyStorePath: ""
  keyStorePassword: secret
  keyStoreType: PKCS12
  sslPort: 8443
  redirectHttpToHttps: false

tempDir: /var/cache/scm/work

# logging
log:
  rootLevel: WARN
  enableFileAppender: false
  enableConsoleAppender: true
  logger:
    sonia.scm: INFO
    com.cloudogu.scm: INFO

# webapp config
webapp:
  ## Sets explicit working directory for internal processes, empty means default java temp dir
  workDir:
  ## Home directory "scm-home" which is also set for classpath
  homeDir: /var/lib/scm
  cache:
    dataFile:
      enabled: true
    store:
      enabled: true
  ## Warning: Enabling this option can lead to security issue.
  endlessJwt: false
  ## Number of async threads
  asyncThreads: 4
  ## Max seconds to abort async execution
  maxAsyncAbortSeconds: 60
  ## Amount of central work queue workers
  centralWorkQueue:
    workers: 4
  ## Strategy for the working copy pool implementation [sonia.scm.repository.work.NoneCachingWorkingCopyPool, sonia.scm.repository.work.SimpleCachingWorkingCopyPool]
  workingCopyPoolStrategy: sonia.scm.repository.work.SimpleCachingWorkingCopyPool
  ## Amount of "cached" working copies
  workingCopyPoolSize: 5
/etc/scm $
```

**Comment by zT-1337** [comment]
> I tested it with the SCM-Manager 3.1.0. Configuration provided as environment variables override the configuration provided by the config.yml. But they do not change the values inside the config.yml.

The values inside the config.yml is not supposed to be changed, by environment variables. But you can override the behavior, configured by the config.yml, by using the environment variables.

**Comment by mfide** [comment]
> > I tested it with the SCM-Manager 3.1.0. Configuration provided as environment variables override the configuration provided by the config.yml. But they do not change the values inside the config.yml.
> 
> The values inside the config.yml is not supposed to be changed, by environment variables. But you can override the behavior, configured by the config.yml, by using the environment variables.

Yes you are right.

I confirmed that config.yml in the container still has "forwardHeadersEnabled: false" item but "SCM_FORWARD_HEADERS_ENABLED=true" in the environment section overrides the behaviour of the container and it behaves as expected.

Thank you for your help.
