### ISSUE TITLE
I have found a issue in SCM-Manager Plugin error please help me to resolve the issue

### ISSUE THREAD

**Issue by SapphireIT** [scm-manager/scm-manager#2208]
Hello,

We are using SCM-Manager and some times our service gets slow. At that time, we restarted the SCM service and it is running properly but yesterday we had same issue and i restarted the SCM service After that, we faced some plugin issue. I have attached a screenshot of it; please check and do needful for the same.

![image](https://github.com/scm-manager/scm-manager/assets/168512216/07cec8b8-aaf9-427e-a36f-0c022b0ab03f)

I have also shared the SCM-Manager logs for further checking purposes. Please check the attached file below.
[scm-manager.log](https://github.com/scm-manager/scm-manager/files/15158719/scm-manager.log)

**Comment by pfeuffer** [comment]
Hi @SapphireIT ,

I'm nearly six years here at SCM-Manager, but this exception is totally new to me. It looks like your deployment got skewed. When the server is started, it writes a directory called `WEB-INF` (the location for this is configured in the server configuration), and in this you should find another folder `plugins` with a file called `plugin-index.xml`. The server can no longer find this file. Either the director has been changed in your server configuration or the file somehow got deleted (though it should be writted anew when the server ist started again).

How this can be fixed depends on your setup (Linux or Windows, installation type and so on). Depending on your configuration, a fresh installation might be the quickest fix.

Regards
René

**Comment by SapphireIT** [comment]
Hello Rene,

We are Installed the SCM in Windows server -2012 Server.

**Comment by SapphireIT** [comment]
Hello Rene,

As per your suggestion, I have checked and all the plugin files are as they are, so why is this happening? kindly do needful as soon as possible.

**Comment by SapphireIT** [comment]
Hello christophloose,

Our issue is resolved now one plugin has an issue, we removed the plugin and our issue is resolved

**Comment by pfeuffer** [comment]
Ah, glad to hear this. Thanks for the update!

Just out of curiosity: Can you tell us which plugin has caused the issue and how this was installed? This should not happen.
