### ISSUE TITLE
Mirror Tags are always gray

### ISSUE THREAD

**Issue by docbacardi** [scm-manager/scm-manager#2209]
I'm using the "Repository Mirror" plugin for several external repositories. The synchronization works like a charm, only the "mirror" tag in the repository list is always gray. The documentation [here](https://scm-manager.org/plugins/scm-repository-mirror-plugin/docs/2.4.x/en/create/) suggests that a successful sync is marked with a green tag:

> Mirrored repositories are marked with a Mirror tag. A gray tag indicates the ongoing first synchronization with the external source.
> If the data synchronization was successful, the tag is green. A red tag indicates errors during the synchronization.
> If branches or tags were rejected due to a configured filter (other than the name patterns), it is yellow.

All of my mirrors were successfully synchronized as the repository data and the mirror log shows. The tool tip of the "mirror" tags says "Last synchronization successful", but the color is gray:
 
![scmv3_mirror_tag_with_tooltip](https://github.com/scm-manager/scm-manager/assets/7099784/3151d0ee-e7de-4c64-b613-7deab3758454)

Tests were done with Firefox 125.0.3 and Chromium 124.0.6367.91, both running on Ubuntu 22.04 LTS. The screenshot shows the dark theme, but the problem occurs with all themes.

I'm using SCM Manager v3.1.0 on Ubuntu x86_64 20.04LTS with Java 17. The "Repository Mirror" plugin is v2.4.2 . The SCM Manager is started as a systemd service with the provided script "bin/scm-server".

**Comment by pfeuffer** [comment]
Thanks for the hint. Indeed, this looks strange. We will check this.

**Comment by fscholdei** [comment]
The fix should be available with the next release probably by end of the month.

**Comment by docbacardi** [comment]
Just updated to v3.2.0 but the icons are still gray. All plugins are up to date. A refresh of a mirror repository after the update did not change anything.

My HTML/CSS skills are about tourist level, so this is just a wild guess: does ```color="success"``` really have some effect:
![scm_manager_mirror_icons_02](https://github.com/scm-manager/scm-manager/assets/7099784/55b22928-32a1-4a62-9958-962d44a361a7)

**Comment by christophloose** [comment]
@docbacardi due to quality improvements we delayed the plugin release of the mirror plugin until next week.

**Comment by docbacardi** [comment]
Back from holidays, updated to v3.2.1 and the mirror tags are colorful.
Thanks for the help!
