### ISSUE TITLE
Not possible to change the SCM_HOME directory on Windows

### ISSUE THREAD

**Issue by vruss** [scm-manager/scm-manager#2213]
## Issue description

I'm trying to change the `SCM_HOME` directory on Windows to be `C:\SCM-Manager` but it doesn't work.

#### Describe how to reproduce the bug

Turn off the service.

Copy existing data from %APPDATA%/Roaming/SCM-Manager to the new location.

Open the `scm-server.xml` and add `<env name="SCM_HOME" value="C:\SCM-Manager" />`  as shown here: https://scm-manager.org/docs/3.2.x/en/installation/windows/

Also, add SCM_HOME to the Windows System Environment Variables.

Restart PC and service

See that you are greeted with a first setup and any plugins installed will still be installed in the old location.

#### Describe your SCM-Manager setup

Windows Server with default SCM server configuration except for what I described above.

#### Which operating system, browser and versions do you use?

Windows Server.

#### Log of the bug

Couldn't find any relevant logs

**Comment by eheimbuch** [comment]
Hey, it seems that your configuration is broken? If you have version 3.2 running on your scm-server the old config format known as `scm-server.xml` is not longer supported. You must use the new `config.yml` instead. There you can set the home dir and all other settings regarding your server. Please read the docs [here](https://scm-manager.org/docs/3.2.x/en/administration/scm-server).

Hope this helps.
Eduard

**Comment by vruss** [comment]
Hm that's odd. I followed the installation instructions:

1. Download the Windows installer from here: https://scm-manager.org/download#windows which is 3.2.0
2. Installed the latest LTS version of OpenJDK
3. Ran `scm-server.exe install`
4. Ran `scm-server.exe start`

So maybe there's a bug with that one? Looking at the files I have installed it looks like the 3.2.0 folder contained the 2.10 version

![image](https://github.com/scm-manager/scm-manager/assets/10886082/c0ba8437-387a-45ce-abe8-494b1fd15df3)

![image](https://github.com/scm-manager/scm-manager/assets/10886082/cda090ab-d14c-4859-ac21-6a21131700cb)

**Comment by vruss** [comment]
The guide on this page only mentions the old `scm-server.xml`

**Comment by vruss** [comment]
I still think me changing the system environment variable should have made a difference. Changing the yaml file fixed the issue

**Comment by christophloose** [comment]
> Hm that's odd. I followed the installation instructions:
> 
> 1. Download the Windows installer from here: https://scm-manager.org/download#windows which is 3.2.0
> 2. Installed the latest LTS version of OpenJDK
> 3. Ran `scm-server.exe install`
> 4. Ran `scm-server.exe start`
> 
> So maybe there's a bug with that one? Looking at the files I have installed it looks like the 3.2.0 folder contained the 2.10 version
> 
> ![image](https://private-user-images.githubusercontent.com/10886082/334031141-c0ba8437-387a-45ce-abe8-494b1fd15df3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODA0OTYsIm5iZiI6MTcxNjg4MDE5NiwicGF0aCI6Ii8xMDg4NjA4Mi8zMzQwMzExNDEtYzBiYTg0MzctMzg3YS00NWNlLWFiZTgtNDk0YjFmZDE1ZGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA3MDk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNmM4ZmY4OTBlMjJmYmE3OWIxNTU5NWQzODJjZWYzNDcyNDcwMTQ3ODc3YTg4Mjc0NDBlMmU0Y2I0OGQ1NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1tA2nbAHgCJn6trS4BZqJckWt7QsNZTYmmMJm9uRbv0)
> 
> ![image](https://private-user-images.githubusercontent.com/10886082/334030996-cda090ab-d14c-4859-ac21-6a21131700cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODA0OTYsIm5iZiI6MTcxNjg4MDE5NiwicGF0aCI6Ii8xMDg4NjA4Mi8zMzQwMzA5OTYtY2RhMDkwYWItZDE0Yy00ODU5LWFjMjEtNmEyMTEzMTcwMGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA3MDk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNDQ4ODA2ZjU0OGI4MmUzNjQwZDY3OWVmZDhkZTdkMjkzMmI5ZGM4OWVhNDc4ODZjODM5MzgwODY0ZTI0NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7JyiqwDtNTylxUHMt6XhG6rDaLAhalV69KYr05GejY8)

This is only the windows service that we are using and it's not the version number of the SCM-Manager.
Happy to hear that you found a solution!

We will have a look at the windwos installation manual. Thank you for the hint.
