### ISSUE TITLE
Update SVNKit

### ISSUE THREAD

**Issue by AnhTuWally** [scm-manager/scm-manager#2216]
## Issue description

The SVNKit used in SCM-Manager is quite outdated. This result in issue with the SVN Repo created by SVM-Manager to be on an older version of SVN (v 1.6). 

I was trying to do SVN sync with a repo hosted with SVN repo using v1.10 and it failed. I suspected that this was because of the SVN version 1.6 was not compatible to sync with SVN repo v1.10. 

A Quick Fix that I did was to use `svnadmin upgrade [REPO_PATH]` to upgrade the repo from SCM-Manager to using SVN 1.10 instead of the default SVN v 1.6. 

I'm quite unsure how stable it is for the SCM-Manger's SVNKit to manage and serve SVN Repo v 1.10. 

### Feature Request

It would be awesome if the SVNKit used by SCM-Manager is updated to the current latest version so that SCM-Manager can fully support SVN-repo with higher version. 

#### Problem to be solved

Compatibility issue with SVN version

#### Proposed solution

Update SM-Manager SVNKit to a newer version.

**Comment by fscholdei** [comment]
Hey AnhTuWally,

thank you for the feature request. We will take a closer look.

Regards, Florian

**Comment by pfeuffer** [comment]
Hi @AnhTuWally , what version of SCM-Manager do you use? The latest SCM-Manager version (3.3.0) uses SVNKit 1.10.10, and as far as I can see this is the latest release.

**Comment by AnhTuWally** [comment]
Hello @pfeuffer, 

Thank you for the confirmation. We've just updated to SCM-Manager version (3.3.0). The repository has been working fine. Just out of curiosity, what is the best way to check the SVNKit version?

Regards,
Tu

**Comment by pfeuffer** [comment]
Hey @AnhTuWally , this is a good question. To be honest, I don't think that we have a good place to check this. The only way I can think of is [the build file](https://github.com/scm-manager/scm-manager/blob/develop/scm-plugins/scm-svn-plugin/build.gradle#L29) for the tag of the SCM-Manager version. Of course, this is not a convenient way. We will think about whether we should display this somwhere in the frontend. Thanks for the idea.
