### ISSUE TITLE
Build instructions for the CLI?

### ISSUE THREAD

**Issue by kastl-ars** [scm-manager/scm-manager#2221]
Hi,

I wanted to package the CLI for openSUSE, but found no instructions on how to build it? Did I miss them (due to being inexperienced with gradle)? Did I look in the wrong place?

Thanks in advance,
Johannes

**Comment by sdorra** [comment]
Hi, the CLI is located in a different repository and it is written in Go, so you don need Gradle knowledge.

https://github.com/scm-manager/cli

**Comment by kastl-ars** [comment]
Huh, why did I not find that repository yesterday? I was wondering if it was in a separate one.

Anyway, thanks for the fast reply!
