### ISSUE TITLE
Browsing a Subverision repository should use "head" instead of a fixed revision.

### ISSUE THREAD

**Issue by docbacardi** [scm-manager/scm-manager#2232]
## Issue description

I'm using SCM Manager v3.4.1 .

Browsing a Git repository in the WebUI shows the latest revision of folders and files. Opening the same URL again after more commits arrived will include these updates. The user can navigate to a fixed revision, but this is not the default.

This is different for a Subversion repository. The root folder behaves like a Git repository. It always shows the latest revision. The URL has the form
```
  https://SERVER/repo/NAMESPACE/REPOSITORY/code/sources/
```
Diving into a subdirectory - for example "trunk" - adds a revision to the URL:
```
  https://SERVER/repo/NAMESPACE/REPOSITORY/code/sources/REVISION/trunk/
```
"REVISION" is the number of the latest revision in the repository when the link is generated by SCM manager. However this is a link to a fixed revision. Opening this URL after more commits arrived will not show the changes.

#### Problem to be solved

I'm looking for a URL to display a folder or a file in its latest revision. It should not contain a fixed revision number, so that it stays valid even after more commits arrive.

The URL should be easy to generate with a web browser even for non-tech users. The process should be the same for Git and Subversion repositories.

I'm aware of the "Direct Filelink" plugin, but this works - as the name suggests - only for files and not for folders. Furthermore there seems to be no easy way for non-tech users to generate the URL.

#### Proposed solution

It would be great if browsing Subversion repositories could use "head" as the revision in the URLs like this:
```
  https://SERVER/repo/NAMESPACE/REPOSITORY/code/sources/head/trunk/
```

**Comment by pfeuffer** [comment]
Thanks for this suggestion, sounds very reasonable to me. Indeed you can use the revision `-1` right now, but you'd have to set this manually in the URL so this is only a little step for this.

What do you think, would this revision `-1` lead to confusion or would this be okay as a replacement for `head` from your suggestion?

**Comment by docbacardi** [comment]
Thank you for the workaround. This helps already a lot.

I would not mind a ```-1``` in the URL. Of course ```head``` would be clearer, but self-explanatory URLs are not my main concern here.

**Comment by fscholdei** [comment]
Hi docbacardi,

We have now added 'head' as a revision for Subversion repositories with [4ebf0e2](https://github.com/scm-manager/scm-manager/commit/4ebf0e2044ac3bc27b2d8f9312d437a9b73cb1b6) in core and [1356825](https://github.com/scm-manager/scm-editor-plugin/commit/1356825cd07409393734b4dc1762e12366d3e03e) in the editor-plugin. It will be available with the next release version. Thanks again for the suggestion!

Regards,
Florian

**Comment by docbacardi** [comment]
Just updated to v3.6.0 and everything works as expected. Thank you very much.
