### ISSUE TITLE
Git repository authentication with ssh-key

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#26]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/26) by ChrisM (Bitbucket: [Krimsar](https://bitbucket.org/Krimsar), GitHub: [Krimsar](https://github.com/Krimsar)).**

----------------------------------------

I've tried several GUI-Tools and most of them fail to handle http authentication properly (ether they don't ask for the user/pass and fail silently, or they don't provide a way to save the credentials).

Therefore I would like to see authentication support with a ssh-key-file, if that's possible at all.

Any other suggestions?

**Comment by sdorra** [comment]
Version 2 comes with a ssh plugin, which support ssh key authentication.
