### ISSUE TITLE
Support cloneing/branching at the server

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#41]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/41) by Hardcoded (Bitbucket: [Hardcoded](https://bitbucket.org/Hardcoded), GitHub: [Hardcoded](https://github.com/Hardcoded)).**

----------------------------------------

For a DVCS (hg, git, bzr) it would be nice if one could clone/branch a repository directly at the server.

**Comment by sdorra** [comment]
Version 2 support branching over the ui.
