### ISSUE TITLE
Resources defined in plugin.xml are loaded in alphabetical order instead of defined order.

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#429]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/429) by Jan Börner (Bitbucket: [jboerner](https://bitbucket.org/jboerner), GitHub: [jboerner](https://github.com/jboerner)).**

----------------------------------------

I have a couple of JavaScript files defined in the resources section of my plugin.xml file. The file depends on each other so they must be included to the frontend in the defined order. But it looks like they are loaded in alphabetical order.

I renamed the resource files to get the right order but that is not the nicest way.

**Comment by sdorra** [comment]
Version 2 uses webpack to bundle the plugins, so this should be no problem for version 2.
