### ISSUE TITLE
Support multiple repository localtions

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#457]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/457) by maugustin (Bitbucket: [maugustin](https://bitbucket.org/maugustin), GitHub: [maugustin](https://github.com/maugustin)).**

----------------------------------------

Hi,

I'd like to request the feature to have multiple repository locations (at least for HG).

We have multiple reasons for this:
* diskspace on one volume is limited, it would be perfect to add another diskdrive (windows maschine) as additional location for repositories
* not mixing up all repositories in one directory, but keeping them separate for read-only/archived repos and user created/active projects

Suggestions: in the repositories.xml the xml-element repositories could have a attribute location, or a subelement like repository-group with attribute location. This would keep the relative path in the repository-xml-element working.

And by the way: auto detection of new repositories in such a location would be very nice.

Kind regards,
Michael

**Comment by sdorra** [comment]
With version it is now possible to use different location for repositories. The locations are now stored in a file called `repository-paths.xml` and can point to any location.
