### ISSUE TITLE
online hook configuration

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#465]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/465) by Anonymous.**

----------------------------------------

Hello, first of all. Congratulations for this wonderfull application.

my contribution is a requirement. ¿ could be a way for configure repository hooks inside scm-manager? like a plugin that enables to upload desired script directly by the web.

thank you.

**Comment by sdorra** [comment]
The script plugin for version 2 is able to bind script execution to events. If the script is bound to a "PostReceiveRepositoryHookEvent" you can do what ever you want for every push.
