### ISSUE TITLE
Missed localization JS files.

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#511]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/511) by Vladislav Bauer (Bitbucket: [vbauer](https://bitbucket.org/vbauer), GitHub: [vbauer](https://github.com/vbauer)).**

----------------------------------------

We have the following errors in web console after login:

* GET http://git-trainings.noveogroup.com/resources/moment/lang/ru.js 404 (Not Found) (index):77
* GET http://git-trainings.noveogroup.com/resources/js/i18n/ru.js 404 (Not Found) (index):79
* GET http://git-trainings.noveogroup.com/resources/extjs/i18n/ext-lang-ru.js 404 (Not Found) 

UI shows English localization instead of Russian. Maybe it'll be better to hide errors when localization files are missed and use default localization?

**Comment by sdorra** [comment]
Version does not longer check, if the language is not supported.
