### ISSUE TITLE
Option to display user's real name

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#533]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/533) by vawagner (Bitbucket: [vawagner](https://bitbucket.org/vawagner), GitHub: [vawagner](https://github.com/vawagner)).**

----------------------------------------

We use LDAP to manage our user accounts. Unfortunately our company as a username format that is very unfriendly to our repository admins. The format is the letter 'E' followed by a 5-digit employee number, e.g. 'E12345'. Our repository admins have to follow strict legal requirements for making sure the right people have access to repositories, so they hate using the LDAP accounts because you can't tell at a glance who E12345 actually is.

If possible, we would hugely appreciate making it possible to display a user's real name everywhere the username is displayed, e.g. under Permissions for a repo. Something like:

Valerie Wagner (E12345)
or
E12345 (Valerie Wagner)

would be hugely useful. We see this format when selecting a user for addition to a repository, but then only the username after they are added.

**Comment by sdorra** [comment]
Version 2 does that.
