### ISSUE TITLE
Support "Pull Request" (or "Merge Request") within a single repository

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#557]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/557) by Brian Pratt (Bitbucket: [btowntkd](https://bitbucket.org/btowntkd), GitHub: [btowntkd](https://github.com/btowntkd)).**

----------------------------------------

Our company uses a single central repository, and we utilize the "git flow" workflow to implement features, issues, and releases.  This means that rather than having a separate 'forked' repository for every code change, developers do their work within different branches of a *single* Git repository.

We would like to implement a code review process similar to the "pull request" functionality; but instead of having a "pull request" between two forked repositories, we would like be able to submit a "merge request" - a request for merging two branches within a single repository.

I'm not sure if this makes more sense as a new, standalone plugin, or as an enhancement to the existing "Fork" plugin.  Currently within the "Fork" plugin, a developer can only create a pull request from a repository which has been previously "Forked."

**Comment by sdorra** [comment]
Version 2 has the review plugin which supports pull request based on branches.
