### ISSUE TITLE
Q: Is it possible to send notifications to an SCM group?

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#683]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/683) by Anonymous.**

----------------------------------------

I have looked around quite a bit and have not been able to find a way to do this other than using an external mailing list.

We have goups set up to perform our access control but would like to use the same groups as targets for notification emails.  This would drastically reduce the maintenance overhead associated with the notification mechansim.

Please let me know if I missed a config entry that would enable this.  Thx.

**Comment by sdorra** [comment]
This is not possible, because scm-manager does not know the members of external groups. SCM-Manager only knows the groups of the logged in user.
