### ISSUE TITLE
UI improvements - Branch creation/Tag operations

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#732]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/732) by Madhav Adepu (Bitbucket: [madhavadepu](https://bitbucket.org/madhavadepu), GitHub: [madhavadepu](https://github.com/madhavadepu)).**

----------------------------------------

Need UI improvement for easy way to create branch or remove branch from UI.
And also tag create or remove from UI.

**Comment by sdorra** [comment]
In scm-manager 2 it now possible to create branches over the web interface.
