### ISSUE TITLE
Disable "Remember me" in login

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#744]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/744) by Mark Bewley (Bitbucket: [Mark Bewley](https://bitbucket.org/Mark Bewley), ).**

----------------------------------------

A nice tool, we have been using for a while now.

It would be nice if there was a config option to disable the "remember me" in the login menu.

**Comment by sdorra** [comment]
The "remember me" was removed for scm-manager 2.
