### ISSUE TITLE
Git ssh-key authentication plugin to scm-manager 1.46: Error

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#745]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/745) by Anonymous.**

----------------------------------------

Ssh-key authentication for our Git repository would be nice to have, for not having to re-write password when push to repository. 

I tried the plugin from the dist folder in  https://github.com/litesolutions/scm-ssh-plugin, with recommendations to use version 1.46 of scm-manager. But it failed anyway.

I am trying this on my Windows 8 machine, before I'll iinstall it on the office build server with a Windows Server 2012.

I did the "upgrade to new version"-steps. 
I renamed the old scm-manager standalone (1.45).
I downloaded 1.46 and placed it at the same directory as the old. 
Uninstalled service. Installed service. 
This works fine!

Added the plugin (I can't see any other choices than only one way on how to install it), but this gives me an error 503.

**Comment by sdorra** [comment]
SCM-Manager 2 comes with a new ssh plugin. Please upgrade to version 2.
