### ISSUE TITLE
forward slash not supported on branch names

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#751]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/751) by Anonymous.**

----------------------------------------

whereas git does support forward slash for branch names, scm-manager does not preview those branches on the commits view.

this also has an impact on the plugins, such the notify pulgin, which is not able to see the new commit hence it does not notify those changes.

**Comment by sdorra** [comment]
This should be fixed for version 2.
