### ISSUE TITLE
Please implement gitweb servlet interface for git repositories

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#784]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/784) by Yuri Konotopov (Bitbucket: [nE0sIghT](https://bitbucket.org/nE0sIghT), GitHub: [nE0sIghT](https://github.com/nE0sIghT)).**

----------------------------------------

It would be nice if scm-manager will use [gitweb](https://git-scm.com/book/en/v2/Git-on-the-Server-GitWeb) for browsing git repositories (like hgweb for mercurial).

**Comment by sdorra** [comment]
SCM-Manager is designed to use its own interface for all kinds of web interfaces. Version 2 does not longer use hgweb.
