### ISSUE TITLE
Permission OWNER (but with no "Remove repository" option)

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#791]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/791) by x y (Bitbucket: [spookiecookie](https://bitbucket.org/spookiecookie), GitHub: [spookiecookie](https://github.com/spookiecookie)).**

----------------------------------------

Please add a feature to have following permission: OWNER without ability to remove repository.
Or OWNER with ability only to manager users.

**Comment by sdorra** [comment]
In version 2 it is possible to assign fine grained permissions.
