### ISSUE TITLE
Jenkins-plugin 1.12 is not fully compatible with jre1.8.

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#799]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/799) by Lars Astell (Bitbucket: [larsast](https://bitbucket.org/larsast), ).**

----------------------------------------

Use SCM-manager 1.46. Jenkins-plugin 1.12, JRE1.8   
The “Jenkins repository configuration view” doesn’t show up, which make it impossible to configure usage of different Jenkins servers.

After downgrading to JRE1.7 the “Jenkins repository configuration view” show up. 

It's the same behavior for the jira-plugin 1.16.

**Comment by sdorra** [comment]
This should be fixed for version 2.
