### ISSUE TITLE
Rest API for push

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#852]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/852) by František Lučivjanský (Bitbucket: [flucivja](https://bitbucket.org/flucivja), GitHub: [flucivja](https://github.com/flucivja)).**

----------------------------------------

Hi folks,

Does scm-manager or some plugin have support for push over the REST api? I am asking this because I haven't found this in the official documentation nor in plugin. If not, how hard do you think would be to create plugin for it?

Thanks,
Fero

**Comment by sdorra** [comment]
Modifying a repository over a rest api is possible with version 2 and the editor plugin.
