### ISSUE TITLE
Some plugins installation failed after new SSH plugin is installed

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#867]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/867) by branekbb (Bitbucket: [branekbb](https://bitbucket.org/branekbb), ).**

----------------------------------------

On previously mentioned site:

http://oss.aquenos.com/scm/scm-ssh-plugin/

new version of ssh plugin is released. Few improvements are listed.

We are using 1.49 version of scm-manager, and above plugin is incompatible with most of the plugins from scm-plugin repository. As example, if scm-mail-plugin is installed and you try to install ssh plugin 2.0.0, scm-server will not start any more. Recovery is to delete plugins dir, and reinstall all plugins you want.

Proven as not working with scm-ssh-plugin 2.0.0. are:
scm-mail-plugin
scm-fork-plugin
scm-userrepo-plugin

Some just want install, some will broke server completely.

Tested on:
ubuntu 12.04
openjdk 7
oraclejdk 7

ubuntu 16.05
openjdk7
oraclejdk 7 and 8

Any help possible here?

**Comment by sdorra** [comment]
SCM-Manager v2 comes with a new ssh plugin. Please upgrade to version 2.
