### ISSUE TITLE
Remember Me doesn't work

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#898]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/898) by Troels Larsen (Bitbucket: [TroelsL](https://bitbucket.org/TroelsL), GitHub: [TroelsL](https://github.com/TroelsL)).**

----------------------------------------

If I check the 'Remember Me' button on either of our two SCM Manager servers and click Login (with correct username/password), I it briefly displays a loading bar then reverts back to the login prompt.

Tried on the following browsers:
Chrome 56.0.2924.87 (64-bit)
Internet Explorer 11.0.9600.18537CO

In the console, I get the following errors:

POST http://scmsia/scm/api/rest/authentication/login.json 500 (Server Error)
i @ 761aa8f….js:72
request @ 761aa8f….js:73
request @ 761aa8f….js:224
run @ 761aa8f….js:1589
(anonymous) @ 761aa8f….js:52
761aa8f….js:1851 

Uncaught TypeError: Cannot read property 'failure' of undefined
    at L.failure (761aa8f….js:1851)
    at Object.callback (761aa8f….js:272)
    at constructor.afterAction (761aa8f….js:1529)
    at Ext.form.Action.Submit.failure (761aa8f….js:1586)
    at Ext.data.Connection.handleFailure (761aa8f….js:226)
    at f (761aa8f….js:71)
    at m (761aa8f….js:71)
    at 761aa8f….js:51

**Comment by sdorra** [comment]
The "Remember me" function was removed for scm-manager 2.
