### ISSUE TITLE
build scm-manager : missing dependencies ssp*

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#899]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/899) by Cédric Levasseur (Bitbucket: [Cedric Levasseur](https://bitbucket.org/Cedric Levasseur), ).**

----------------------------------------

It's impossible to build scm-manager due to missing dependencies

```
#!java

[ERROR] Failed to execute goal on project scm-core: Could not resolve dependencies for project sonia.scm:scm-core:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: com.github.sdorra:ssp-lib:jar:1.0.0-SNAPSHOT, com.github.sdorra:ssp-processor:jar:1.0.0-SNAPSHOT: Could not find artifact com.github.sdorra:ssp-lib:jar:1.0.0-SNAPSHOT in repo (http://myitbuild.emea.cegedim.grp/artifactory/repo) -> [Help 1]
```

Morever, the documentation (https://bitbucket.org/sdorra/scm-manager/wiki/build-from-source) should document which repository we should add to Artifactory to build it :

* https://maven.scm-manager.org/nexus/content/repositories/releases
* https://maven.scm-manager.org/nexus/content/repositories/snapshots/
* https://oss.sonatype.org/content/repositories/snapshots
* ...

**Comment by sdorra** [comment]
This should be fixed now.
