### ISSUE TITLE
groupmanager REST Api documentation

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#908]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/908) by Markus Beuttler (Bitbucket: [markusbe](https://bitbucket.org/markusbe), GitHub: [markusbe](https://github.com/markusbe)).**

----------------------------------------

Which methods are supported from the groupmanager REST api
api/rest/groupmanager give a complete list of the groups, members and groupmanagers

Is it possible to set the groupmanager over the api?

**Comment by sdorra** [comment]
SCM-Manager comes with a openapi rest documentation, which include plugins too. You only have to install the openapi plugin.
