### ISSUE TITLE
Integration of SVNKit 1.9.2

### ISSUE THREAD

**Issue by cesmarvin** [scm-manager/scm-manager#985]
**[Original report](https://bitbucket.org/sdorra/scm-manager/issue/985) by Georg Tsakumagos (Bitbucket: [Georg Tsakumagos](https://bitbucket.org/Georg Tsakumagos), ).**

----------------------------------------

We're facing one SVN related bug preventing merging a branch that should be fixed  somewhere from Version 1.9.0. Sadly the svnkit developer do not document wich version exactly. To be sure it would be nice you integrate the latest svnkit release to be sure its included.

We would like to test the fix and give response.

Best regards
Georg

**Comment by Metzlmane** [comment]
Can you please tell me also which version of SVN is included in 2.0.0.-rc4? I tried several commands, but I'm not able to determine the repository version on the server

**Comment by sdorra** [comment]
RC-4 uses version **1.9.0-scm3** and RC-5 uses **1.10.1-scm1**
